### ISSUE TITLE
faststart

### ISSUE THREAD

**Issue by svnpenn** [axiomatic-systems/Bento4#105]
Bento4 seems to have no way to set or even detect faststart (moov before mdat). Please resolve, thank you.

**Comment by svnpenn** [comment]
https://github.com/Martchus/tageditor/issues/11

**Comment by barbibulle** [comment]
faststart files are fully supported. In fact, that's the default/preferred mode for files created by the library. So in almost all cases you will see files output by Bento4 have moov before mdat. 
There is a special case with the mp4tag tool, where the class AP4_FileCopier is used and tries to preserve the original file as much as possible. This means that if the input file to mp4tag has moov before mdat, the output file will have the same layout. The same holds true for files with mdat before moov, the output will keep that layout.

**Comment by svnpenn** [comment]
@barbibulle thank you for quick response. Can Bento4 detect if a file is faststart without having to write a new file?

**Comment by barbibulle** [comment]
Yes, you can do that. The fastest way to do this is to process the file in
'fast' mode (ex: mp4info --fast) and look at the IsMoovBeforeMdat() method
of the AP4_File object.
Currently, the mp4info tool doesn't print out that information, but that
would be trivial to add.

**Comment by svnpenn** [comment]
I have [a workaround][1] for now:

~~~pl
#!/usr/bin/awk -f
/moov/ {
  print "faststart (moov before mdat)"
  exit
}
/mdat/ {
  print "not faststart (moov after mdat)"
  exit 1
}
~~~

[1]://github.com/svnpenn/a/blob/41c8fc8/etc/faststart.awk

**Comment by svnpenn** [comment]
@barbibulle this has not been fixed, why did you close?

**Comment by barbibulle** [comment]
Sorry for closing this. I was doing to cleanup in old tickets and moved a bit too fast ;-) I'm reopening this.

**Comment by barbibulle** [comment]
Fixed in master

**Comment by svnpenn** [comment]
https://github.com/axiomatic-systems/Bento4/issues/249
