### ISSUE TITLE
Build target x86-unknown-linux 32-bit on 64-bit host does not work

### ISSUE THREAD

**Issue by gabr1e11** [axiomatic-systems/Bento4#11]
Hi all,

I was trying to compile the tools on a 64-bit host so I used the x86-unknown-linux target. However it is missing the -m32 flag for both the compiler and the linker. I just added this to Build/Target/Config.scons:

env.AppendUnique(CCFLAGS = ['-m32'])
env.AppendUnique(CXXFLAGS = ['-m32'])
env.AppendUnique(LINKFLAGS = ['-m32'])

And it compiles, but haven't tried that library yet. Am I missing something?

Regards,
Roberto

**Comment by barbibulle** [comment]
Are you trying to build a 32-bit binary on a 64-bit host? Why not build the 64-bit binary (target = x86_64-unknown-linux)?

**Comment by gabr1e11** [comment]
Yes, that is the case. I'm compiling from my development machine for 64 and
32 bits. I have another machine with 32-bit processor and I wanted to run
some tests. Anyhow I can imagine anyone wanting to generate several targets
from the same development machine, so the 32-bit compilation should not be
different to any other target regarding cross-compilation.

**Comment by gabr1e11** [comment]
Seems like this is fixed now with target x86_unknown_linux. Thanks.
