### ISSUE TITLE
Regarding MP4 DASH packaging

### ISSUE THREAD

**Issue by sridhardvvce** [axiomatic-systems/Bento4#112]
Hi,

We are using Bento4 tools for dash packaging. First we are fragmenting the audio and video files using mp4fragment and then creating the DASH files using mp4 dash. We are using marlin format for DASH and the DASH files are encrypted.

We are playing the DASH files using expressplay marlin SDK in mobile. Marlin SDK is not playing some of the files because the audio and video segment duration is not same in the DASH package.

Below are the files we are using:

https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1247/drm_courses/9310/orig/42306/smallfiledashAudioStream.mp4

https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1247/drm_courses/9310/orig/42306/smallfiledashHighQualityVideoStream.mp4

https://s3-ap-southeast-1.amazonaws.com/learnyst/schools/1247/drm_courses/9310/orig/42306/smallfiledashMediumQualityVideoStream.mp4

First we are fragmenting the file using the mp4fragment like below:
mp4fragment input output

after that we are creating dash package using the following command(We are creating both marlin and widevine complaint DASH package)
mp4dash --encryption-key=$9:$10 --marlin --widevine --widevine-header=provider:intertrust#content_id:$9 fragmentedAudio.mp4 fragmentedVideo1.mp4 fragmentedvidoe2.mp4 -o outdir

The output is generated and the DASH has different segment duration for audio and video. audio has 2 sec segment duration and video has 6 seconds duration
<SegmentTemplate duration="2001" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4s" startNumber="1" timescale="1000"/>
<SegmentTemplate duration="6000" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4s" startNumber="1" timescale="1000"/>

Some of the DASH players are not playing if the segment duration is not matching.

Can you please help in resolving this issue

**Comment by colde** [comment]
Just out of curiosity, which DASH player is not handling segments with different lengths for audio and video? That is a totally valid stream, and the player is the place to fix that, but i have never personally encountered it.
