### ISSUE TITLE
mp42avc missing from latest built binaries for win32

### ISSUE THREAD

**Issue by troppoli** [axiomatic-systems/Bento4#117]
Hey folks, I just started looking a Bento4, and in the doc one of the included tools is mp42avc, looks perfect for me to debug some of the segments that I'm building to feed to a MSE, but it isn't included in the current built binaries for win32. Perhaps the doc is wrong and the tool is no longer made, either way the doc or the build is out of sync.

thanks.

**Comment by troppoli** [comment]
I downloaded the latest source, and duplicated the mp42aac win32 project folder and renamed it to mp42avc. Then did a search and replace on Aac => Avc and aac => avc. Then added this new project to the solution, and I was able to use it.

**Comment by barbibulle** [comment]
You're right, this tool should have been included in the binary release.
I'll make sure it does (along with mp42hevc as well) in the next update.

**Comment by barbibulle** [comment]
this should be fixed in the latest release
