### ISSUE TITLE
Packaging HLS for Fairplay supported offline usage

### ISSUE THREAD

**Issue by chartelt** [axiomatic-systems/Bento4#124]
Should have flag "EXT-X-SESSION-KEY" present in a master playlist as in:
https://tools.ietf.org/html/draft-pantos-http-live-streaming-20#section-4.3.4.5

**Comment by barbibulle** [comment]
Yes, it looks like this was added in a recent version of the spec. 
Signaling this tag in the master playlist is optional, but I think it is very useful. I will add support for that.

**Comment by chartelt** [comment]
Awesome! Although tagged as optional, many use-cases build on this flag being present.

**Comment by chartelt** [comment]
I do not have a patch available, but see that the latest update to this section could be of interest for Offline Playback and master-playlist with "PSSH" data: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.5

**Comment by chartelt** [comment]
Nevermind, mp4-hls.py has option "--signal-session-key" avail
