### ISSUE TITLE
How to play virtual subclip of dash streaming 

### ISSUE THREAD

**Issue by justflyhard** [axiomatic-systems/Bento4#126]
hi i am using bento4 for generating dash streaming...everything works perfect.But now i need to play subclip of video by providing start time and end time in  the url .Please suggest me how can i achieve this.Thanks

**Comment by barbibulle** [comment]
There's no general standard for passing a DASH subset as part of a manifest URL.
The ability to play a portion of a DASH stream is purely a function of the media player library you use, which should provide you with an API for providing start and end times of the segment you want to play.

**Comment by justflyhard** [comment]
@barbibulle  Thanks for reply .I am using exoplayer library for android.I didnt find any such way with exoplayer by searching whole day.I really appreciate if you have any references for this problem (like stackoverlfow url or something)
