### ISSUE TITLE
`mp4hls` single-file and AES encryption options are incompatible.

### ISSUE THREAD

**Issue by dtiesling** [axiomatic-systems/Bento4#127]
[EDIT]
I believe I've determined the root cause of the issue below. When using the single file option and trying to encrypt with AES the chunk ranges are not always divisible by 16. It appears that `mp4hls` does not add the padding to each chunk of the single file when doing the encryption. The lack of padding causes web players to choke on the audio decode.

[ORIGINAL]
I'm using `mp4hls` to create encrypted single-output HLS files. When I play these streams using any of the common browser players I get errors decoding the audio which results in the audio drifting significantly from the video.

Examples:
[here](http://output.jsbin.com/fagituguba]) or [here](http://dailymotion.github.io/hls.js/demo/?src=https%3A%2F%2Fstorage.googleapis.com%2Frush-externalresources%2Fbbb_test.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&dumpfMP4=false&levelCapping=-1&defaultAudioCodec=undefined)

bento command `mp4hls --output-single-file --encryption-key="{key}" --encryption-iv-mode=random -encryption-key-uri=XX_KEY_URL_XX -o "{output_dir}" "{mp4_path}"`

chrome://media-internals output
```
00:00:23 568	debug	Dropping audio frame which failed decode with timestamp: 23040000 us, duration: 21333 us, packet size: 349 bytes
00:00:33 967	debug	Dropping audio frame which failed decode with timestamp: 33450666 us, duration: 21333 us, packet size: 344 bytes
00:00:33 967	error	Large timestamp gap detected; may cause AV sync to drift. time:33472000us expected:33407999us delta:64001us
```

**Comment by dtiesling** [comment]
@barbibulle would you be able to confirm the issue I'm seeing?

**Comment by barbibulle** [comment]
@dtiesling You're right. I have fixed this in the master branch. I haven't pushed a new pre-compiled binary release, but if you can try from the source distribution, let me know if this works for you now.

**Comment by barbibulle** [comment]
@dtiesling correction, I have made the fix on my local branch, but haven't pushed it yet. I will push it later today.

**Comment by dtiesling** [comment]
Woooooooooo!!!!!!!! Thank you so much!

**Comment by dtiesling** [comment]
Latest master branch works great.

**Comment by dhaval02** [comment]
Please help me with below issue:
Unable to see IV value in manifest file,
Please help me with modifications in below command in bento4 (mp4hls packaging)

/root/bento4/Bento4-SDK-1-6-0-637.x86_64-unknown-linux/bin/mp4hls --hls-version=5 --master-playlist-name=index.m3u8 --encryption-mode=SAMPLE-AES --encryption-iv-mode=fps --encryption-key=248bd83f78dcf7dd4e7b2fa7e9ed32d0773aa50de5174249acf4264e96f78b76 --encryption-key-format=com.apple.streamingkeydelivery --encryption-key-uri=skd://773aa50de5174249acf4264e96f78b76 96p_mp4.mp4 144p_mp4.mp4 240p_mp4.mp4 360p_mp4.mp4 480p_mp4.mp4 576p_mp4.mp4 720lowp_mp4.mp4 720highp_mp4.mp4 1080lowp_mp4.mp4 1080highp_mp4.mp4 -o KundaliBhagya_5/ -f
