### ISSUE TITLE
I am getting error during encode video !  

### ISSUE THREAD

**Issue by saqibkafeel** [axiomatic-systems/Bento4#129]
whats i am doing wrong in it ! 

![image](https://cloud.githubusercontent.com/assets/6615261/23498617/531a4fce-fedd-11e6-8546-ee68fc79837f.png)

and thanks in Advance For any advice !

**Comment by barbibulle** [comment]
It looks like you're using python 3.x instead of python 2.x, can you check?

**Comment by saqibkafeel** [comment]
-yes that was version issue ! 

-now its showing this issue according to your provided doc !
-command =>  mp4dash --encryption- key=43215678123412341234123412341234:12341234123412341234123412341234 --marlin big_buck_bunny.mf4

![image](https://cloud.githubusercontent.com/assets/6615261/23598108/f35d5ef6-01ec-11e7-9728-09407e4a2c4d.png)

-then i use mp4dash --marlin --encryption-key=43215678123412341234123412341234:12341234123412341234123412341234 --marlin big_buck_bunny.m4f

-its done it like ! 

![image](https://cloud.githubusercontent.com/assets/6615261/23598182/83829762-01ed-11e7-9dd6-bd5caa939d9d.png)

-then i host my output file on local server and enter its key in ms3 server's example-config.json file as my demo 

![image](https://cloud.githubusercontent.com/assets/6615261/23598246/095ff564-01ee-11e7-89f3-c81691267b8d.png)

-output file folder set in htdocs like 
![image](https://cloud.githubusercontent.com/assets/6615261/23598482/9bf13018-01ef-11e7-812b-ca9e59ff579a.png)

-and its open in browser like that 
![image](https://cloud.githubusercontent.com/assets/6615261/23598501/b3cb4d2c-01ef-11e7-8761-d80ed5897390.png)

-then i join both links and run with Ms3SampleClient 

![image](https://cloud.githubusercontent.com/assets/6615261/23598522/d56cb218-01ef-11e7-9fe1-32f5a63747a4.png)

-is it write ?

-then i try to play this link in my android app sdk who's successfully play demo video provided by ExpressPlay Showing Just Black Screen and shows some error And after some time show video can't Play dialog

![image](https://cloud.githubusercontent.com/assets/6615261/23598586/4a8db952-01f0-11e7-8391-766efd3fe91e.png)

 
-emulator 

![image](https://cloud.githubusercontent.com/assets/6615261/23598646/ad1f662e-01f0-11e7-876c-a4833882bd14.png)

-error log when can't play dialog show 

![image](https://cloud.githubusercontent.com/assets/6615261/23598676/d193f5d8-01f0-11e7-8575-be596367b68b.png)

-also using this run time property 

![image](https://cloud.githubusercontent.com/assets/6615261/23598700/ee8db41c-01f0-11e7-8db5-105984c4da32.png)


-what i am doing wrong in this whole scenario ?

Thanks In Advance For Any Best Advice !
