### ISSUE TITLE
Cannot extract atom using bash script

### ISSUE THREAD

**Issue by AndriusWild** [axiomatic-systems/Bento4#131]
Hello,
I can extract `udta` atom running a command in Linux terminal, e.g.
`mp4extract moov/udta 'media/data/Family Pictures/2016/2016-10/20161030/20161030_174720.mp4' 'media/data/Family Pictures/2016/2016-10/20161030/20161030_174720.txt`
but when I am trying to do the same using a bash script
```
cd "$sourcedir"
for filelist in *.mp4;
do
mp4extract moov/udta "$sourcedir/$filelist" "$sourcedir/${filelist%.*}.txt"
done
```
I get this error:
```
mp4extract version -r
mp4extract: unknown options specified, ignoring: /media/data/Family Pictures/2016/2016-10/20161030/20161030_174720.mp4 /media/data/Family Pictures/2016/2016-10/20161030/20161030_174720.txt 
Open: open(moov/udta) failed (src/mp4file.cpp,398)
```
Am I doing anything wrong? Same code works for ffmpeg and other tools.
I am using a static build.

**Comment by barbibulle** [comment]
It looks like you are not properly quoting the command line arguments, so if there is a space character in your file path (ex: '.../Family Pictures/...'), it is treated as two separate paths.
