### ISSUE TITLE
mp4-dash-encode uses outdated audio codec

### ISSUE THREAD

**Issue by bayantaani** [axiomatic-systems/Bento4#132]
I was trying to create multiple resolutions of an mp4 fragmented video using mp4-dash-decode.py, and it kept giving me this error:
`Unknown encoder 'libfaac'`
which is the audio codec for ffmpeg. Accoring to [this question](http://stackoverflow.com/questions/19774975/unknown-encoder-libfaac) on stackoverflow, ffmpeg removed the support for libfaac.
However, it is still hardcoded in mp4-dash-encode, line 111 as the default audio encoder.
For those having the same error, you can change line 111 to:
`parser.add_option('--audio-codec', dest='audio_codec', default='aac',`

**Comment by barbibulle** [comment]
The default setting isn't libfaac, but libfdk_aac, which is the highest quality AAC encoder available with ffmpeg. However, not all ffmpeg distributions are compiled with support for libfdk_aac, so you can use "--audio-codec aac" on the command line to use the builtin aac codec instead (with a lower quality result).

**Comment by bayantaani** [comment]
Yes you're right.. I was mistaken, the default is libfdk_aac. And apparently my ffmpeg is not compiled with libfdk_aac support.
I must have misread it and googled for libfaac instead.
