### ISSUE TITLE
Smart pointer referenced after release

### ISSUE THREAD

**Issue by amartens1** [axiomatic-systems/Bento4#138]
In Source/C++/Apps/Mp4Info/Mp4Info.cpp by line 1564
the 'input' smart pointer is released. However, it is reused shortly after (lines 1578/1580).

(A common practice to avoid this kind of issues is to assign 'NULL' to smart pointers after releasing them)

**Comment by barbibulle** [comment]
Thanks for the report. I fixed this in the master branch. (luckily, this issue didn't cause any trouble, since the AP4_File object, which has a reference to the stream, has a lifetime that was longer than the scope in which the input reference was used).
