### ISSUE TITLE
PlayReady license issued but not playing

### ISSUE THREAD

**Issue by deisenbacher01** [axiomatic-systems/Bento4#14]
Hello,

I am running bento4 on a windows7, below is my syntax I copied from your PlayReady example using the MS public license servers 

This is the example that is listed in the bento4 doc

mp4-dash.py --exec-dir c:\Bento4-SDK-1-4-2-594.x86-microsoft-win32-vs2010\utils\bin\win32 frag_inception_audio.mp4 frag_inception_video.mp4 -f -o encrypted_MS/ --mpd-name=inception.mpd --encryption-key=09e367028f33436ca5dd60ffe6671e70:b42ca3172ee4e69bf51848a59db9cd13 --playready-header=LA_URL:http://playready.directtaps.net/pr/svc/rightsmanager.asmx 

when I go to play the media in the DASH reference player
http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/index.html 

I get an error "unsupported video type or invalid file path" 

Can you assist?
 I am trying to get the public MS test server to work so then I can test another PR server once I know the public one works 

THX

**Comment by barbibulle** [comment]
Hi David, I'm following up on this issue via the zendesk support site.

**Comment by chiranjeevikona** [comment]
Hi,

iam trying to package the video file using Bento4 packager, how can we get the encrypted key??
