### ISSUE TITLE
Wrong box order in sample table box

### ISSUE THREAD

**Issue by lnwhome** [axiomatic-systems/Bento4#142]
Hi,
I'm creating MP4 video init segment which contains contains Sample Table Box. According to ISO spec stbl must contain following boxes: stsd, stts, stsc, stsz, stco in order specified. See below, please.

"ISO 14496-12 Section 6.2.3 Box Order says
4) It is recommended that the boxes within the Sample Table Box be in the following order:
Sample Description, Time to Sample, Sample to Chunk, Sample Size, Chunk Offset."

The problem is that AP4_SampleTable::GenerateStblAtom() method generates boxes in different order(stsd, STSZ, stsc, STTS, stco). Can you fix the box order or advice how to create stbl using different method(which generates boxes in right ), please ?

**Comment by barbibulle** [comment]
This can easily be fixed. I'll make sure this is fixed in the next release.
Have you found a player for which the order of the boxes causes a problem?

**Comment by lnwhome** [comment]
No, I just created init segment and compared it with one generated by reference platform. I spotted the difference and then confirmed using the spec that Bent4 does not follow recommendations. So, at this point this is only theoretical issue but I guess it's good to fix it to avoid possible problems in the future.
