### ISSUE TITLE
Mp4decrypt takes off encryption; videos corrupted

### ISSUE THREAD

**Issue by Rocksteady18** [axiomatic-systems/Bento4#143]
Hi I have a video I got from a dash stream.  I used the key and mp4decrypt to take off the encryption and it removed.  However when I try to play the output in a media player it is scrambled:

![capture](https://cloud.githubusercontent.com/assets/4706460/26258475/bd4701e2-3c92-11e7-9860-46791a5e631d.JPG)

Is there any way to fix this so I can watch the video?

**Comment by barbibulle** [comment]
Most likely the key you used isn't the right one.
Unfortunately, there's no way to verify if the key is correct or not, other than so see if the elementary stream produced when decrypting is a valid stream (can be played).
Are you sure you used the right key?

**Comment by Rocksteady18** [comment]
No not sure it's the right key I bet that's the problem.  Before decrypt mediainfo says encrypted and after it does not say encrypted, that's why I thought it was the right key no other I tried did that but it must be some fluke that the encrypted came off mediainfo because the file is garbage.  ffmpeg says it has too many frames or something like that probably wrong key.  Thanks anyway for helping
