### ISSUE TITLE
Empty master HLS manifest

### ISSUE THREAD

**Issue by jbboehr** [axiomatic-systems/Bento4#145]
We've been having an issue where the HLS master manifest generated by `mp4-dash` (not `mp4-hls`) is empty, example:

```
#EXTM3U
# Created with Bento4 mp4-dash.py, VERSION=1.7.0-614
#
#EXT-X-VERSION:6

# Media Playlists

# Audio

# Video
```
```
#EXTM3U
# Created with Bento4 mp4-dash.py, VERSION=1.8.0-614
#
#EXT-X-VERSION:6

# Media Playlists

# Audio

# Video
```

The DASH manifest works correctly. This manifest was generated via the command:

```bash
mp4-dash --verbose --debug -o mp4-dash-output --mpd-name=master.mpd --profiles=on-demand --rename-media --media-prefix 51777258 --no-split --hls --hls-master-playlist-name=master.m3u8 *.f.mp4
```

Here are the full samples attached:
- [sample.zip](https://github.com/axiomatic-systems/Bento4/files/1020513/sample.zip) (7fffc8a)
- [sample2.zip](https://github.com/axiomatic-systems/Bento4/files/1020531/sample2.zip) (9a27e41)

Any ideas?

**Comment by jbboehr** [comment]
Apparently the video doesn't have an audio track.

**Comment by barbibulle** [comment]
Sorry, I hadn't had time to review this earlier. As it turns out, this is something that was fixed on my local branch. I've just pushed an update to master, which should achieve the same results as your PR. Let me know if this works for you.

**Comment by barbibulle** [comment]
fixed in master
