### ISSUE TITLE
PSSH object not added to init.mp4 segments (playready)

### ISSUE THREAD

**Issue by Murmur** [axiomatic-systems/Bento4#151]
I am trying to create DRM dash content and would like to have PSSH objects both in manifest and init.mp4 files. Playready PSSH box is not found in init files so am doing something wrong with a command line arguments?

This is a simplified version just Playready only. Final result should use Playready, Widevine and Marlin pssh. Tried both KEY:VALUE pairs and @FILENAME.xml syntax.

"--playready-header=LA_URL:https://pr-gen.test.expressplay.com"
"--playready-header=@./playready-object.xml"

**mp4-dash.py command** VERSION = "1.8.0" SDK_REVISION = '615'
```
%python% "%bento%\utils\mp4-dash.py" --exec-dir="%bento%\bin" ^
 --always-output-lang --use-segment-timeline ^
 --output-dir=./output --force --mpd-name=manifest.mpd ^
 --encryption-key=43215678123412341234123412341234:12341234123412341234123412341234 ^
 "--playready-header=LA_URL:https://pr-gen.test.expressplay.com" ^
  .\temp-720p_frg.mp4 ^
  .\temp-128k_frg.mp4
```

**Playready object in manifest.mpd**
```
<mspr:pro>bgIAAAEAAQBkAjwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AZQBGAFkAaABRAHoAUQBTAE4AQgBJAFMATgBCAEkAMABFAGoAUQBTAE4AQQA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBtAHUAaABqAFQAOQB1AEMAYQBzAHMAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwBwAHIALQBnAGUAbgAuAHQAZQBzAHQALgBlAHgAcAByAGUAcwBzAHAAbABhAHkALgBjAG8AbQA8AC8ATABBAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</mspr:pro>
```

**Base64 decoded mspr value**
```
<WRMHEADER xmlns="http://schemas.microsoft.com/DRM/2007/03/PlayReadyHeader" version="4.0.0.0"><DATA><PROTECTINFO><KEYLEN>16</KEYLEN><ALGID>AESCTR</ALGID></PROTECTINFO><KID>eFYhQzQSNBISNBI0EjQSNA==</KID><CHECKSUM>muhjT9uCass=</CHECKSUM><LA_URL>https://pr-gen.test.expressplay.com</LA_URL></DATA></WRMHEADER>
```

ps: Ignore laurl value its not the working license request url.

**Comment by Murmur** [comment]
Now I can see if keep my eyes open, logging file displayed a warning `since hbbtv-1.5 profile is selected, no PlayReady PSSH box will be added to the init segments`. Changing a profiles attribute activates PSSH element in an init segments.
`--profiles="urn:mpeg:dash:profile:isoff-live:2011,http://dashif.org/guidelines/dash264"`

I don't know a reason why hbbtv1.5 profile disables PSSH in an init segment, I have always seen PSSH box in an every test content available.

**Comment by barbibulle** [comment]
My memory on this is a bit rusty, but my recollection is that for HbbTV 1.5, having a PSSH in the init segment wasn't allowed.

**Comment by Murmur** [comment]
Thanks for the comment, yes I admit DASH+DRM has always been a bit fuzzy world in HbbTV compared to the normal PC software environments(dashjs players etc). It's sometimes extremely frustrating to get VOD catalog work on different hbbtv manufacturer platforms. No one want to run an entire VOD catalog through a customized hbbtv dash profile segmenter to make them work properly. Just playback the same PC browser content already found in CDN server cluster. Thats the ideal case anyway.

This is what latest but nowdays a bit obsolete v1.5 release say. Last line is what I don't fully understand ` value of the SystemID field corresponding to that DRM system shall be specified as well as the encoding of the Data field.` What is this _encoding_ of the data field they talk about.
https://www.hbbtv.org/wp-content/uploads/2015/07/HbbTV-specification-1-5.pdf
```
C.4.1 „pssh‟ box
An ISOBMFF file may contain multiple Protection System Specific Header  ('pssh') boxes 
(as defined inCENC [4]).  The terminal shall be able to identify and use the 'pssh' box 
that corresponds to the DRM system that is available to the terminal. 
Usage of the pssh by the DRM in either  moov or  moof box is optional. 
If a DRM system uses the pssh box, then the value of the SystemID field  corresponding to
that DRM system shall be specified as well as the encoding of the Data field.
```

I guess we can close this issue as a fix is not to pass hbbtv profile argument for bento4 segmenter.
