### ISSUE TITLE
Force option not working?

### ISSUE THREAD

**Issue by zocheyado** [axiomatic-systems/Bento4#157]
So I was reading in the docs about the -f --force option and I can't seem to get it to work at all. This is the direct quote from the docs 

>   -f, --force           Allow output to an existing directory

But if you try and actually run that with -o (specifying your output directory) you get 
```[Errno 21] Is a directory: 'outputfolder'```

Any idea?

**Comment by barbibulle** [comment]
Can you share the entire command line you're using?

**Comment by zocheyado** [comment]
Basically straight from the docs,
`mp4dash -f input.mp4 -o customOutputFolder`

This is how I understand the docs to work but in testing I have also tried
`mp4dash -f --force input.mp4 -o customOutputFolder`
`mp4dash --force input.mp4 -o customOutputFolder`

**Comment by barbibulle** [comment]
I'm not able to reproduce this problem. What platform are you running on?
Can you run the same command with the `--debug` option?

**Comment by zocheyado** [comment]
Interesting I seem to have been able to find how this happens. So if I run a totally normal command with a fully qualified input file like this 
```
/bento4/bin/mp4dash -f test.mp4 -o output --debug
```
the force command works perfectly. However if I use a wildcard in my search (like I do in my actual project) like this
```
/bento4/bin/mp4dash -f file_prefix* -o output --debug
```

It will error out. saying >IOError: [Errno 21] Is a directory: 'output'

Interesting that the command in general works but specifically the force option fails when using this wildcard.

**Comment by barbibulle** [comment]
That's very odd. I tried exactly that scenario, with two mp4 files and a wildcard, and I can't reproduce the error. Can you send the console output you're getting (so I can see where in the code this error is triggered)?
