### ISSUE TITLE
MP4Dash command fails with audio?

### ISSUE THREAD

**Issue by zocheyado** [axiomatic-systems/Bento4#159]
I am running Bento4 Mp4Dash to convert my fragmented video files into MPEG-DASH streaming videos. However I seem to get this error 

> ERROR: unsupported input file, more than one "traf" box in fragment

but only if I have audio enabled. I have found that if I run -an in FFMPEG (to ignore the audio tracks) my MP4Dash command runs just fine, any ideas as to why this would happen? 

*Edit* here is my debug output and command
```
osboxes@osboxes tmp]$ /externalHome/bento4/bin/mp4dash test.mp4 -o test --debug
Parsing media file 1: test.mp4
Processing MP4 file test.mp4
  found 1 segments
COMMAND:  ['/externalHome/bento4/utils/../bin/mp4info', '--fast', '--format', 'json', 'test.mp4']
COMMAND:  ['/externalHome/bento4/utils/../bin/mp4dump', '--verbosity', '1', '--format', 'json', 'test.mp4']
ERROR: unsupported input file, more than one "traf" box in fragment

```

**Comment by zocheyado** [comment]
This apparently can be fixed by using the ffmpeg command -moveflags separate_moof. This splits out the audio and video tracks which is why it was not working before. Still might be worth looking into but for my purposes this is done.

**Comment by barbibulle** [comment]
If your input file consists of fragments that are 'multiplexed' (both audio and video elementary streams in a single fragment) then you'll get this error. Most DASH profiles disallow this type of mixed fragments so the Bento4 tools refuse then. You should be able to re-fragment your media with 'mp4fragment', or configure your encoder to produce non-multiplexed fragments (it seems you have found how to do this with ffmpeg)
