### ISSUE TITLE
Ap4PosixRandom uses /dev/random. /dev/urandom would be better

### ISSUE THREAD

**Issue by ATrattnig** [axiomatic-systems/Bento4#16]
System/Posix/Ap4PosixRandom uses /dev/random. The read function to /dev/random can be blocking. In our case this is not acceptable. Using /dev/urandom is sufficient for encryption key generation and the read function is never blocking. For an extended explanation I recommend http://www.2uo.de/myths-about-urandom/. 

Best Regards,
Armin Trattnig (bitmovin)

**Comment by barbibulle** [comment]
This makes sense. Thanks.
I'll make the change in the source tree.

**Comment by barbibulle** [comment]
Fixed
