### ISSUE TITLE
Memory leak (moov atom) in AP4_Processor::Process

### ISSUE THREAD

**Issue by mchelnokov** [axiomatic-systems/Bento4#162]
Hi,
There is a pointer to AP4_MoovAtom declared [here](https://github.com/axiomatic-systems/Bento4/blob/ce01e533ffe4b06668473406ab286a9afc5fbe76/Source/C%2B%2B/Core/Ap4Processor.cpp#L433), the atom object is created [here](https://github.com/axiomatic-systems/Bento4/blob/ce01e533ffe4b06668473406ab286a9afc5fbe76/Source/C%2B%2B/Core/Ap4Processor.cpp#L441) and assigned to that pointer [here](https://github.com/axiomatic-systems/Bento4/blob/ce01e533ffe4b06668473406ab286a9afc5fbe76/Source/C%2B%2B/Core/Ap4Processor.cpp#L447). But then the moov atom is never deleted.
I think, "delete moov" is missed after [this line](https://github.com/axiomatic-systems/Bento4/blob/ce01e533ffe4b06668473406ab286a9afc5fbe76/Source/C%2B%2B/Core/Ap4Processor.cpp#L741).

Best regards,
Michael Chelnokov.

**Comment by mchelnokov** [comment]
Hi,
Just like to remind about this issue, it obstructs using of AP4_Processor-derived classes, especially when input moov contains some AP4_UnknownAtom (then input stream isn't released too).

Best regards,
Michael Chelnokov.

**Comment by barbibulle** [comment]
Sorry about the delay. I'll try to get some time over the coming week to fix that.
