### ISSUE TITLE
questions about mpd

### ISSUE THREAD

**Issue by jjmares** [axiomatic-systems/Bento4#166]
hi!

when we have some mpd file is there any way to obtain the complete full mp4 files? (or maybe the links of them)

in another hand, once you have the complete mp4 encrypted file and it plays well from internet streaming, is possible to get the key someway? maybe its stored in some cache or similar?

**Comment by barbibulle** [comment]
To obtain a MP4 file from an MPD, what you need to do is write or find a tool that will parse the MPD and download the media segments described in the MPD (picking just one of the bitrates in case the MPD is multi-bitrate). Once you have all the segments, re-combining the segments into a single file is fairly easy. I've used tools like this in the past, but I don't know of one that's open source... maybe I should write one!

However, if the media is encrypted, it is most likely delivered with an associated DRM, which means that you cannot access the decryption key. Only the secured DRM engine in your player or OS on which your player is running can access the key and decrypt the media (internally to its private decoder pipeline).
