### ISSUE TITLE
Dolby Digital Plus generation broken with Smooth + Encryption

### ISSUE THREAD

**Issue by nadimix** [axiomatic-systems/Bento4#168]
When creating an encrypted smooth streaming package with Dolby Digital Plus tracks using mp4-dash.py I get `ERROR: 'dolby_digital_info'`. So is not able to fill the `QualityLevel fields` in the client manifest.

This error happens because `track.info['sample_descriptions'][0]` does not contains `['dolby_digital_info']`.

I found that is missing a case for `AP4_ATOM_TYPE_EC_3` in `AP4_EncaSampleEntry::ToTargetSampleDescription` at _Ap4proessor.cpp_ which should returns the content of `dec3` box, just like the MP4A case with the `esds` box.

So, `desc = prot_desc->GetOriginalSampleDescription()` in `ShowSampleDescription_Text` at `Mp4Info.cpp` there is not `dec3` box.

I tried to implement it but I always get` dec3 = NULL` after `AP4_Dec3Atom* dec3 = AP4_DYNAMIC_CAST(AP4_Dec3Atom, GetChild(AP4_ATOM_TYPE_DEC3));`.

It should be easy because the box structure when on the clear and encrypted is pretty similar:
EC-3 on the clear bytes (9.isma)
```
EC-3 on the clear
size ec-3     ec-3 Payload                                                 size dec3     payload 	
0031 65632d33 000000000000000100000000000000000002001000000000bb8000000000 000d 64656333 1200200f00

EC-3 encrypted
size enca     enca Payload                                                 size dec3     payload 	
0081 656e6361 000000000000000100000000000000000002001000000000bb8000000000 000d 64656333 1200200f00
```
But, at this moment, I am not able to get a proper solution by myself although I will keep working on this.

By other hand, I found that the number of channels is not correctly parsed in DASH and Smooth. I think is for the same issue so it returns always 2 channels by default.

Thank you Gilles in advance

**Comment by barbibulle** [comment]
I have pushed a fix for this on the master branch. The issue was that the 'dec3' atom wasn't instantiated with its proper class when inside an 'enca' container. 
Regarding the number of channels, do you have an example stream that shows the error? I have tried with a 5.1 stream and the number of channels (6) is computed correctly in my case.

**Comment by nadimix** [comment]
Thanks a lot for the quick fix !!

Regarding the number of channels, you are right. I am using an old version of mp4encrypt and mp4fragment which are causing my issue. I tested that the current version from master works well with dolby digital plus tracks :)
