### ISSUE TITLE
ERROR: Values instance has no attribute 'track_key_infos'

### ISSUE THREAD

**Issue by andreyrikunov** [axiomatic-systems/Bento4#169]
Hi,

have got error trying to create smooth stream from individually encrypted tracks  -  _ERROR: Values instance has no attribute 'track_key_infos'_:

`mp4encrypt --global-option 'mpeg-cenc.piff-compatible:true' --method MPEG-CENC --key 1:395a3609b167c1147d32b694a6ac11eb:random --property 1:KID:ce5b460dab334e879ec446a7a18bf175 v.mp4 v.e.mp4`

`mp4encrypt --global-option 'mpeg-cenc.piff-compatible:true' --method MPEG-CENC --key 1:395a3609b167c1147d32b694a6ac11eb:random --property 1:KID:ce5b460dab334e879ec446a7a18bf175 a.mp4 a.e.mp4`

`mp4dash --verbose --smooth --playready-header='LA_URL:http://test.playready.microsoft.com/service/rightsmanager.asmx?PlayRight=1&UseSimpleNonPersistentLicense=1'  v.e.mp4 a.e.mp4`
```
Profiles: urn:mpeg:dash:profile:isoff-live:2011
Parsing media file 1: v.e.mp4
Parsing media file 2: a.e.mp4
Audio: {('audio', 'en', u'mp4a'): [File 2#1]}
Video: {('video', u'avc1'): [File 1#1]}
Subtitles: {}
INFO: adjusting segment duration for audio track File 2#1 to 10.0 to match the video
audio track: File 2#1 - language=en, max bitrate=137705, avg bitrate=136648, req bandwidth=136002, codec=mp4a.40.2
video track: File 1#1 - language=en, max bitrate=6183481, avg bitrate=5305269, req bandwidth=5810041, codec=avc1.640028
Processing and Copying media file v.e.mp4
Processing and Copying media file a.e.mp4
ERROR: Values instance has no attribute 'track_key_infos'
```

**Comment by barbibulle** [comment]
I'll work on this bug shortly. In the meantime, have you tried doing the packaging and encryption in one step? (i.e use the --encryption-key option of the mp4dash tool)

**Comment by andreyrikunov** [comment]
this way? 

`mp4dash --smooth --encryption-key=ce5b460dab334e879ec446a7a18bf175:395a3609b167c1147d32b694a6ac11eb --playready-header='LA_URL:http://test.playready.microsoft.com/service/rightsmanager.asmx?PlayRight=1&UseSimpleNonPersistentLicense=1' v_h264_a_aac.mp4`

yep, works perfectly

**Comment by barbibulle** [comment]
I pushed a fix for this. It is usually simpler to do encryption and packaging in one step. The packager supports pre-encrypted tracks for cases where files are encrypted ahead of time (possibly by a different tool), so that's still a supported mode.

**Comment by andreyrikunov** [comment]
so quick!

**Comment by andreyrikunov** [comment]
> The packager supports pre-encrypted tracks for cases where files are encrypted ahead of time 

that's exactly my case
thanks a lot!

**Comment by andreyrikunov** [comment]
would be good to see the fix in the next release, when is it coming?

**Comment by gopiio** [comment]
Hi,

if you have following case, how would you do it?

I have SD,720p, 1080p and audio tracks.  each of them will have unique key:keyID pair.  I am using mp4encrypt to encrypt each of the tracks.
E.g
`mp4encrypt --method MPEG-CENC --key 1:66104510A3834E9A0C3BF1143204FD4B:0123456789abcdef --property 1:KID:323E43CCF8199A2CFE0F995B56AA807B fragments/2800k.mp4 encrypted/2800k.mp4`

Now I am running mp4dash to create the DASH output.  My command looks as this:
`~/Tools/bento4/bin/mp4dash -f -o output --widevine --widevine-header=provider:widevine_test --playready --playready-header=LA_URL:https://xbox.playready.msf.ioko.com/rightsmanager.asmx encrypted/800k.mp4 encrypted/1500k.mp4 encrypted/2800k.mp4 encrypted/4500k.mp4 encrypted/audio.mp4`

I am getting following error

> ERROR: Mp4Track instance has no attribute 'key_info'

Is it possible to produce DASH with multiple keys?  Is there anywhere you can use mp4dash to setup multiple keys?

Thanks

**Comment by andreyrikunov** [comment]
You can't simply combine Widevine and Playready packaging on the same basis of tracks encrypted with unique keys because _mp4dash_ supports **PlayReadyHeader 4.0.0.0** only which is **single key** only while Widevine supports multiple keys.

**Comment by gopiio** [comment]
@andreyrikunov thanks for the info regards to playready header
