### ISSUE TITLE
How do we decrypt the AES-CBC encrypted fMP4 content ?

### ISSUE THREAD

**Issue by gowtham9b** [axiomatic-systems/Bento4#170]
How do we exactly find the encrypted blocks? How do we handle video and audio streams separately?

**Comment by barbibulle** [comment]
If you have an encrypted MP4 file (fragmented or not), you can use the mp4decrypt tool to decrypt it. You need to pass the decryption key for each track in the file.
For example, if you have a file with an audio track with ID 1 encrypted with key 000102030405060708090a0b0c0d0e0f and a video track with ID 2 encrypted with key 00112233445566778899aabbccddeeff, you would invoke:
mp4decrypt --key 1:000102030405060708090a0b0c0d0e0f --key 2:00112233445566778899aabbccddeeff encrypted-file.mp4 decrypted-file.mp4

**Comment by gowtham9b** [comment]
Thank you for your response. I'm trying to implement my own decryption, I assume I can take reference from mp4decrypt?

**Comment by barbibulle** [comment]
If you need to implement your own decryption, I would recommend starting with the MPEG Common Encryption specification (ISO/IEC 23001-7) , which contains all the details.

**Comment by gowtham9b** [comment]
Hey. Where can I encrypted FMP4 content or how do I create one?
