### ISSUE TITLE
Support for HLS fMP4 with FairPlay

### ISSUE THREAD

**Issue by zshenker** [axiomatic-systems/Bento4#171]
I was wondering what the current state of support was for doing HLS with fMP4 segments, with FairPlay DRM?

I can see that mp4-dash.py supports the 'cbcs' mode for CENC but for hls there seems to be only `--hls` and `--hls-key-url`. I can't see any way to set the key format.

With mp4-hls.py it seems like there is only support for TS output, and not fMP4.

Is there something I am missing or any plans to support this use case?

**Comment by samlee64** [comment]
If you look at the Mp4Encrypt.cpp you can see that one of the encryption methods if MPEG-CBCS which is what I'm pretty sure what you're looking for because mp4encrypt can take in fMP4

**Comment by barbibulle** [comment]
There is basic support for HLS with fMP4, using the mp4dash tool (it was much easier to do the implementation in the DASH packager, which natively supports the MP4 format, rather than duplicate the code and add MP4 support to mp4-hls.
To use cbcs, pass '--encryption-cenc-scheme=cbcs' on the command line.

WARNING: this feature is not fully finished, and a major known issue is that the output isn't 100% compliant with the spec yet, and as a result the video tracks don't always work with Apple clients (iOS and macOS). The reason is complicated, but known, and we are working on a fix ASAP.

**Comment by barbibulle** [comment]
This feature is now supported for H264 (AVC) streams. H265 (HEVC) is still not 100% there, but should be soon.

**Comment by arielsfr** [comment]
"WARNING: this feature is not fully finished, and a major known issue is that the output isn't 100% compliant with the spec yet, and as a result the video tracks don't always work with Apple clients (iOS and macOS)."

Would this be the reason I'm getting the error message: "Progressive stream type not supported or the stream has an error" in OS X Safari?

**Comment by barbibulle** [comment]
This should now work for H.264 content (the remaining part of the work is for H.265/HEVC content).
Are you getting this error with H.264?

**Comment by arielsfr** [comment]
Yes, H.264, with version Bento4-SDK-1-5-0-615.universal-apple-macosx.zip.

**Comment by jed2nd** [comment]
Hey guys, I really hope I'm just missing something stupid, and If so, I apologize for hopping onto this thread.  Here's what I'm attempting to run:

`mp4-dash.py --force --hls --encryption-key=11111111111111111111111111111111:11111111111111111111111111111111:11111111111111111111111111111111 --encryption-cenc-scheme=cbcs --verbose ./big_buck.mp4`

Just to make sure I'm not missing something in the rest of my process, I've got a `key.bin` that contains just 1s (plus the terminating character), in my `output/video/avc1/`.  I've got a simple webserver up to feed these files.  Testing on an iOS device results in the following requests:

```
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/master.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/master.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/video/avc1/media.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/video/avc1/init.mp4 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/audio/und/mp4a/media.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/video/avc1/key.bin HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/master.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/video/avc1/media.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/master.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/video/avc1/media.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/audio/und/mp4a/media.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/video/avc1/init.mp4 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/video/avc1/key.bin HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/video/avc1/init.mp4 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/audio/und/mp4a/media.m3u8 HTTP/1.1" 200 -
10.0.0.123 - - [11/Oct/2017 18:29:04] "GET /output/video/avc1/key.bin HTTP/1.1" 200 -
```

No video is ever displayed :(

Been bashing my head against this fruitlessly.  I'm sure I'm just doing something wrong.

**Comment by barbibulle** [comment]
Your key.bin file needs to be a 16-byte binary file with the byte 0x11
repeated 16 times, not a file with the ascii string '
11111111111111111111111111111111'.  Is that what you have?
(on the command line, keys and IVs are represented in hexadecimal, because
you can't really input binary data on the command line, but the data itself
is what's stored in the media and/or key files)

**Comment by jed2nd** [comment]
@barbibulle yeah, that's what I have.
Here's what it looks like in xxd:

```
00000000: 1111 1111 1111 1111 1111 1111 1111 1111  ................
00000010: 0a                                       .
```

**Comment by jed2nd** [comment]
Hi @barbibulle I've tried removing the trailing 0x0a, along with a few other ideas.  I'm still not finding a way to get this working.  Any help you can provide would be greatly appreciated!

**Comment by barbibulle** [comment]
Hi Jed,

if you can share the files you've used for testing, along with the exact
command-line parameters you have used, I can take a look and see if I can
reproduce the issue.

**Comment by jed2nd** [comment]
@barbibulle big buck bunny is the mp4 I'm testing against:
http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4
Command line args are listed above.
Thanks for taking a look!

**Comment by jed2nd** [comment]
@barbibulle I have finally gotten video to display.  By copying the key.bin file that is created using the mp4hls tool into the video and audio folders of the output from mp4dash, it seems the key is now correctly formatted.  It's still unclear to me what the differences are between the file I was using versus this one, but I am now able to confirm the tool works as intended.  Perhaps it would be useful to add the same `--output-encryption-key` argument to mp4dash that exists in mp4hls.

**Comment by gokerwin** [comment]
@barbibulle  Hi, As far as I know, HLS has supported hevc and fmp4 since 2017 WWDC. In the FairPlay Streaming Overview from FairPlay Streaming Server SDK (4.0.1), I also know that fairplay only support h264. However, the last update time of this document is 2016-06-24. 

So, I want to consulting that if fairplay also has support hevc ? 

Sincerely looking forward to receiving your reply. Thank you.

**Comment by barbibulle** [comment]
@gokerwin Fairplay with HEVC is supported and has been tested on macOS and iOS.

**Comment by gokerwin** [comment]
@barbibulle Thank you very much. But I can find any reference material, and I have test on my Macbook on MacOS High Sierra 10.13.2,  Safair 11.0.2 that the fairplay with hevc don't work. If it has system version requirements or any reference material ?

**Comment by AdithyanBitmovin** [comment]
@gokerwin Same problem. Fairplay/ HEVC will not work on Safari.
Although the same stream works on iOS and Apple TV. Did you solve your problem?

**Comment by barbibulle** [comment]
Fairplay/HEVC has been tested and working on iOS, AppleTV and macOS/Safari.
Do you have an example stream that we can use to try and replicate the problem you are having?

**Comment by AdithyanBitmovin** [comment]
@barbibulle the example stream is here : http://bitmovin-api-europe-west1-ci-output.commondatastorage.googleapis.com/encoding_test/CinepolisHevcFmp4FairplaySintel4k-Fri_Mar_23_13_13_14_CET_2018/stream.m3u8

- This stream works on iOS and Apple TV. I checked this.
- Will not work on Safari.

Thanks for checking.

**Comment by SayoniDuttaRoy** [comment]
**I created a fairplay encrypted hvc stream using shaka packager. However it does not play although unencrypted hevc created by the same process plays.**
**On specifying the hevc codec in the master playlist, I get the error :** 
"INTERNAL_ERROR" = "Error Domain=AVFoundationErrorDomain Code=-11867 \"See -[AVPlayerItem errorLog] for 1 events\" UserInfo={NSLocalizedDescription=Playback Stopped, NSUnderlyingError=0x1c865ec60 {Error Domain=CoreMediaErrorDomain Code=-12880 \"Can not proceed after removing variants\" UserInfo={NSDescription=Can not proceed after removing variants}}, NSDebugDescription=See -[AVPlayerItem errorLog] for 1 events, NSLocalizedFailureReason=Could not download required resources.}"

**On removing the hevc codec from the master playlist, I get the error:**
"INTERNAL_ERROR" = "Error Domain=AVFoundationErrorDomain Code=-11833 \"Cannot Decode\" UserInfo={NSUnderlyingError=0x1c0c401e0 {Error Domain=NSOSStatusErrorDomain Code=-12906 \"(null)\"}, NSLocalizedFailureReason=The decoder required for this media cannot be found., AVErrorMediaTypeKey=vide, NSLocalizedDescription=Cannot Decode}";

Please help.

**Comment by barbibulle** [comment]
I'm suspecting there's something off in the license data returned by your FairPlay key server (maybe some flag that allows/disallows playback on desktop machines?).
I have verified that encrypted content (both h.264 and hevc) can play just fine in Safari.
Here's a link to a page that has 4 examples: h264 and hevc, both in cleartext and encrypted.
The encrypted content is the same as what you'd use if you used FairPlay as a key delivery DRM, but in this case the key is just delivered straight from the server without DRM. (but the encrypted format is the same).
For reference, the encrypted content was generated with this command:
`mp4dash --hls --encryption-key=000102030405060708090a0b0c0d0e0f:00112233445566778899aabbccddeeff --encryption-cenc-scheme=cbcs -o encrypted_h265 hevc_video.mp4`

You can access the test streams here: http://www.bok.net/tmp/safari_hls_test/player.html
