### ISSUE TITLE
fmp4 encryption with HLS

### ISSUE THREAD

**Issue by ajagannath** [axiomatic-systems/Bento4#172]
We are trying to get encrypted fmp4 with HLS work with Bento4.
I uncovered a bug while doing this. However I was able to get some outputs but not able to correctly play them on safari.

I am using pre-built bento : http://zebulon.bok.net/Bento4/binaries/Bento4-SDK-1-5-0-615.universal-apple-macosx.zip
Source Media: http://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_5mb.mp4

Fragment:
```
$ mp4fragment --fragment-duration 10000 --debug --force-i-frame-sync all --index SampleVideo_720x480_5mb.mp4 fragmented.mp4
Using track ID 1 as anchor
==== Track ID 1 - dts=0, target=128000, start=0, end=210/774
---- Track ID 2 - dts=0, target=403200, start=0, end=394/1453
==== Track ID 1 - dts=107520, target=256000, start=210, end=543/774
---- Track ID 2 - dts=403456, target=1042560, start=394, end=1018/1453
==== Track ID 1 - dts=278016, target=384000, start=543, end=774/774
[Track ID 1 has reached the end]
---- Track ID 2 - dts=1042432, target=1486080, start=1018, end=1451/1453
+++ New anchor: Track ID 2
==== Track ID 2 - dts=1485824, target=1920000, start=1451, end=1453/1453
[Track ID 2 has reached the end]
```

Fragmented successfully but gets error when creating playlist:
```
$ mp4dash  --hls  --encryption-cenc-scheme cbcs --encryption-key 11111111111111111111111111111111:11111111111111111111111111111111 --profiles=on-demand --no-split fragmented.mp4 
Parsing media file 1: fragmented.mp4
Extracting track 2 from fragmented.mp4
Extracting track 1 from fragmented.mp4
Encrypting track IDs [2] in tmp9wFaSe = Extracted[track 2 from fragmented.mp4]
Encrypting track IDs [1] in tmpSOq6hf = Extracted[track 1 from fragmented.mp4]
Parsing media file 1: tmpPP39ON = Encrypted[tmp9wFaSe = Extracted[track 2 from fragmented.mp4]]
Parsing media file 2: tmpT5eLU8 = Encrypted[tmpSOq6hf = Extracted[track 1 from fragmented.mp4]]
Processing and Copying media file tmpT5eLU8 = Encrypted[tmpSOq6hf = Extracted[track 1 from fragmented.mp4]]
Processing and Copying media file tmpPP39ON = Encrypted[tmp9wFaSe = Extracted[track 2 from fragmented.mp4]]
ERROR: 'NoneType' object has no attribute '__getitem__'
```

However, when we try video only, we can successfully create output:
```
$ mp4fragment --fragment-duration 10000 --debug --force-i-frame-sync all --index --track video  SampleVideo_720x480_5mb.mp4 fragmented_video_only.mp4
Using track ID 1 as anchor
==== Track ID 1 - dts=0, target=128000, start=0, end=210/774
==== Track ID 1 - dts=107520, target=256000, start=210, end=543/774
==== Track ID 1 - dts=278016, target=384000, start=543, end=774/774
```

```
$ mp4dash  --hls  --encryption-cenc-scheme cbcs --encryption-key 11111111111111111111111111111111:11111111111111111111111111111111 --profiles=on-demand --no-split fragmented_video_only.mp4 
Parsing media file 1: fragmented_video_only.mp4
Extracting track 1 from fragmented_video_only.mp4
Encrypting track IDs [1] in tmphSj31b = Extracted[track 1 from fragmented_video_only.mp4]
Parsing media file 1: tmpcG3JvU = Encrypted[tmphSj31b = Extracted[track 1 from fragmented_video_only.mp4]]
Processing and Copying media file tmpcG3JvU = Encrypted[tmphSj31b = Extracted[track 1 from fragmented_video_only.mp4]]
```

Now the created output has
`#EXT-X-VERSION:6` I think it should be 7 ( this is minor) 

`key.bin` is created with `11111111111111111111111111111111` as used in `--encryption-key `, in binary
Here is the complete output: 
[Output.zip](https://github.com/axiomatic-systems/Bento4/files/1212981/Output.zip)

And when I play this content, Its not exactly coming out right
<img width="662" alt="decoded_video" src="https://user-images.githubusercontent.com/17299167/29145456-12786948-7d12-11e7-8b1b-643ba5562bd3.png">

Anything we are missing in this? 

Thanks
Abhijith

**Comment by samlee64** [comment]
I'm also running into this issue.  
`mp4fragment --fragment-duration 2000 --index small.mp4 fsmall.mp4`
`mp4dash --hls --encryption-cenc-scheme cbcs --encryption-key 11111111111111111111111111111111:11111111111111111111111111111111 fsmall.mp4

**Comment by samlee64** [comment]
I'm also seeing this issue when as I try to encrypt a fMP4 thats split into separate files. 

`cmd="mp4encrypt --method MPEG-CBCS --key ${N}:${KEY}:${IV} --property ${N}:KID:${KID} ./src/2s_init.mp4 ./encrypted/cenc-init.mp4"
echo $cmd
eval $cmd

for i in `seq 0 9`;
do
  cmd="mp4encrypt --method MPEG-CBCS --key ${N}:${KEY}:${IV} --property ${N}:KID:${KID} --fragments-info ./src/2s_init.mp4 ./src/2s_${i}.mp4 ./encrypted/cenc-${i}.mp4"
  echo $cmd
  eval $cmd
done
`

**Comment by zshenker** [comment]
The `ERROR: 'NoneType' object has no attribute '__getitem__'` error appears to be from this line:
https://github.com/axiomatic-systems/Bento4/blob/master/Source/Python/utils/mp4-dash.py#L1443

`options.track_key_infos` is getting reset when audio/video tracks are being pulled from different files. I don't get that error any more if I wrap that line in `if not hasattr(options, 'track_key_infos'):`

I am also getting the same issues with playback of these streams in Safari. 

@barbibulle Would you expect CBCS encrypted HLS streams to playback ok in Safari ?

**Comment by barbibulle** [comment]
Support for HLS with fMP4 and CBCS encryption isn't fully compatible with
iOS and macOS clients yet (those clients ignore the explicit encryption
layout metadata found in saio/saiz boxes, and instead rely purely on the
video slice header size to determine the portions of the sample that is
encrypted). The iOS and macOS clients aren't wrong (it is legal to work
that way according to the spec), but it makes it harder for the packager,
which is responsible, in that mode, to precisely compute the video slice
headers.
This issue only applies to the video streams, and should not affect audio
stream.
We are working on a fix for this and should be able to share the fix
shortly.

**Comment by ajagannath** [comment]
Thank you @barbibulle. We are able to verify that audio-only encryption has no problem playing in safari.
We look forward for the fix.

**Comment by ajagannath** [comment]
@barbibulle Do you have any ETA on this? 
If this is not a priority, can you point us to a place where we can start looking in code and help in fixing the issue? 

Thanks
Abhijith

**Comment by barbibulle** [comment]
I've made some progress on this over the week-end, but not 100% complete. I'm hoping to have this ready to test before next Monday.

**Comment by sinkers** [comment]
@barbibulle how did you go with this? Happy to assist with testing.

**Comment by barbibulle** [comment]
I have pushed a commit to the master branch and uploaded new pre-compiled binaries. 
This should work now. Let me know if you have any problem with it.

**Comment by bcasinclair** [comment]
@barbibulle should this work for HEVC? I as getting some errors, will replicate and post

**Comment by barbibulle** [comment]
Unfortunately HEVC is still not 100% complete. The authors of the CBCS sample-oriented encryption mode (i.e Apple) have really chosen a very poor design here, as the encrypter needs deep knowledge of the internals of the codecs, so a lot of specific code must be added for each video format (as opposed to the other encryption modes where things are mostly codec-agnostic).
I'm hoping to be able to push an update very shortly that completes CBCS/HEVC support.

**Comment by bcasinclair** [comment]
Yeah it definitely looks non-trivial. So my reading is need to be able to parse the full slice header to work out the encrypted range, is that correct?

**Comment by barbibulle** [comment]
Yes, that's correct. I have started attacking this (there's already a parser for the slice header, but it currently stops when it has enough to know about frame ordering, which is needed for muxing, and since the library isn't implementing a codec, it doesn't need to parse more than is required)

**Comment by barbibulle** [comment]
This is now supported using the mp4dash tool.
