### ISSUE TITLE
MediaSource instance has no attribute 'track_key_infos'

### ISSUE THREAD

**Issue by gtebbutt** [axiomatic-systems/Bento4#178]
Running `mp4-dash.py --force --hls --no-split --profiles=on-demand foo.mp4` on r616 gives the above error (running on OSX 10.12.6). 

For my purposes, adding `self.track_key_infos = {}` directly to the `__init__` of `MediaSource` in `mp4utils.py` seems to work fine to fix it, but I'm new to the project so I won't claim to have looked at any implications of doing so.

**Comment by barbibulle** [comment]
Sorry about that. I just pushed a fix and updated the pre-compiled binaries.

**Comment by gtebbutt** [comment]
Very much appreciated, thank you!
