### ISSUE TITLE
mp4fragment creating extra small fragment

### ISSUE THREAD

**Issue by bcasinclair** [axiomatic-systems/Bento4#19]
I have been finding that mp4fragment has been creating an extra audio fragment with only 3 samples even though the previous fragment has less than the maximum number of samples for the specified duration.

Using this sample file: http://asbctest.s3.amazonaws.com/debug/muxed.mp4

Result looks like this
mp4fragment --verbosity 3 muxed.mp4 cokead_frag.m4f
found regular I-frame interval: 200 frames (at 25.000 frames per second)
fragment: track ID 1  200 samples
fragment: track ID 2  345 samples
fragment: track ID 1  200 samples
fragment: track ID 2  344 samples
fragment: track ID 1  200 samples
fragment: track ID 2  345 samples
fragment: track ID 1  150 samples
fragment: track ID 2  258 samples
fragment: track ID 2  3 samples

As the video is 25fps 200 samples per fragment is exactly on 8 seconds as per the encode and the audio is 44.1Khz so should be 43 packets of 1024 samples second == 344.5 samples.

So are the last 2 fragments for track 2 258 and 3? Shouldn't it be one last fragment of 261 samples? Even if I adjust the fragment duration to longer than the video I still get one last audio fragment of 3 samples.

The result is that when it runs through mp4split is that it is generating one more audio segment than video segment and this is causing some players to error.

**Comment by bcasinclair** [comment]
If it has any relevance if I only fragment the audio track on it's own it doesn't have this issue, e.g.

mp4fragment --debug --index --track 2 muxed.mp4 tst.m4f
found regular I-frame interval: 200 frames (at 25.000 frames per second)
Using track ID 2 as anchor
==== Track ID 2 - dts=0, target=352800, start=0, end=345/1295
==== Track ID 2 - dts=353280, target=705600, start=345, end=689/1295
==== Track ID 2 - dts=705536, target=1058400, start=689, end=1034/1295
==== Track ID 2 - dts=1058816, target=1411200, start=1034, end=1295/1295
[has reached the end]

And with both tracks, which shows the new anchor being created which appears to be the issue:

mp4fragment --debug --index muxed.mp4 tst.m4f
found regular I-frame interval: 200 frames (at 25.000 frames per second)
Using track ID 1 as anchor
==== Track ID 1 - dts=0, target=200, start=0, end=200/750
---- Track ID 2 - dts=0, target=352800, start=0, end=345/1295
==== Track ID 1 - dts=200, target=400, start=200, end=400/750
---- Track ID 2 - dts=353280, target=705600, start=345, end=689/1295
==== Track ID 1 - dts=400, target=600, start=400, end=600/750
---- Track ID 2 - dts=705536, target=1058400, start=689, end=1034/1295
==== Track ID 1 - dts=600, target=800, start=600, end=750/750
[has reached the end]
---- Track ID 2 - dts=1058816, target=1323000, start=1034, end=1292/1295
+++ New anchor: Track ID 2
==== Track ID 2 - dts=1323008, target=1764000, start=1292, end=1295/1295
[has reached the end]

**Comment by bcasinclair** [comment]
It it helps I can see the issue is that the target_dts here is getting set of the video track time which is slightly shorter than the total audio track time and hence resulting in the extra fragment.

https://github.com/axiomatic-systems/Bento4/blob/master/Source/C%2B%2B/Apps/Mp4Fragment/Mp4Fragment.cpp#L407-L409

**Comment by barbibulle** [comment]
The reason you are getting an 'extra' audio segment here is that the audio track is slightly longer than the video. The 'extra' audio segment contains the part of the audio track that has no matching video.
The fragmenter creates a sequence of segments that match as closely as possible. If there's any leftover (no matching partner), those segments will have no siblings. The comment you see about selecting a 'new anchor' is a result of that: the video has reached the end, so the audio track (ID 2) becomes the 'new anchor', and a sibling-less audio segment is output.
