### ISSUE TITLE
Hard coded font path in mp4-dash-encode.py

### ISSUE THREAD

**Issue by klacointe** [axiomatic-systems/Bento4#20]
The option `--text-overlay` fails on Linux..

https://github.com/axiomatic-systems/Bento4/blob/master/Source/Python/utils/mp4-dash-encode.py#L161

**Comment by barbibulle** [comment]
True. This is an "obscure" option that I've only tested on Mac OSX. I'll add an option to specify the font path, and probably also include a default font with the distribution.

**Comment by barbibulle** [comment]
A new option, --text-overlay-font, has been added for this.
