### ISSUE TITLE
Encryption-key  option required on linux build but not on windows

### ISSUE THREAD

**Issue by sdaub** [axiomatic-systems/Bento4#200]
I have been working with Bento on a windows development machine and have code working that I am using to call mp4hls.py.  In order to test things out, I am not doing any encryption on this content.  

I am now working to move this code to run on a linux docker container.  I have my (dotnet core) code, and the linux build (Bento4-SDK-1-5-0-617.x86_64-unknown-linux.zip) and installed it in the container.  When I call mp4hls I get an error "no encryption key was specified".  If I provide the encryption-key option with a value then mp4hls succeeds, albeit with encrypted output.  

It seems like there is a bug in the linux build which causes it to now be able to package content without having to encrypt it. 

Is there something different I need to do on linux?

**Comment by sdaub** [comment]
More detail on the error on linux:

```
ERROR: no encryption key specified
    Traceback (most recent call last):
    File "/app/bento/bin/../utils/mp4-hls.py", line 648, in <module>
    main()
    File "/app/bento/bin/../utils/mp4-hls.py", line 638, in main OutputHls(options, media_sources)
  File "/app/bento/bin/../utils/mp4-hls.py", line 309, in OutputHls
    ProcessSource(options, media_info, out_dir)
  File "/app/bento/bin/../utils/mp4-hls.py", line 236, in ProcessSource
    **kwargs)
  File "/app/bento/utils/mp4utils.py", line 303, in Mp42Hls
    return Bento4Command(options, 'mp42hls', input_filename, *args, **kwargs)
  File "/app/bento/utils/mp4utils.py", line 282, in Bento4Command
    raise Exception(message)
Exception: binary tool failed with error 1 - ['/app/bento/utils/../bin/mp42hls', '--hls-version', '4', '--iframe-index-filename', '/video/work/mfTest_package/media/fps/media-1/iframes.m3u8', '--show-info', '--encryption-mode', 'AES-128', '--output-single-file', '--segment-url-template', 'media.ts', '--segment-filename-template', '/video/work/mfTest_package/media/fps/media-1/media.ts', '--segment-duration', '6', '--index-filename', '/video/work/mfTest_package/media/fps/media-1/stream.m3u8', '--encryption-key-uri', 'key.bin', '/video/work/mfTest/19dbdab8-14d9-4c30-a4b5-461ecd030ab6_abr460.mp4']
```

**Comment by edent** [comment]
I have the same issue. I solved it by using 1.5.0-615 from http://zebulon.bok.net/Bento4/binaries/

**Comment by barbibulle** [comment]
Sorry about that. 
I have committed a fix for this, and pushed new pre-compiled binary bundles.

**Comment by sdaub** [comment]
Thank you!  Working properly now.
