### ISSUE TITLE
undefined name 'plaintext' in aes.py

### ISSUE THREAD

**Issue by andreyrikunov** [axiomatic-systems/Bento4#203]
See https://github.com/axiomatic-systems/Bento4/blob/ce01e533ffe4b06668473406ab286a9afc5fbe76/Source/Python/utils/aes.py#L297

**Comment by barbibulle** [comment]
Thanks for the bug report. We'll fix that.
How did you run into this bug? (This line should only execute if an invalid input is passed, so I'm curious to know which script ended up calling this function with an invalid value)

**Comment by andreyrikunov** [comment]
that's pyflakes finding
