### ISSUE TITLE
mp4-hls -> hls master playlist error with samsung internet browser.  issue and fix

### ISSUE THREAD

**Issue by Braisor** [axiomatic-systems/Bento4#207]
- With latest version of samsung internet explorer (android), MediaPlayer error:
"java.io.FileNotFoundException: No content provider"

#EXTM3U**CR**
**CRLF**
#Created with Bento4 mp4-hls.py version 1.1.0r615**CR**
**CRLF**
**CR**
**CRLF**
#Media Playlists**CR**

Removing all blank lines and it work. I thought it was a pb with CRLF but it's ok with same blank lines after # Media Playlist line...  

- Another pb with old version of samsung internet browser (or Edge, don't remember) i have to change this
media_info = {
            'source':      media_source,
            'dir':         'media-'+str(media_index)
        }
to this
media_info = {
            'source':      media_source,
            'dir':         './media-'+str(media_index)
        }

Browsers incompatibility forever

**Comment by barbibulle** [comment]
I think this has been fixed in a recent release. I'm closing this issue. Let me know if the fix doesn't work for you.
