### ISSUE TITLE
Bad conversion mp4hls

### ISSUE THREAD

**Issue by klimentLambevski** [axiomatic-systems/Bento4#208]
I am using mp4hls to convert mp4 video in HLS playlist.
$ mp4hls test.mp4  --> works fine, but the generated video is black screen with audio only, Am i missing something ?

I am using mp4hls.bat on windows

**Comment by barbibulle** [comment]
What player are you using? Can you posts a link to the files you used, and the exact command-line parameters you used so that we can try to replicate your issue?

**Comment by klimentLambevski** [comment]
I used the command `mp4hls test.mp4` with this video 
http://techslides.com/demos/sample-videos/small.mp4

**Comment by barbibulle** [comment]
I have tested this file with `mp4hls`, and the output plays perfectly fine with the quicktime player and ffmpeg. 
Which player have you tried?

**Comment by klimentLambevski** [comment]
I used VLC player and video.js player for web, Same result, i can upload the result files if you want and sent you a link

**Comment by barbibulle** [comment]
Yes, please send a link to the files, as I'm not able to reproduce this issue.

**Comment by klimentLambevski** [comment]
Link to the video https://drive.google.com/open?id=0ByFxf0d-LmuWTnA4aUpobmI5U1U
Link to the output https://drive.google.com/open?id=0ByFxf0d-LmuWcEx3YjNQVFNaeUU

**Comment by barbibulle** [comment]
The video data in the two links above don't match. If I download test.mp4 and use `mp4hls`, I get an output that plays perfectly well. However, if I download the output.zip from the link, I get a directory with files that have the same size as what I've generated from the input, but the video data is completely different. 
I have double-checked this on macOS and Windows.
Could you check that you're indeed looking at the right files?
