### ISSUE TITLE
Bento4 with DRMtoday

### ISSUE THREAD

**Issue by PraveenValaboju** [axiomatic-systems/Bento4#209]
Could you share the command line for bento4 with DRMtoday CEC

**Comment by barbibulle** [comment]
Can you provide more details on what exactly you're trying to achieve? (what type of content, what DRM, etc.)

**Comment by PraveenValaboju** [comment]
we want to package the content with bento4  into multi DRM pption- (Widevine and PlayReady), using DRMtoday  DRMtoday cloud service
Could you please help on this

**Comment by barbibulle** [comment]
Multi-DRM encryption is documented here:
https://www.bento4.com/developers/dash/encryption-and-drm/

I am not familiar with how DRMtoday works, but assuming that is works like a normal cloud-based DRM service, the way it should typically work is that when you encrypt your content with a chosen key and key ID (KID) (as shown in the doc), you also configure your DRM service to issue licenses with the same key and KID.
