### ISSUE TITLE
--output-dir not used in mp4-dash-encode.py

### ISSUE THREAD

**Issue by klacointe** [axiomatic-systems/Bento4#21]
The option `--output-dir` don't change the output path.

**Comment by barbibulle** [comment]
Can you share an example of a command line invocation that shows the problem (I've just verified that invoking mp4-dash.py with the -o foo or --output-dir foo option does indeed create a directory named foo in which the output files are stored).  Maybe you're using other options that make something fail?

**Comment by klacointe** [comment]
This issue is about the mp4-dash-encode.py script, not mp4-dash.py

**Comment by barbibulle** [comment]
This should be fixed now.
