### ISSUE TITLE
Mp4Mux:NULL nal_unit crashes app when parsing from h264 file

### ISSUE THREAD

**Issue by sasmaster** [axiomatic-systems/Bento4#211]
Hi! I am trying to mux h264 file which I am generating using Nvidia Video SDK. Using Mp4Mux tool.
I am getting thrown inside AP4_AvcFrameParser::Feed() method . 
nal_unit retuns NULL from the m_NalParser.Feed() . Also there is no null handling for this case and the app crashes when dereferencing null in 
 return Feed(nal_unit->GetData(), nal_unit->GetDataSize(), access_unit_info, eos);

Thanks.

**Comment by barbibulle** [comment]
Sorry about that. This will be fixed shortly.

**Comment by sasmaster** [comment]
That's OK man, bugs happen) )
 Btw,now when I think about this case, my video stream was shorter than the
audio. Probably that was the reason for null return. I added check for
nal_unit == null with 'false ' return and it finilized encoding fine.

**Comment by barbibulle** [comment]
Should be fixed now.
