### ISSUE TITLE
ISMV file is not decrypted by MP4Decrypt

### ISSUE THREAD

**Issue by xpouyat** [axiomatic-systems/Bento4#213]
Hello,
I am not able to decrypt an encrypted ISMV file. The MP4DECRYPT tool runs fine but the output is still encrypted.

You can reproduce the behavior by encrypting/decrypting a clear ISMV file using the file:

https://mediasvcs6gbv2zdblgmj.blob.core.windows.net/asset-e2047cbb-ccdf-442a-81d5-b5124c7813a6/BigBuckBunny_1272k.ismv?sv=2015-07-08&sr=c&si=ea20aa87-90fb-42da-8e6d-cea3b97375c8&sig=fPKhLnNFoOdz9Z4Xrw2AMWNchIqvIPBI1RM0D1n1KqA%3D&se=2027-09-28T09%3A05%3A00Z

Encrypt it this way:
mp4encrypt --method PIFF-CTR --key 4:7C719DFA88D893D5A60CECFC0F094EB6:random --property 4:KID:a09e825f1b72434e84cb192f69fc715f  C:\video\BigBuckBunny_1272k.ismv C:\video\BigBuckB
unny_1272k-encrypted.ismv

Decrypt the output file this way:
mp4decrypt --key a09e825f1b72434e84cb192f69fc715f:7C719DFA88D893D5A60CECFC0F094EB6 C:\video\BigBuckBunny_1272k-encrypted.ismv -out C:\video\BigBuckBunny_1272k-decrypted.ismv

With MP4Info, we see that BigBuckBunny_1272k-decrypted.ismv is still encrypted....

**Comment by barbibulle** [comment]
Sorry about that. The ` --key <id>:<k>` command line parameter for `mp4decrypt` says that <id> can be a track ID or a KID, but unfortunately support for the KID form is broken, so you need to pass in the track ID instead.
In you example, you're encrypting track ID 4, so you would need to use `--key 4:7C719DFA88D893D5A60CECFC0F094EB6`.

Also, please note that the `mp4encrypt` example you're using here doesn't set the KID for the tracks. To set the KID, you need to pass `--property <track_id>:KID:<KID>`, so in your case here, where you use track ID 4 and KID a09e825f1b72434e84cb192f69fc715f, you would have:
`--property 4:KID:a09e825f1b72434e84cb192f69fc715f`.

**Comment by xpouyat** [comment]
Thanks. But I used `--property 4:KID:a09e825f1b72434e84cb192f69fc715f` when encrypting... See my first message.
I tried using `--key 4:7C719DFA88D893D5A60CECFC0F094EB6` when decrypting the ISMV file, and get an error: 
ERROR: failed to process the file (-10)

**Comment by barbibulle** [comment]
Sorry, my bad, I had read your post too quickly. The command line was correct.
I looked into this, and realized that support for PIFF-CTR was broken a few releases ago, and wasn't caught by automated testing (and since most people these days tend to use the MPEG-CENC mode, which in most cases will be backward-compatible with PIFF-CTR, I had not received any complaints until now).
I have fixed the issue and pushed a new release and set of pre-compiled binary packages. 
Let me know if this works for you.

**Comment by xpouyat** [comment]
Thanks! It works now. Thank you for your quick help and fix.

**Comment by sahil129** [comment]
How to get the decryption key from this plz help me


EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED = urn:uuid
ce87e8a2-372b-76df-449e-213ef0e1c961 = KID

**Comment by DarbyCrash** [comment]
Where is that fix?
