### ISSUE TITLE
Preserving metadata with mp4fragment

### ISSUE THREAD

**Issue by jviney** [axiomatic-systems/Bento4#216]
Hi,

I'm using mp4fragment and need to preserve the metadata from the original unfragmented mp4. It looks like this information is contained in the moov/udta atom.

Extracting this atom with mp4extract, then inserting it into the fragmented mp4 appears to work correctly. Is there anything wrong with this approach or is there a better way to do it?

```
mp4fragment input.mp4 fragmented.mp4
mp4extract moov/udta input.mp4 moov-udta.atom
mp4edit --insert moov:moov-udta.atom fragmented.mp4 fragment-udta.mp4
```

Thanks in advance.

**Comment by barbibulle** [comment]
This approach will work. But I should really add an option to the mp4fragment tool to tell it to keep the original `udta` atom in the output (I don't see a good reason not to). I'll try to add this in the next release.
