### ISSUE TITLE
Unable to Decrypt this Video

### ISSUE THREAD

**Issue by wakhgando** [axiomatic-systems/Bento4#220]
[https://a56avoddashs3ww-a.akamaihd.net/d/2$o-57kEyyDe_VLCwMfFll1rx8qSA~/ondemand/sin-dub-iad/7925/3405/64bd/4f29-ba34-885b2260d343/ba945d08-7843-45d2-90ea-d347ba493031_video_1.mp4
](url)

**Comment by barbibulle** [comment]
How did you try decrypting the file? Do you have the decryption key(s)?

**Comment by wakhgando** [comment]
i have this MPD file and  trying KID for the decrypyion.
https://s3.ll.dash.row.aiv-cdn.net/d/2$o-57kEyyDe_VLCwMfFll1rx8qSA~/sin/7925/3405/64bd/4f29-ba34-885b2260d343/ba945d08-7843-45d2-90ea-d347ba493031_corrected.mpd
[](url)

**Comment by barbibulle** [comment]
The KID is just the key identifier, not the key itself. Without the key, you can't decrypt anything.

**Comment by wakhgando** [comment]
i have downloaded this movie with separate audio and separate video.
audio is OK but video is Encrypted.i searched in developer tools and applied all keys so what will the decryption key.

[https://www.primevideo.com/detail/0LL7X538M4VNR0YB0WIMUR46UI/](url)

**Comment by d3ibis** [comment]
I have same issue BUT I have the key...
Separate audio/video files both encrypted

key is: 43D1465BE137D6ED0100000000000000

command: mp4decrypt --key 1:43D1465BE137D6ED0100000000000000 --key 2:43D1465BE137D6ED0100000000000000 encrypted.mp4 decrypted.mp4

everything is fine and no errors but still file is encrypted (in media info shows also encrypted)

**Comment by barbibulle** [comment]
Is it possible for you to share the video file so that we can try to
replicate the issue on our side?
