### ISSUE TITLE
Playready encryption parameter question

### ISSUE THREAD

**Issue by billyrt** [axiomatic-systems/Bento4#221]
Hi, 

I just start to learn how to use Bento4 to fragment/dash mp4.

Now I am confusing about the parameter for playready encryption.

According to the Bento4 document, I should use --encryption-key=KID:EncryptionKey --plready-header=LA_URL:License Acquisition URL source.mp4 -o output folder.

I am using Azure document sample to get the information through AMS .Net SDK.

https://docs.microsoft.com/en-us/azure/media-services/media-services-deliver-keys-and-licenses
http://mingfeiy.com/integrate-azure-playready-license-service-encryptorstreaming-server

From the output, I can see following information:

Created key nb:kid:UUID:60ab7db0-3301-4592-9ca7-9382aeee9ccb with key value 5ZSO
yMbNvfML3jJYtudHUg==
PlayReady License Key delivery URL: https://AMS_LAURL
Widevine License Key delivery URL: https://AMS_LAURL
Added authorization policy: nb:ckpid:UUID:444100d9-b21c-4e2f-a720-7bc46731c72d

What is the KID and Encryption key I from here??

Hope someone can help me to clarify.

Thank you.

**Comment by mchelnokov** [comment]
Hi,
Looks like your KID is 60ab7db0330145929ca79382aeee9ccb (I hope, Azure doesn't use little-endian GUID byte order here) and your encryption key is e5948ec8c6cdbdf30bde3258b6e74752 (you should just convert it from Base64 to hex, like "echo "5ZSOyMbNvfML3jJYtudHUg==" | base64 -d | xxd -p").

**Comment by billyrt** [comment]
Hi, 

Thank you for the hint! I made it work for 1 video, and seems encrypted fine and Playready player can play it correct, thank you!

Still trying to do the other video with another KID/ID but seems not doing well, still trying to make sure it works solid...lol

**Comment by billyrt** [comment]
It turns out it's other videos I was using need to encode again even using MediaInfo it shows same H.264/ML/4.0, once using ffmpeg to encode again, it works.

Thank you.
