### ISSUE TITLE
correct command for Widevine challenge

### ISSUE THREAD

**Issue by techbliss** [axiomatic-systems/Bento4#223]
Hello 
Im trying to figure out the correct way to decrypt a  mp4 with a Widewine challenge key and track KID
I tried 
```
mp4decrypt "file_encrypted.mp4" Widewinekey_in_hex:KID_id_for track
```
But dont seem to have any effect, and i dont get any errors regarding key either.

```
mp4decrypt "file_encrypted.mp4" "out_decrypted.mp4"--key Widewinekey_in_hex:KID_id_for track
```
dont have any effect also.

In the tut its descibed as 

```
mp4decrypt "file_encrypted.mp4" "out_decrypted.mp4"--key 1:KID_id_for track
````
any suggestions

**Comment by barbibulle** [comment]
The <KID:key> syntax for passing keys to mp4decrypt is actually broken, so you'll need to use the <track_id:key> form.
Example, if you have a file with two tracks, id=1 and id=2, both encrypted with key 00112233445566778899aabbcddeeff, you'd decrypt it this way:

mp4decrypt --key 1:00112233445566778899aabbcddeeff --key 2:00112233445566778899aabbcddeeff encrypted.mp4 decrypted.mp4

**Comment by techbliss** [comment]
Will it automatically find the KID when just using one AES key then.

**Comment by barbibulle** [comment]
Yes, the KID is part of the file itself, so you don't need to specify it when decrypting.

**Comment by Nemesis7** [comment]
@barbibulle This seems to be fixed on Windows, but on Mac this workaround is still needed. When will this be fixed?

**Comment by barbibulle** [comment]
@Nemesis7 I'm not sure how you would find this fixed on Windows. The code is the same for all platforms, and I don't believe I've made any change to this recently.
I haven't prioritized this much, since the workaround is pretty easy to use (i.e specify the track ID, not the KID), but if you have a blocking use case, let me know, I can always try and prioritize fixing this.

**Comment by Nemesis7** [comment]
> @Nemesis7 I'm not sure how you would find this fixed on Windows. The code is the same for all platforms, and I don't believe I've made any change to this recently.
> I haven't prioritized this much, since the workaround is pretty easy to use (i.e specify the track ID, not the KID), but if you have a blocking use case, let me know, I can always try and prioritize fixing this.

Thanks mate, I would appreciate this being fixed. I know it should not be possible, but somehow using the KID on Windows decrypts the video track, but on a Mac it doesn't unless I use the track ID. Is there no way that the code is interpreted differently when building mp4decrypt for MacOSX vs. Windows?

**Comment by Nemesis7** [comment]
@barbibulle Do you need more input from me regarding this issue?

**Comment by SArun61** [comment]
Is it possible to get mp4decrypt.exe application binaries for windows?

**Comment by SArun61** [comment]
I am having an mpd link and widewine license url. Is it possible to download the encrypted content and decrypt locally?

**Comment by FloridaStream** [comment]
this does not decrypt the widevine, this decrypt with the kid: key, if you have the key used in your widevine license distribution, you will be able to decrypt, there is no key in the manifest, just the kid. @SArun61
