### ISSUE TITLE
HLS encryption options from mp4dash app

### ISSUE THREAD

**Issue by pscplayco** [axiomatic-systems/Bento4#237]
Hi, I would like to Fairplay-encrypt some content using fmp4 source files, but I don't find the way to include the following options that I need:

--encryption-args="--encryption-iv-mode=fps --encryption_key_format=com.apple.streamingkeydelivery --encryption-key-format-versions=1

....within the mp4dash command. If there any way? Thank you in advance

**Comment by pscplayco** [comment]
I've tried mp4dash with just the option "--encryption-cenc-scheme=cbcs" but then the playback is not working for me. I'm pretty sure the other parameters are needed for our Fairplay implementation...

**Comment by pscplayco** [comment]
Anyone could help us understanding how to FAIRPLAY-encrypt an HLS packaging using fragmentedMP4 format? That's what we are looking for..... Thanks you

**Comment by barbibulle** [comment]
For Fairplay support, you need to use the option `--fairplay-key-uri` to pass the URI needed by Fairplay for key delivery (ex: skd://key1234).

**Comment by pscplayco** [comment]
Hey, thank you very much for the hint. Tested and working now
