### ISSUE TITLE
mp4-dash.py - write video before audio adaptation sets (request)

### ISSUE THREAD

**Issue by richardbushell** [axiomatic-systems/Bento4#24]
Hi
Is it possible to add a flag option in mp4-dash.py to write the Video adaptation set information into the MPD file first, and then the Audio adaptation set second.
Currently it writes the audio set first, and there's no way to switch the order if that's the preference.
Thanks.
Richard

**Comment by barbibulle** [comment]
In software, everything' possible ;-)
But can you explain why you need the elements in a specific order? The DASH XML schema doesn't require the adaptation sets to appear in any particular order, so this would make no difference to any player.

**Comment by richardbushell** [comment]
Yes, I appreciate it makes no difference. All the other tools, and our own previous working with DASH lead with video before audio. It seems across the industry that video leads in almost all scenarios. Every time we view an MPD file we automatically think video before audio. It's just our arbitrary preference...
