### ISSUE TITLE
First segment size contains ftyp + moov + moof + mdat. Ok?

### ISSUE THREAD

**Issue by qchroman** [axiomatic-systems/Bento4#241]
Hello,

I've been digging around in the code to find out how the bandwidth was calculated and came across this code

```      
for atom in self.tree:
    segment_size += atom['size']
```

Inside the mp4utils.py. After printing out the names of the atom and its size I found out that the first fragment size contains not only moof + mdat boxes, but also the size of the ftyp and moov box. Was it done intentionally?

Thank you!

**Comment by barbibulle** [comment]
Thanks for pointing this out. This will be fixed in the next release.
