### ISSUE TITLE
write faststart

### ISSUE THREAD

**Issue by svnpenn** [axiomatic-systems/Bento4#249]
Bento4 can read faststart with "mp4info", but it seems to have no way to write - these other programs can do it

~~~
ffmpeg -i infile.m4a -c copy -movflags faststart outfile.m4a
~~~

~~~
mp4box -ipod infile.m4a
~~~

**Comment by svnpenn** [comment]
https://github.com/axiomatic-systems/Bento4/issues/105

**Comment by barbibulle** [comment]
The Bento4 tools always output 'faststart' files by default. So one way to do what you need here is to perform a 'null edit' on a file.
For example, `mp4edit input.mp4 output.mp4` should result in an output.mp4 file that's in 'faststart' mode.

**Comment by svnpenn** [comment]
@barbibulle thanks
