### ISSUE TITLE
mp4fragment command produces wrong tfdt on Linux, correct on Windows

### ISSUE THREAD

**Issue by sandersaares** [axiomatic-systems/Bento4#250]
Command: `mp4fragment --tfdt-start 1519350239.52 --fragment-duration 999999999 y.mp4 z.mp4`

Input file: [y.zip](https://github.com/axiomatic-systems/Bento4/files/1750757/y.zip)

App version: 1.5.1-622 from https://www.bento4.com/downloads/

Expected result:

```
[tfdt] size=12+8, version=1
      base media decode time = 136741521556800
```

At 90000 timescale that is 1519350239.52 seconds.

Actual result:

When executing mp4fragment on Windows, actual result matches expected result.

When executing mp4fragment on Linux (Docker container from `ubuntu:latest` image):

```
[tfdt] size=12+8, version=1
      base media decode time = 136741524480000
```

At 90000 timescale that is 1519350272 seconds which is 32.48 seconds too large a value.

With smaller values in input, the tfdt in the output appears to be correct. The idea here is to use 1970 as the zero point, hence the large numbers.

**Comment by barbibulle** [comment]
Yes, indeed, the options parser was using strtof() instead of strtod(), thus losing some precision.
This is now fixed on the master branch.
