### ISSUE TITLE
How to set(change) tfdt field?

### ISSUE THREAD

**Issue by jaykim305** [axiomatic-systems/Bento4#251]
Hi, I'm currently working on my research involving DASH.
Simply I would like to make video(fragmented mp4) start at the specific time just like any m4s media segment from Dash.

For example, if a segment is for timestamp 4 sec, I would like to make similar fmp4 to that segment which starts from 4 sec and no video before 4 sec, so that I could replace the segment.

My question is

1) If I want the fragmented mp4 video [moof mdat] to start at specific time, is 
'base media decode time' (in moof/traf/tfdt path) the correct field that I have to change?

2) If 1) is correct, is there any way or supported tool that I could set or change [tfdt] field of the mp4 ?
    - I tried `mp4edit --replace` to replace tfdt from other video segment, but it seems that mp4edit replace is limited tool and doesn't support what I need.
   - It prints error like
`ERROR: atom 'moof/traf/tfdt' not found`

**Comment by gimansour** [comment]
@jaykim305 , can you please let me know how you managed to get around this?

**Comment by jaykim305** [comment]
What I did was just read the video atom file in binary format. In fragmented video atoms, there are several header fields. Each field has its name, size and data.
You can read the file in binary format and using the size of each field as offsets, you can easily read and write or modify the data of any field.
I did simply with few lines of python code.
In addition, if you change the 'base media decode time', you can make the video play at the specific time you want.

**Comment by morpig** [comment]
bumping this issue. it's an old issue, but do you still have any code examples I can look at @jaykim305?

i'm having issues where video track & audio track have different tfdt values (eventhough same segment number, a/v synced), and when input to ffmpeg, it doesn't like different values, which leads to buffers & discontinuity.
