### ISSUE TITLE
"No JSON object could be decoded"

### ISSUE THREAD

**Issue by Muqito** [axiomatic-systems/Bento4#27]
Hello!

I got this error:

"No JSON object could be decoded"

when I ran this:

C:\Python27\python.exe bento/utils/mp4-dash-encode.py -b 5 fixed.mp4

[Running windows 7, x64, with python 2.7]

And I have checked the mp4 file for errors with ffprobe and I can verify that it's complete!

Any idea how I can fix this?

Any idea what I can do? Or is this no longer supported?

**Comment by barbibulle** [comment]
Can you re-run the same with the ‘-d’ and ‘-v’ options (verbose and debug)?

-- Gilles


On September 28, 2015 at 11:42:23 AM, Christoffer Lans (notifications@github.com) wrote:

Hello!

I got this error:

"No JSON object could be decoded"

when I ran this:

C:\Python27\python.exe bento/utils/mp4-dash-encode.py -b 5 fixed.mp4

[Running windows 7, x64, with python 2.7]

And I have checked the mp4 file for errors with ffprobe and I can verify that it's complete!

Any idea how I can fix this?

Any idea what I can do? Or is this no longer supported?

**Comment by Muqito** [comment]
Sure, here it is:

http://pastebin.com/AJAn3h4R

**Comment by barbibulle** [comment]
Hmm, that’s puzzling.
Looks like ffprobe isn’t producing valid JSON.
Can you try running the ffprobe command by itself to see what it outputs?

 ffprobe -of json -show_format -show_streams "fixed.mp4"

-- Gilles


On September 28, 2015 at 1:37:11 PM, Christoffer Lans (notifications@github.com) wrote:

Sure, here it is:

http://pastebin.com/AJAn3h4R

**Comment by Muqito** [comment]
Yeah sorry, I updated the post just before your comment. you can find it in the pastebin :)

**Comment by Muqito** [comment]
Actually it has some metadata at the beginning of the json!

And that of course is troubling:

http://pastebin.com/tnF6QKBy

**Comment by barbibulle** [comment]
It looks like on Windows, ffprobe does print its non-JSON logs to stderr, but instead to stdout, so it gets mixed in with the JSON. -v quiet or -loglevel quiet would indeed fix this. I'll put this in the main distribution

**Comment by Muqito** [comment]
Still doesn't work! I have tried these tools all day now.

ffmpeg, bento, x264 + m4box no result.

But I think you can close this since my problem is probably not related to your project anyway.
