### ISSUE TITLE
Building for Linux and Mac and Windows from Windows using scons

### ISSUE THREAD

**Issue by qchroman** [axiomatic-systems/Bento4#271]
Hello all,

I apologize for a weird question, but, is there a way to build Bento4 from Windows for other platforms like linux and macos?

Running `scons -u` on my Windows 10 x64 machine throws

> scons: *** Invalid value for option target: x86-microsoft-win32.  Valid values are: ['any-blackberry-qnx', 'arm-android-linux', 'mipsel-sigma-linux', 'sh4-st-linux', 'x86-afl-linux', 'x86-unknown-cygwin', 'x86-unknown-linux', 'x86-unknown-mingw', 'x86_64-unknown-linux']
> File "D:\JOB\projects\multipack-update\keyosmultipack\Build\Boot.scons", line 58, in <module>

Which may mean that scons doesn't have build instructions for my platform. And running something like `scons -u build_config=Release target=x86_64-unknown-linux` gives me

> scons: Entering directory `D:\JOB\projects\multipack-update\keyosmultipack'
> scons: Reading SConscript files ...
> ********** Configuring Build Target = x86_64-unknown-linux / Release ********
> 
> scons: *** A shared library should have exactly one target with the suffix: .dll
> File "D:\JOB\projects\multipack-update\keyosmultipack\Build\Build.scons", line 128, in Executable

I presume I'm missing something, but can't figure out what exactly.

Thank you in advance for your help.

**Comment by barbibulle** [comment]
Are you trying to compile for Windows, or cross-compile on a Windows host for a non-windows target?
To compile for Windows, use the Visual Studio Project, or CMake, as explained in the toplevel README file. Cross-compiling on a Windows host for a non-windows platform is not a supported use case.
