### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by richardbushell** [axiomatic-systems/Bento4#279]
Just wondering if anyone has yet ported the mp4-dash.py Python 2 code to Python 3?
It's 10 years since Python 3 was released, so I assume all the dependencies (if any) have long ago been updated, so I assume it's just a matter of time to make the code changes required? Alas, Python is not a language that I have any real experience in to attempt it myself, so just wondering if this has been done yet, or is set as a milestone for future updates.

This is the only Python 2 code we need to support, so it would be great if this could be updated...

**Comment by barbibulle** [comment]
I do have a branch where I tried to create a version that's compatible with python 2 and 3, but that proves to be a real pain. My issue with python 3 is that I'd have to maintain two versions, one for python2 and one for python3... I know I have to bit the bullet at some point and get to it. Maybe what that means is moving to python3 altogether and leaving python2 behind just as a legacy version.

**Comment by richardbushell** [comment]
Python 3 (with 2 as legacy) makes sense to me, it's an easy upgrade for v2 users. Thought I'd ask the question, but appreciate if it's not an immediate priority. You can close the issue if you wish, or leave it on a to do list...

**Comment by timcolson** [comment]
FYI - While running through an article on HLS & DASH (on OS X 10.14), ran into Python 2 code in Bento4 python wrappers that will not run with Python 3. (article: https://medium.com/@Gnaphron/the-grand-unified-streaming-89033a97e26e)

After fixing a dozen print -> print(x) statements, ran into more problems, then learned that Bento4 does not support Python3. Mmm...okay, so decided to downgrade for the day to Python 2.7...

Uninstalled Python3 with homebrew, but installing brew bento4 formula depends on "python" which as of March 2018 now means "Python 3" (See https://github.com/mopidy/homebrew-mopidy/issues/21)

Oh my, that's a bit of a pickle. No homebrew install of Bento4 for Mac OS users. Okay, so the lazy/easy route isn't going to work, but honestly, it's not 100% obvious to me where/how to install the binary snapshots either. :(

**Comment by MTonomy-Nchinda-Nchinda** [comment]
1. Install python2.7
2. Run `which mp4dash` to get the location of the executable that runs mp4-dash.py.
3. In that file change `python` to `python2.7`

**Comment by mmokhi** [comment]
> I do have a branch where I tried to create a version that's compatible with python 2 and 3, but that proves to be a real pain. My issue with python 3 is that I'd have to maintain two versions, one for python2 and one for python3... I know I have to bit the bullet at some point and get to it. Maybe what that means is moving to python3 altogether and leaving python2 behind just as a legacy version.

Hey @barbibulle :slightly_smiling_face: 
Is there possibilty for you to share your python-3 branch (or point me to repo if it's publicly available?).
I am about to start porting it to python-3 but if there's a thing to start with (and help you with) it'd be easier :smile: 

Thanks :pray:

**Comment by barbibulle** [comment]
I'll try to push a python3 branch soon. I've been lagging a bit on getting that done, but it is becoming more and more urgent now.

**Comment by timcolson** [comment]
> python3 altogether and leaving python2 behind
Past three months, intense learning of Python to build/deploy two video migration utilities. Given this new experience, I believe Python3 only, with 2 as legacy, is the way to go.

**Comment by mmokhi** [comment]
> I'll try to push a python3 branch soon. I've been lagging a bit on getting that done, but it is becoming more and more urgent now.

Thanks for the feedback,
Tell me if I can be any help :smile: :+1:

**Comment by dionisioC** [comment]
> I'll try to push a python3 branch soon. I've been lagging a bit on getting that done, but it is becoming more and more urgent now.

Good news, let me know if you need a hand

**Comment by qchroman** [comment]
Hello all,

Just wanted to check if moving to p3 is still a plan and if there are any ETAs available :)

Thank you for the great product!

**Comment by bakkenlab** [comment]
Has anyone tried using the 2to3 pip library to port the python scripts to 3? Not sure if it's worth trying on my end since that sounds too easy and idk what else would have to be done to get it working.

**Comment by aalireza439** [comment]
I used the 2to3, I got this error:
```
ERROR: This tool must be run with Python 2.x
You are running Python version: 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by barbibulle** [comment]
Since the official EOL time for Python 2 was Jan 1 2020, the time has really come for me to stop procrastinating, and port everything over to python3.
I have that mostly complete. I still need to run a few tests. I'm planning on releasing a version for people to try sometime in the next couple weeks.

**Comment by sagargnkr** [comment]
Hi @barbibulle , I am stuck with few functions when porting to python3 like ComputeWidevineHeader Can you help out?

**Comment by barbibulle** [comment]
I have pushed a branch where everything has been migrated to python3. Can you try that and let me know if it works for you?

**Comment by sagargnkr** [comment]
Hi @barbibulle , this worked for me. Thank you.
