### ISSUE TITLE
Not accurate Russian language name in LanguageNames 

### ISSUE THREAD

**Issue by bvc3at** [axiomatic-systems/Bento4#307]
Hi!

In `LanguageNames` code `ru` has name `русский язык`, which stands for `russian language` what is not quite the same as other language names (for example, code `en` has name `English`). As native speaker i think, `Русский` (which stands for 'Russian') is more accurate name.
https://github.com/axiomatic-systems/Bento4/blob/master/Source/Python/utils/mp4utils.py#L181

**Comment by barbibulle** [comment]
Thanks for noticing and fixing this.
