### ISSUE TITLE
AVI and WEBM video formats

### ISSUE THREAD

**Issue by kabhagava** [axiomatic-systems/Bento4#313]
Hello, thanks for making this very easy to use tool!  I have tried it with MP4 videos successfully. Does the tool also support other video formats like avi, or webm?

**Comment by barbibulle** [comment]
AVI and WebM are very different formats. Bento4 focused on all formats based on the ISO Base File Format standard (i.e MP4), but doesn't aim to be a general purpose all-format library. If does support MPEG2-TS in some form, mostly for conversion from MP4 to MPEG2-TS, which is a common use case for HLS streaming
