### ISSUE TITLE
Video tracks are not aligned

### ISSUE THREAD

**Issue by Jason239** [axiomatic-systems/Bento4#315]
Hi,
I have two files that differ only in resolution and bitrates.
As a result of checking, GOP, key frame, and fps are the same.

So, what else case does this error occur?
`ERROR: video tracks are not aligned ("File 2#1" differs from File 1#1)`

**Comment by barbibulle** [comment]
It is likely that your encoder isn't configured to be strict about encoding with fixed-size GOPs. Is it possible for you to post links to an example that illustrates the problem you're seeing, so that I can check if that's the case?

**Comment by Jason239** [comment]
As you mentioned, the GOP is not completely fixed-size. Therefore, it seems to be caused by the inconsistency of the frame in the middle.

Thanks for your help
