### ISSUE TITLE
Version 1 of track run box is not supported.

### ISSUE THREAD

**Issue by lnwhome** [axiomatic-systems/Bento4#328]
ISO/IEC 14496-12 2015 introduces version 1 of trun box which allows negative composition time.
This is not supported now by Bento4. 
Can you add support for new trun box ? What would be time frame for this activity ?
For convenience, I place new trun box description here.
The description comes from ISO/IEC 14496-12 2015, chapter 8.8.8
"
aligned(8) class TrackRunBox 
			extends FullBox(‘trun’, version, tr_flags) {
	unsigned int(32)	sample_count;
	// the following are optional fields 
	signed int(32)	data_offset;
	unsigned int(32)	first_sample_flags;
	// all fields in the following array are optional
	{
		unsigned int(32)	sample_duration;
		unsigned int(32)	sample_size;
		unsigned int(32)	sample_flags
		if (version == 0) 
			{ unsigned int(32)	sample_composition_time_offset; }
		else
			{ signed int(32)		sample_composition_time_offset; }
	}[ sample_count ]
}
"

**Comment by barbibulle** [comment]
Closing this, as per my response by email. Let me know if this works for you as explained in the email, or if I should re-open this issue.
