### ISSUE TITLE
display codec string for audio tracks in mp4info

### ISSUE THREAD

**Issue by nickdesaulniers** [axiomatic-systems/Bento4#33]
mp4info currently lists the codec string for video tracks, which is very helpful.  I would like the codec string to be listed for audio, too.

**Comment by barbibulle** [comment]
That's implemented in the dev branch (haven't pushed all my changes yet, so isn't visible on GitHub just yet, should be there over the next day or so)

**Comment by barbibulle** [comment]
This is now in the master branch.

**Comment by nickdesaulniers** [comment]
cool thank you!
