### ISSUE TITLE
1.5.1-625 and newer are not tagged on GitHub

### ISSUE THREAD

**Issue by orivej** [axiomatic-systems/Bento4#346]
From https://www.bento4.com/downloads/ and commit messages it is evident that 1.5.1-624 is not the latest release, but it is the last release on GitHub: https://github.com/axiomatic-systems/Bento4/releases

**Comment by orivej** [comment]
This is why distributions have not noticed the updates: https://repology.org/metapackage/bento4/versions

**Comment by barbibulle** [comment]
Sorry about that. I forgot to push the last few tags... should be fixed now.
