### ISSUE TITLE
alternative to ffmpeg copy to fix header, in bento4

### ISSUE THREAD

**Issue by FloridaStream** [axiomatic-systems/Bento4#373]
After using bento4, I have to pass the file through `ffmpeg`, to fix the header, since it but of play without going through `ffmpeg -vcodec copy`, is there any way to fix this with bento4? without making use of `ffmpeg`? 

**If so, could you give me an example of how to do it?**

My output is written via `AP4_FileByteStream :: Create ("test_output.mp4", AP4_FileByteStream :: STREAM_MODE_WRITE, output);`

I'm still studying the features and uses of bento4, an amazing library, sorry if I asked any silly questions, I'm a layman. @barbibulle 

Thank you for your attention.

**Comment by barbibulle** [comment]
Hi @FloridaStream, the answer is: it depends. The first question is: why is the file you created with the library not playing? It should. When you say "fix the headers", what exactly is not correct in the header, or at least doesn't correspond to what you need? If you have an example of a small output file produced by the Bento4 library which doesn't play, and a version processed by ffmpeg that does play, I can take a look (I would also need to know which player to use to observe the failure to play).

**Comment by FloridaStream** [comment]
I am sending the original encrypted file, the file generated by bento4, and the file fixed by ffmpeg, are in the link below.
https://drive.google.com/file/d/1vOpzrtYA2vi7j8pHh2iZh_ZMJUSBnHsJ/view?usp=sharing

I am using a custom code, I do not know what may be causing this, I can not share the code openly.
I used VLC to test the files.

@barbibulle grateful for the attention, I hope to be able to solve this to avoid that I have to use ffmpeg.

**Comment by barbibulle** [comment]
The problem with your file here (looking at video_track_1.mp4) is that it is declared as having an encrypted track (use `mp4info` to show the track info), even though the track media is not encrypted. Looks like you decrypted the media samples, but didn't change the signaling in the track sample descriptions. When you decrypt with a tool like `mp4decrypt`, you'll see that the sample description is re-written to output a 'clear' sample description. I'm not sure how you generated the file, but that's the problem.
Also, the file has some 'odd' things (which aren't fatal, just not quite right): the media fragments have non-consecutive indexes (every other fragment sequence number is missing). That shouldn't prevent a player from playing it, in general, but it isn't compliant with the spec. Not sure how you generated those (when you use a tool like `mp4fragment`, you'll see that the fragment sequence numbers are correct.
