### ISSUE TITLE
mp4Fragment : timescale options change constant frame rate mode to variable

### ISSUE THREAD

**Issue by GaylordJacques** [axiomatic-systems/Bento4#378]
Hi,

I have an issue with mp4Fragment command.
I try to change the timescale of my input file to set it to 1000 (instead of 11988) like this:

`mp4fragment --timescale 1000 --fragment-duration 2000 video.mp4 video.fragmented.mp4`

Input : video.mp4 have a timescale of 11988, **constant frame rate mode** and a 23.976 frame rate.
Output : video.fragmented.mp4 have a timescale of 1000, 23.976 frame rate but a **variable frame rate mode**.

I need to keep a constant frame rate mode (like the input file) and a timescale of 1000.

After a quick code check it seems than it can be related to some timestamp value approximation due to 23.976 frame rate value and timescale of 11988.

video.mp4 (mp4info command)
-----------------------------
`mp4info video.mp4
File:
  major brand:      isom
  minor version:    1
  compatible brand: isom
  compatible brand: avc1
  fast start:       yes

Movie:
  duration:   1357483 ms
  time scale: 600
  fragments:  no

Found 2 Tracks
Track 1:
  flags:        1 ENABLED
  id:           1
  type:         Video
  duration: 1357398 ms
  language: und
  media:
    sample count: 32545
    **timescale:    11988**
    duration:     16272500 (media timescale units)
    duration:     1357399 (ms)
    bitrate (computed): 1496.362 Kbps
  display width:  960.000000
  display height: 540.000000
  frame rate (computed): 23.976
  Sample Description 0
    Coding:      avc1 (H.264)
    Width:       960
    Height:      540
    Depth:       24
    AVC Profile:          100 (High)
    AVC Profile Compat:   0
    AVC Level:            31
    AVC NALU Length Size: 4
    AVC SPS: [6764001facd940f0117ee1000003007d0000176a0f183196]
    AVC PPS: [68ebecb22c]
    Codecs String: avc1.64001F
Track 2:
  flags:        1 ENABLED
  id:           2
  type:         Audio
  duration: 1357483 ms
  language: und
  media:
    sample count: 58462
    timescale:    44100
    duration:     59865088 (media timescale units)
    duration:     1357485 (ms)
    bitrate (computed): 128.305 Kbps
  Sample Description 0
    Coding:      mp4a (MPEG-4 Audio)
    Stream Type: Audio
    Object Type: MPEG-4 Audio
    Max Bitrate: 161288
    Avg Bitrate: 128304
    Buffer Size: 1305
    Codecs String: mp4a.40.2
    MPEG-4 Audio Object Type: 2 (AAC Low Complexity)
    MPEG-4 Audio Decoder Config:
      Sampling Frequency: 44100
      Channels: 2
    Sample Rate: 44100
    Sample Size: 16
    Channels:    2`

video.mp4 (mediainfo command)
-----------------------------
`General
Complete name                            : video.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/avc1)
File size                                : 264 MiB
Duration                                 : 22 min 37 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 628 kb/s
Encoded date                             : UTC 2019-03-11 18:31:41
Tagged date                              : UTC 2019-03-11 18:31:41

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 22 min 37 s
Bit rate                                 : 1 500 kb/s
Maximum bit rate                         : 5 321 kb/s
Width                                    : 960 pixels
Height                                   : 540 pixels
Display aspect ratio                     : 16:9
**Frame rate mode                          : Constant**
Frame rate                               : 23.976 (23976/1000) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.121
Stream size                              : 242 MiB (92%)
Title                                    : 264@GPAC0.7.1-rev0-g440d475f1-heads/v0.7.1
Writing library                          : x264 core 157 r2935 545de2f
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=17 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=48 / keyint_min=25 / scenecut=0 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=1500 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 2019-03-11 18:31:41
Tagged date                              : UTC 2019-03-11 18:31:42

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 22 min 37 s
Bit rate mode                            : Variable
Bit rate                                 : 128 kb/s
Maximum bit rate                         : 161 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 20.8 MiB (8%)
Title                                    : aac@GPAC0.7.1-rev0-g440d475f1-heads/v0.7.1
Encoded date                             : UTC 2019-03-11 18:31:42
Tagged date                              : UTC 2019-03-11 18:31:42`

video.fragmented.mp4 (mp4info command)
-----------------------------
`mp4info video.fragmented.mp4
File:
  major brand:      isom
  minor version:    1
  compatible brand: isom
  compatible brand: avc1
  compatible brand: iso5
  fast start:       yes

Movie:
  duration:   1357483 ms
  time scale: 1000
  fragments:  yes

Found 2 Tracks
Track 1:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           1
  type:         Video
  duration: 1357398 ms
  language: und
  media:
    sample count: 0
    **timescale:    1000**
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 1496.362 Kbps
    sample count with fragments: 32545
    duration with fragments:     1357399
    duration with fragments:     1357399 (ms)
  display width:  960.000000
  display height: 540.000000
  Sample Description 0
    Coding:      avc1 (H.264)
    Width:       960
    Height:      540
    Depth:       24
    AVC Profile:          100 (High)
    AVC Profile Compat:   0
    AVC Level:            31
    AVC NALU Length Size: 4
    AVC SPS: [6764001facd940f0117ee1000003007d0000176a0f183196]
    AVC PPS: [68ebecb22c]
    Codecs String: avc1.64001F
Track 2:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           2
  type:         Audio
  duration: 1357483 ms
  language: und
  media:
    sample count: 0
    timescale:    1000
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 128.305 Kbps
    sample count with fragments: 58462
    duration with fragments:     1357485
    duration with fragments:     1357485 (ms)
  Sample Description 0
    Coding:      mp4a (MPEG-4 Audio)
    Stream Type: Audio
    Object Type: MPEG-4 Audio
    Max Bitrate: 161288
    Avg Bitrate: 128304
    Buffer Size: 1305
    Codecs String: mp4a.40.2
    MPEG-4 Audio Object Type: 2 (AAC Low Complexity)
    MPEG-4 Audio Decoder Config:
      Sampling Frequency: 44100
      Channels: 2
    Sample Rate: 44100
    Sample Size: 16
    Channels:    2`

video.fragmented.mp4 (mediainfo command)
-----------------------------
General
Complete name                            : video.fragmented.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/avc1/iso5)
File size                                : 264 MiB
Duration                                 : 22 min 37 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 631 kb/s

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 22 min 37 s
Bit rate                                 : 1 500 kb/s
Maximum bit rate                         : 5 321 kb/s
Width                                    : 960 pixels
Height                                   : 540 pixels
Display aspect ratio                     : 16:9
**Frame rate mode                          : Variable**
Frame rate                               : 23.976 (23976/1000) FPS
Minimum frame rate                       : 23.810 FPS
Maximum frame rate                       : 24.390 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.121
Stream size                              : 242 MiB (92%)
Writing library                          : x264 core 157 r2935 545de2f
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=17 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=48 / keyint_min=25 / scenecut=0 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=1500 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 22 min 37 s
Bit rate mode                            : Variable
Bit rate                                 : 128 kb/s
Maximum bit rate                         : 161 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 20.8 MiB (8%)

**Comment by barbibulle** [comment]
The problem is that if you want to force a media timescale of 1000, you won't be able to keep a precise frame rate of 23.976, because the timescale is too small to keep the necessary precision. Frames (a.k.a samples) have a duration that's a multiple of the timescale. So if you impose a timescale of 1000, your frames will have durations that are integral number of milliseconds. But with a framerate of 23.976, each frame has a duration of  1/23.976 seconds, or 1000/23.976 timescale units, which isn't an integer (it is 41.7083...). So some frames will have a duration of 41 units, some 42 units. Not far off, but not constant. If you want a constant framerate, your timescale must be a multiple of 2997, because then each frame duration will be a multiple of 2997/23.976 which is 125 exactly, so all frames can have the exact same duration in timescale units. In the original file here, your timescale was 11988, which is a multiple of 2997, so that worked out to constant duration frames.
Now, keep in mind that the media timescale is purely a number used internally by the player to compute timestamps, it has no effect on anything visible to the end user (for instance, choosing a timescale of 2997 or 11988) makes no practical difference. So is there a specific reason why you need to change the timescale of your file to 1000?  Also, even if you do that, even though technically your output file will have frames with non-constant duration, I doubt that you would see a difference when playing the file back, because the difference in timing would be less than a millisecond, and given that your screen refresh rate is likely around 16 milliseconds (for 60fps), you would not see the difference (because the frames are already displayed at a time that's been rounded to the nearest frame display time, which every ~16ms).

**Comment by GaylordJacques** [comment]
Hi Barbibulle,

Thanks for your support.

Finally we use a timescale of 10000000 to avoid some fragmentation issue. Some preprocessing tools seems to manage 100nanoseconds fragments perhaps to manage this case of 23.976 fps.
