### ISSUE TITLE
mp4-dash.py floating-point arithmetic error

### ISSUE THREAD

**Issue by ATrattnig** [axiomatic-systems/Bento4#39]
Hi,
In function AddSegmentTemplate (mp4-dash.py) you calculate the duration for the segmenttemplate the following way:
duration=str(int(track.average_segment_duration*1000))

I encountered the case that track.average_segment_duration is exactly 4.004.
If you use this value in the calculation the resulting duration will be "4003", due to floating point arithmetic before calling the function. You can try it yourself, in a python shell.
I propose you use duration=str(int(round(track.average_segment_duration*1000))) instead. 

Best Regards
Armin

**Comment by barbibulle** [comment]
You're right, that would be better. Thanks for the tip. I'll make the change.

**Comment by barbibulle** [comment]
The change has been made in the latest release.
