### ISSUE TITLE
Creating Content for Dash

### ISSUE THREAD

**Issue by sinhalaBsc** [axiomatic-systems/Bento4#399]
I want to make video stream server and backend I am planing to make video fragments process using Bento4's mp4-dash.py Python script to generate the corresponding MPD file needed by clients.

library source - git clone https://github.com/axiomatic-systems/Bento4.git

tutorial source - https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API/Transcoding_assets_for_MSE#Getting_started

but I am getting following errors for following linux batch commands.

I've tried on some changes with batch command but it wont works.

$ python mp4-dash-encode.py -b 5 -v fragmented.mp4
(works successfully )

$ python mp4-dash.py --exec-dir=<path to Bento4 tools> video_0*
(getting error)

Python error: is a directory, cannot continue 
ERROR: media file to does not exist
Thanks !

**Comment by barbibulle** [comment]
When using the `--exec-dir` option, you need to pass it the location where the compiled executables are. You normally only have to use that option if you've compiled the executable yourself and want the `mp4-dash` tool to point to your compiled executable. If you have downloaded the package with pre-compiled binaries, then you can just use the `mp4dash` command located in the `bin` directory.
