### ISSUE TITLE
incorrect sample count in saiz audio track with CBCS

### ISSUE THREAD

**Issue by ivan2037** [axiomatic-systems/Bento4#428]
Hi. 

I am trying to generate a fmp4 DASH Widevine DRM with the CBCS protection scheme. 
Only "sample count" in "saiz" AUDIO track shows 0 instead of 243 and exoPlayer is having a problem. 

Do you know how to resolve this? Thank you for your support. 

[moof] size=8+1113
  [mfhd] size=12+4
    sequence number = 2
  [traf] size=8+1089
    [tfhd] size=12+8, flags=20008
      track ID = 2
      default sample duration = 1024
    [tfdt] size=12+8, version=1
      base media decode time = 0
    [trun] size=12+984, flags=201
      sample count = 244
      data offset = 1129
      entry 0000 = sample_size:23
      entry 0001 = sample_size:6
      entry 0002 = sample_size:6
      entry 0003 = sample_size:232
      entry 0004 = sample_size:334
      entry 0005 = sample_size:169
      entry 0006 = sample_size:177
      entry 0007 = sample_size:178
      entry 0008 = sample_size:188
      entry 0009 = sample_size:191
      entry 0010 = sample_size:190
      entry 0011 = sample_size:186
      entry 0012 = sample_size:185
      entry 0013 = sample_size:168
      entry 0014 = sample_size:167
      entry 0015 = sample_size:171
      entry 0016 = sample_size:165
      entry 0017 = sample_size:189
      entry 0018 = sample_size:177
      entry 0019 = sample_size:170
      entry 0020 = sample_size:179
      entry 0021 = sample_size:174
      entry 0022 = sample_size:155
      entry 0023 = sample_size:171
      entry 0024 = sample_size:171
      entry 0025 = sample_size:191
      entry 0026 = sample_size:196
      entry 0027 = sample_size:187
      entry 0028 = sample_size:166
      entry 0029 = sample_size:172
      entry 0030 = sample_size:177
      entry 0031 = sample_size:161
      entry 0032 = sample_size:178
      entry 0033 = sample_size:154
      entry 0034 = sample_size:178
      entry 0035 = sample_size:176
      entry 0036 = sample_size:189
      entry 0037 = sample_size:192
      entry 0038 = sample_size:176
      entry 0039 = sample_size:198
      entry 0040 = sample_size:153
      entry 0041 = sample_size:152
      entry 0042 = sample_size:159
      entry 0043 = sample_size:181
      entry 0044 = sample_size:183
      entry 0045 = sample_size:187
      entry 0046 = sample_size:191
      entry 0047 = sample_size:181
      entry 0048 = sample_size:173
      entry 0049 = sample_size:168
      entry 0050 = sample_size:160
      entry 0051 = sample_size:161
      entry 0052 = sample_size:171
      entry 0053 = sample_size:157
      entry 0054 = sample_size:181
      entry 0055 = sample_size:175
      entry 0056 = sample_size:196
      entry 0057 = sample_size:198
      entry 0058 = sample_size:193
      entry 0059 = sample_size:172
      entry 0060 = sample_size:163
      entry 0061 = sample_size:173
      entry 0062 = sample_size:178
      entry 0063 = sample_size:184
      entry 0064 = sample_size:184
      entry 0065 = sample_size:187
      entry 0066 = sample_size:188
      entry 0067 = sample_size:180
      entry 0068 = sample_size:158
      entry 0069 = sample_size:149
      entry 0070 = sample_size:167
      entry 0071 = sample_size:171
      entry 0072 = sample_size:176
      entry 0073 = sample_size:179
      entry 0074 = sample_size:178
      entry 0075 = sample_size:170
      entry 0076 = sample_size:180
      entry 0077 = sample_size:141
      entry 0078 = sample_size:144
      entry 0079 = sample_size:161
      entry 0080 = sample_size:174
      entry 0081 = sample_size:182
      entry 0082 = sample_size:186
      entry 0083 = sample_size:188
      entry 0084 = sample_size:179
      entry 0085 = sample_size:181
      entry 0086 = sample_size:179
      entry 0087 = sample_size:179
      entry 0088 = sample_size:173
      entry 0089 = sample_size:147
      entry 0090 = sample_size:152
      entry 0091 = sample_size:173
      entry 0092 = sample_size:177
      entry 0093 = sample_size:187
      entry 0094 = sample_size:169
      entry 0095 = sample_size:170
      entry 0096 = sample_size:185
      entry 0097 = sample_size:177
      entry 0098 = sample_size:170
      entry 0099 = sample_size:163
      entry 0100 = sample_size:180
      entry 0101 = sample_size:175
      entry 0102 = sample_size:167
      entry 0103 = sample_size:181
      entry 0104 = sample_size:170
      entry 0105 = sample_size:161
      entry 0106 = sample_size:158
      entry 0107 = sample_size:175
      entry 0108 = sample_size:172
      entry 0109 = sample_size:168
      entry 0110 = sample_size:174
      entry 0111 = sample_size:181
      entry 0112 = sample_size:177
      entry 0113 = sample_size:174
      entry 0114 = sample_size:204
      entry 0115 = sample_size:181
      entry 0116 = sample_size:156
      entry 0117 = sample_size:166
      entry 0118 = sample_size:221
      entry 0119 = sample_size:285
      entry 0120 = sample_size:207
      entry 0121 = sample_size:159
      entry 0122 = sample_size:172
      entry 0123 = sample_size:147
      entry 0124 = sample_size:154
      entry 0125 = sample_size:149
      entry 0126 = sample_size:182
      entry 0127 = sample_size:180
      entry 0128 = sample_size:164
      entry 0129 = sample_size:167
      entry 0130 = sample_size:174
      entry 0131 = sample_size:178
      entry 0132 = sample_size:163
      entry 0133 = sample_size:228
      entry 0134 = sample_size:157
      entry 0135 = sample_size:169
      entry 0136 = sample_size:153
      entry 0137 = sample_size:176
      entry 0138 = sample_size:158
      entry 0139 = sample_size:160
      entry 0140 = sample_size:168
      entry 0141 = sample_size:167
      entry 0142 = sample_size:171
      entry 0143 = sample_size:146
      entry 0144 = sample_size:167
      entry 0145 = sample_size:169
      entry 0146 = sample_size:172
      entry 0147 = sample_size:195
      entry 0148 = sample_size:186
      entry 0149 = sample_size:190
      entry 0150 = sample_size:193
      entry 0151 = sample_size:162
      entry 0152 = sample_size:152
      entry 0153 = sample_size:161
      entry 0154 = sample_size:165
      entry 0155 = sample_size:160
      entry 0156 = sample_size:162
      entry 0157 = sample_size:182
      entry 0158 = sample_size:193
      entry 0159 = sample_size:186
      entry 0160 = sample_size:180
      entry 0161 = sample_size:279
      entry 0162 = sample_size:155
      entry 0163 = sample_size:152
      entry 0164 = sample_size:165
      entry 0165 = sample_size:168
      entry 0166 = sample_size:260
      entry 0167 = sample_size:173
      entry 0168 = sample_size:179
      entry 0169 = sample_size:229
      entry 0170 = sample_size:209
      entry 0171 = sample_size:146
      entry 0172 = sample_size:152
      entry 0173 = sample_size:159
      entry 0174 = sample_size:167
      entry 0175 = sample_size:174
      entry 0176 = sample_size:170
      entry 0177 = sample_size:181
      entry 0178 = sample_size:172
      entry 0179 = sample_size:212
      entry 0180 = sample_size:216
      entry 0181 = sample_size:189
      entry 0182 = sample_size:152
      entry 0183 = sample_size:168
      entry 0184 = sample_size:159
      entry 0185 = sample_size:173
      entry 0186 = sample_size:169
      entry 0187 = sample_size:183
      entry 0188 = sample_size:184
      entry 0189 = sample_size:155
      entry 0190 = sample_size:150
      entry 0191 = sample_size:163
      entry 0192 = sample_size:166
      entry 0193 = sample_size:159
      entry 0194 = sample_size:155
      entry 0195 = sample_size:173
      entry 0196 = sample_size:162
      entry 0197 = sample_size:178
      entry 0198 = sample_size:156
      entry 0199 = sample_size:152
      entry 0200 = sample_size:166
      entry 0201 = sample_size:160
      entry 0202 = sample_size:181
      entry 0203 = sample_size:174
      entry 0204 = sample_size:179
      entry 0205 = sample_size:175
      entry 0206 = sample_size:175
      entry 0207 = sample_size:162
      entry 0208 = sample_size:156
      entry 0209 = sample_size:169
      entry 0210 = sample_size:176
      entry 0211 = sample_size:189
      entry 0212 = sample_size:196
      entry 0213 = sample_size:178
      entry 0214 = sample_size:172
      entry 0215 = sample_size:173
      entry 0216 = sample_size:175
      entry 0217 = sample_size:177
      entry 0218 = sample_size:173
      entry 0219 = sample_size:172
      entry 0220 = sample_size:168
      entry 0221 = sample_size:183
      entry 0222 = sample_size:178
      entry 0223 = sample_size:178
      entry 0224 = sample_size:169
      entry 0225 = sample_size:167
      entry 0226 = sample_size:172
      entry 0227 = sample_size:160
      entry 0228 = sample_size:174
      entry 0229 = sample_size:162
      entry 0230 = sample_size:175
      entry 0231 = sample_size:173
      entry 0232 = sample_size:166
      entry 0233 = sample_size:191
      entry 0234 = sample_size:171
      entry 0235 = sample_size:185
      entry 0236 = sample_size:188
      entry 0237 = sample_size:181
      entry 0238 = sample_size:184
      entry 0239 = sample_size:174
      entry 0240 = sample_size:177
      entry 0241 = sample_size:169
      entry 0242 = sample_size:172
      entry 0243 = sample_size:174
    [saiz] size=12+5
      default sample info size = 0
      **sample count = 0**
    [saio] size=12+8
      entry count = 1
      entry        0 = 1121
    [senc] size=12+4
      sample info count = 244
      IV Size (inferred) = 0
      entry 0000 = []
      entry 0001 = []

example)
Bento4/bin/mp4encrypt input.mp4 output.mp4 --method MPEG-CBCS --key 1:0a876b0752cbf1a827e2fecfb8747333:efefefefefefefefefefefefefefefef --property 1:KID:99991951686b5e1ba222439999c1f12a --key 2:0a876b0752cbf1a913e2fecfb8747333:efefefefefefefefefefefefefefefef --property 2:KID:99991951686b5e1ba222439999c1f12b

**Comment by barbibulle** [comment]
For audio tracks, there is no need for per-sample 'sample info'. So the `saiz` table has `sample_count` = 0. Admitedly, the `senc` box here isn't useful, since it contains no information, and having it specify 244 entries each of size 0 may be confusing to some parsers.
Is it the `saiz` box that's confusing Exoplayer, or the `senc` with 0-size entries?

**Comment by ivan2037** [comment]
Thank you for your prompt reply. 

It appears to be the exoplayer is confused with saiz box. 
I will try to investigate more and provide you more info. Thank you for very. :)

`Caused by: com.google.android.exoplayer2.ParserException: Length mismatch: 0, 244
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseSaiz(FragmentedMp4Extractor.java:781)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseTraf(FragmentedMp4Extractor.java:705)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseMoof(FragmentedMp4Extractor.java:673)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onMoofContainerAtomRead(FragmentedMp4Extractor.java:546)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onContainerAtomRead(FragmentedMp4Extractor.java:459)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.processAtomEnded(FragmentedMp4Extractor.java:437)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:432)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:318)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:135)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)`

**Comment by barbibulle** [comment]
Looks like a bug in ExoPlayer. The code that's throwing the exception is:
```
int sampleCount = saiz.readUnsignedIntToInt();
    if (sampleCount != out.sampleCount) {
      throw new ParserException("Length mismatch: " + sampleCount + ", " + out.sampleCount);
    }
```

which requires that the `saiz` box have as many entries as the number of samples in the fragment, but that's wrong for audio and CBCS encryption, since in that case there's a fixed IV for the whole track, and therefore no per-sample crypto info.

**Comment by ivan2037** [comment]
I thought so. The Chrome and Safari play without any issue. 
Thank you for your support.

**Comment by ivan2037** [comment]
FYI. 
The exoPlayer works with the following CBCS content. saiz box sample count is same as samples in the audio fragment. 

https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs.mpd 

https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs.mpd;license=https://proxy.uat.widevine.com/proxy?provider=widevine_test;lang=en-US;build=uncompiled

audio: 
 https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_audio_eng_aes_cbcs.mp4

video: https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_h264_main_480p_2000_aes_cbcs.mp4

**Comment by ivan2037** [comment]
> FYI.
> The exoPlayer works with the following CBCS content. saiz box sample count is same as samples in the audio fragment.
> 
> https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs.mpd
> 
> https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs.mpd;license=https://proxy.uat.widevine.com/proxy?provider=widevine_test;lang=en-US;build=uncompiled
> 
> audio:
> https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_audio_eng_aes_cbcs.mp4
> 
> video: https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_h264_main_480p_2000_aes_cbcs.mp4

tears_audio_eng_aes_cbcs.mp4 doesn't contain "saiz" box.
