### ISSUE TITLE
mp4decrypt working on windows but not linux

### ISSUE THREAD

**Issue by glboy** [axiomatic-systems/Bento4#450]
Hi all

I'm doing a dash decrypt with mp4decrypt, on windows its working perfectly, takes about 90s and then the decryption is complete

On Linux it just finishes instantly but the output file is identical to the input, no decryption has occured, its just a copy of the original file

I've tried 3 different boxes Debian/Ubuntu, I've tried older builds, I've tried precompiled, I've tried compiling, all the same result

My mp4decrypt syntax is as follows
mp4decrypt --key 12345678910111213141516171819202:12345678910111213141516171819202 --key 12345678910111213141516171819202:12345678910111213141516171819202 --key 12345678910111213141516171819202:12345678910111213141516171819202 input.mp4 output.mp4 --show-progress

I'm not sure if this is a bug or I'm missing something obvious

Thanks for any input

**Comment by chicc0** [comment]
Same problem here. Tried DEBUG and release builds. Tried compiling with make, cmake sconf.. Not working with anything..

**Comment by barbibulle** [comment]
I'm surprised this works on Windows. The ability to decrypt by passing a KID does not currently work, only decrypting by track ID works (the documentation of the `mp4decrypt` command line usage is wrong in that regard). So in this example, you'd have to pass the track IDs instead of the KIDs associated with each track.

**Comment by glboy** [comment]
thanks for your reply

on windows passing track id trackid:key trackid:key track:key doesn't work, but KID:KEY works

however on linux ive had mixed success with trackid:key trackid:key trackid:key, it seems to work out video more often than not, but often doesnt work on audio tracks

it takes time like its decrypting, and it says it decrypted, but missing audio headers, on windows the headers are always there with the same decryption string

is there anything you can suggest i try?

**Comment by barbibulle** [comment]
I have pushed a new build of the tools to the server. Decrypting by KID should work now. Can you try again and let me know if it works for you?

**Comment by glboy** [comment]
hi again

yes this is now working on windows and linux when passing the KID

thanks for your prompt fix! much appreciated
