### ISSUE TITLE
mp4decrypt not decrypting properly

### ISSUE THREAD

**Issue by ghoshben** [axiomatic-systems/Bento4#454]
the encrypted file(audio) : https://transfer.sh/hqWjd/video_encrypted.mp4
kid:key (in hex) : 00000000000000000000000000000000:328f3f687d3d91f8d6ae092706b0391b

inproperly decrypted file (corrupted audio though mediainfo is showing decrypted)
https://we.tl/t-gN8w08Pj6o

encyption SAMPLE-AES (CBCS)

**Comment by barbibulle** [comment]
I'm getting a 'Not Found' error when trying to download the encrypted file

**Comment by ghoshben** [comment]
really sorry https://we.tl/t-O1Fn6q2GcA thats the encrypted file

**Comment by barbibulle** [comment]
Do you have the original (non-encrypted file), as well as the command-line parameters you used to encrypt it?

**Comment by ghoshben** [comment]
Sadly I dont own that file and has no idea which argument they used for encrypting the file however the source file is a hls which is 
https://we.tl/t-2p1Hz2E9Rw

**Comment by forty875** [comment]
I have same error, decrypt not working, but only when audio type is atmos, normal AC3 tracks decrypt works, AAC i didn't test...
Here is a non encrypted file from a trailer  -> https://www.file-upload.net/download-13788152/P61785796_A1478195567_de-DE_audio_gr2448.mp4.html
non working atmos file -> https://www.file-upload.net/download-13794555/P62207994_A1482150912_de_audio_gr2448.mp4.html
working AC3 file from same movie -> https://www.file-upload.net/download-13794580/P62207994_A1482150912_de_audio_gr384-.m3u8_video.mp4.html

decrypt key for both files should be 1c8cc4b37c57ff34574a8e19f1f0f200

**Comment by ghoshben** [comment]
@forty875 do u have discord or slack ?

**Comment by forty875** [comment]
@ghoshben
did you got decrypt to work or why closed? Still not working for me. This is maybe the same issue as this here https://github.com/axiomatic-systems/Bento4/issues/452

**Comment by ghoshben** [comment]
@forty875 it did, I hope you are referencing to a hls file .either u did not recovered the key correctly or else there is some Xdiscontinuety tag in that hls file which are encrypted with different keyes , so you need to get on the segments before that tag. hope that helps

**Comment by forty875** [comment]
So you can decrypt atmos audio 448/768 track? There is no Xdiscontinuety in my m3u8 and i downloaded every segement correctly because its working for a normal AC3 384 track...

**Comment by ghoshben** [comment]
if so you are probably getting wrong key the atmos tag requires l1 cdm
(most probably however really dont think its safe to discuss over here)
ᐧ

**Comment by forty875** [comment]
Thanks for info, i only have L3 so that might be the problem why its not working... Anyway you can contact me at forty2877@outlook.de

**Comment by barbibulle** [comment]
The atmos file linked here (https://www.file-upload.net/download-13794555/P62207994_A1482150912_de_audio_gr2448.mp4.html) has not been encrypted correctly. The audio samples point to "sample description 2", but there's only one sample description in the track info ("stsd" table), so the decrypter just skips the decryption of the samples, as it doesn't have any crypto metadata available to decrypt them. @forty875  do you know what tool was used to encrypt the atmos audio file?

**Comment by X-C0DE** [comment]
Has anyone solved this?
