### ISSUE TITLE
mp4-dash.py fails when source or output path include unicode characters

### ISSUE THREAD

**Issue by dsander** [axiomatic-systems/Bento4#46]
Hi,

when the source file or output path include unicode characters `mp4-dash.py`fails do write the output files: 

```
$ mp4-dash.py --profiles=on-demand -d -v -f -o "/opt/sb4/data/proxies/media_1/GötzeTest/testfiles/Götze.mp3" "/opt/sb4/data/proxies/media_1/GötzeTest/testfiles/Götze.mp3/fragmented.mp4"
```

```
Traceback (most recent call last):
  File "/opt/sb4/stage/bin/mp4-dash.py", line 1333, in <module>
    main()
  File "/opt/sb4/stage/bin/mp4-dash.py", line 1301, in main
    media_filename = path.join(options.output_dir, mp4_file.media_name)
  File "/opt/sb4/stage/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)
```

We were able to fix this for our use case (our arguements are always UTF-8 encoded) by adding this to the script:

```
reload(sys)
sys.setdefaultencoding('utf8')
```

Since I don't know python very well and this solution will probably break on non unicode terminals I did not submit a pull request. 

Let me know if you need additional information.

Thanks,

Dominik

**Comment by barbibulle** [comment]
Thanks for pointing that out. We'll fix this in the next release.

**Comment by bigt11** [comment]
I also ran into this in v1.5.0-614.  My source folder had a dash (-) in its name, I exchanged it for an underscore (_) and my mp4dash.bat command no longer contains an  UnicodeDecodeError

**Comment by barbibulle** [comment]
I'm not able to reproduce this error. Can you give a specific example of the command-line you used and the error that was printed out?
