### ISSUE TITLE
mp4encrypt updates the tfra's entries more than once

### ISSUE THREAD

**Issue by nadimix** [axiomatic-systems/Bento4#47]
Hi,

I found a bug which, in some cases, updates the tfra entries more than once. This causes responses with the code "415 - Unsupported Media Type"  in services like Akamai when the client requests certain fragments with a correct moof offset but doesn't match with the tfra's entries.

Cheers,
Nadim.

**Comment by barbibulle** [comment]
Thanks for tracking this. I’ll take a look at this shortly and get back to you.

-- Gilles


On December 7, 2015 at 2:37:52 AM, Nadim El Taha (notifications@github.com) wrote:

Hi,

I found a bug which, in some cases, updates the tfra entries more than once. This causes responses with the code "415 - Unsupported Media Type" in services like Akamai when the client requests certain fragments with a correct moof offset but doesn't match with the tfra's entries.

Cheers,
Nadim.

**Comment by nadimix** [comment]
You're welcome, don't hesitate to ask.
