### ISSUE TITLE
Issue in mp4fragment for mp4 files with vorbis audio codec

### ISSUE THREAD

**Issue by soniurvi2610** [axiomatic-systems/Bento4#472]
Hi,

We're trying to do dash packaging with multi-bitrate video encoding with vp9 and vorbis codecs. Once, variants are generated and we do fragmentation of these variants we're getting below mentioned core dump error

```
/opt/bento4_vp9/bin/mp4fragment --fragment-duration 10000 --debug 156MB_vp9test_vorbis_360p.mp4 156MB_vp9test_vorbis_360p_frag.mp4

mp4fragment: Source/C++/Core/Ap4Expandable.cpp:61: AP4_Expandable::AP4_Expandable(AP4_UI32, AP4_Expandable::ClassIdSize, AP4_Size, AP4_Size): Assertion `header_size <= 1+4' failed.
Aborted (core dumped)
```

Below are the commands used in entire process :
**A. Video Encoding :: Ffmpeg**
```
ffmpeg -i 156MB_3.50min.mp4 -y -hide_banner -map 0:v -s 640x360 -c:v vp9 -b:v 1.2M -maxrate 2.4M -bufsize 2.4M -pix_fmt yuv420p -color_primaries bt709 -colorspace bt709 -color_range tv -g 240 -quality good -speed 2 -map 0:a -ar 48000 -c:a vorbis -b:a:0 192k -ac:a:0 2 -f mp4 -strict -2 156MB_vp9test_vorbis_360p.mp4
```

**B. Fragmentation :: mp4fragment**
```
/opt/bento4_vp9/bin/mp4fragment --fragment-duration 10000 --debug 156MB_vp9test_vorbis_360p.mp4 156MB_vp9test_vorbis_360p_frag.mp4
```
The videos can be downloaded from below location : 
1. Source file : https://public.jetstream.video/stage/vp9test_new/156MB_VorbisTest/156MB_3.50min.mp4
2. 360p : https://public.jetstream.video/stage/vp9test_new/156MB_VorbisTest/156MB_vp9test_vorbis_360p.mp4

**Note: I've build Bento4 binaries with latest vp9 changes**

**Comment by barbibulle** [comment]
I'm able to replicate the issue on my side. I'll look into it and let you know.
