### ISSUE TITLE
mp4-dash.py fails when outputting HLS

### ISSUE THREAD

**Issue by jimmymic** [axiomatic-systems/Bento4#477]
Hi @barbibulle ,

PR provided

python /usr/local/bento4/utils/dash.py --debug --verbose --profiles live  --encryption-key **:**:**--encryption-cenc-scheme=cbcs --hls --hls-master-playlist-name 1CBDBB3ACAF62A8F518F57EF921C8523_fmp4.m3u8 --fairplay-key-uri ** --force --use-segment-timeline -o fairplay "Moxion Glass_1080p-fragmented.mp4" "Moxion Glass_1080pHDR(HEVC)-fragmented.mp4"

Fails with error 

Traceback (most recent call last):
  File "/usr/local/bento4/utils/mp4-dash.py", line 1988, in <module>
    main()
  File "/usr/local/bento4/utils/mp4-dash.py", line 1970, in main
    OutputHls(options, set_attributes, audio_sets, video_sets, subtitles_sets, subtitles_files)
  File "/usr/local/bento4/utils/mp4-dash.py", line 821, in OutputHls
    OutputHlsTrack(options, audio_track, all_audio_tracks + all_video_tracks, media_subdir, media_playlist_name, media_file_name)
NameError: global name 'all_audio_tracks' is not defined

**Comment by mhassanist** [comment]
@jimmymic  I commented that line #766 
 all_audio_tracks     = sum(audio_sets.values(),     [])
but still have the issue.

**Comment by barbibulle** [comment]
Maybe your `mp4dash` command points to a different version of the tools?  `mp4dash` is just a launcher for `python3 mp4-dash.py`:
```
#! /bin/bash
BASEDIR=$(dirname $0)
exec python3 "$BASEDIR/../utils/mp4-dash.py" "$@"
```
