### ISSUE TITLE
mp4extract and CRLF characters on Windows

### ISSUE THREAD

**Issue by stt** [axiomatic-systems/Bento4#479]
mp4extract -stdout produces carriage return characters on Windows causing different output compared to writing direct to file.

    $ mp4extract.exe moov vid.mp4 tst.dat; md5sum.exe tst.dat
    ea20c2c6dd525f126296f99c5ac566ca *tst.dat

    $ mp4extract.exe moov vid.mp4 -stdout | md5sum.exe
    ff1b699a5dae29901cf5f4cf00868138 *-

On linux matching commands produce the same checksum.
Both are (Bento4 Version 1.5.1.0)

**Comment by barbibulle** [comment]
With the fix just pushed, you should be able to use the name `-stdout#` to specify you want stdout in binary mode on Windows (or `-stdin#` for stdin in binary mode).
Note that this works with the `cmd` shell, but I think Powershell still has a mind of its own and sometimes tries to convert binary data to unicode...
