### ISSUE TITLE
mp4hls No JSON object could be decoded - mp42hls problem

### ISSUE THREAD

**Issue by dbpaul** [axiomatic-systems/Bento4#480]
Bento4-SDK-1-5-1-629.x86_64-unknown-linux

**mp4hls --debug --verbose sample-1080p.mp4** 
Parsing media file sample-1080p.mp4
Processing MP4 file sample-1080p.mp4
  found 7 segments
COMMAND:  /utils/../bin/mp4info --fast --format json sample-1080p.mp4 ['/utils/../bin/mp4info', '--fast', '--format', 'json', 'sample-1080p.mp4']
COMMAND:  /utils/../bin/mp4dump --verbosity 1 --format json sample-1080p.mp4 ['/utils/../bin/mp4dump', '--verbosity', '1', '--format', 'json', 'sample-1080p.mp4']
.
.
.

Processing sample-1080p.mp4
COMMAND:  /utils/../bin/mp42hls --hls-version 4 --iframe-index-filename output/media-1/iframes.m3u8 --show-info --segment-url-template segment-%d.ts --segment-filename-template output/media-1/segment-%d.ts --index-filename output/media-1/stream.m3u8 --encryption-key-uri key.bin sample-1080p.mp4 ['/utils/../bin/mp42hls', '--hls-version', '4', '--iframe-index-filename', 'output/media-1/iframes.m3u8', '--show-info', '--segment-url-template', 'segment-%d.ts', '--segment-filename-template', 'output/media-1/segment-%d.ts', '--index-filename', 'output/media-1/stream.m3u8', '--encryption-key-uri', 'key.bin', 'sample-1080p.mp4']
Traceback (most recent call last):
  File "/bin/../utils/mp4-hls.py", line 652, in <module>
    main()
  File "/bin/../utils/mp4-hls.py", line 642, in main
    OutputHls(options, media_sources)
  File "/bin/../utils/mp4-hls.py", line 307, in OutputHls
    ProcessSource(options, media_info, out_dir)
  File "/bin/../utils/mp4-hls.py", line 236, in ProcessSource
    media_info['info'] = json.loads(json_info, strict=False)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
**ValueError: No JSON object could be decoded**

**mp42hls --hls-version 4 --iframe-index-filename output/media-1/iframes.m3u8 --show-info --segment-url-template segment-%d.ts --segment-filename-template output/media-1/segment-%d.ts --index-filename output/media-1/stream.m3u8 --encryption-key-uri key.bin sample-1080p.mp4**
{
  "stats": {
    "duration": 25.280000,
    "avg_segment_bitrate": 1428024.126984,
    "max_segment_bitrate": 1599446.153846,
    "avg_iframe_bitrate": 54788.571429,
    "max_iframe_bitrate": 87058.461538,
    **"frame_rate": -nan**
  },
  "audio": {
    "codec": "mp4a.40.2"
  },
  "video": {
    "codec": "avc1.64001E",
    "width": 720,
    "height": 480
  }
}

**Comment by barbibulle** [comment]
A fix for this has been pushed to master, but I haven't made a binary release since. I'll try to push one out today.
