### ISSUE TITLE
mp4dash --hls will cause error

### ISSUE THREAD

**Issue by keijack** [axiomatic-systems/Bento4#483]
I read the code, I don't know why but at mp4-dash.py line 766, `all_audio_tracks` is commented, and at line 821, `all_audio_tracks` is used. so it cause a `undefined` error. please check.

**Comment by krzemienski** [comment]
If you see the other issues posted it’s recommended to use the python3 branch for the time being which doesn’t have this issue

**Comment by barbibulle** [comment]
I have merged the python3 branch to master, and python3 is the default from now on. Can you try with the latest release and check that that fixes the issue?
