### ISSUE TITLE
How to create multiple bit rate files using Mp4HLS

### ISSUE THREAD

**Issue by pankaj-v1** [axiomatic-systems/Bento4#487]
i am using mp4hls command inside a Java program to encrypt a video file into .m3u8 format using AES-128 encryption and using single segment file. I need to create multiple bit rates from single video file and then encrypt them using AES-128 bit to create m3u8 file so that i can use adaptive bit rate features of HLS Player. Till now i was using mp4HLS command which was taking a single input file and providing output file. Is there a way through which mp4HLS can take single video file as input and create multiple output directories for multiple bit rates and put encrypted files in those directories alongwith m3u8 and other files.. Or do i need to use combination of tools to first create multiple bit rates files and then use mp4HLS to encrypt them..I am using these encrypted files for streaming..

**Comment by barbibulle** [comment]
For multiple bitrates, you'll need to have one input file per bitrate (a single input file with multiple video tracks at different bitrate isn't really a good/safe option, even if it can be supported, I wouldn't recommend doing that). Once you have one file per bitrate, you can pass the list of files as input to `mp4dash` or `mp4hls`,  which will create an output directory with all the bitrates together (still one per file)
