### ISSUE TITLE
Rebuilding Initialization segment for HEVC stream fails

### ISSUE THREAD

**Issue by symydckhd** [axiomatic-systems/Bento4#488]
I've been trying to rebuild the MOOV / Movie header for an Encrypted stream through bento4, it works fine with AVC context but with HEVC it seems the Codec Private Data doesn't parse correctly it seems and the hvcC configuration seems seems to be all wrong. The chroma depth and luma depth are wrong and the Profile Compatibility and Constraint are also incorrect. The codec private data is this `0000000140010C01FFFF01600000030090000003000003009695940900000001420101016000000300900000030000030096A001E020021C596565924C2F01520202020800001F480002EE0040000000014401C172B66240`

I have no issues at all using //AP4_AvccAtom*  with FourCC / AVC1 codec private data, it builds perfectly fine however when using //AP4_HvccAtom* no colour space is added to the stream, it's not visible in mediainfo and neither is the HEVC Profile and Level. Not sure what the issue is but would be great if someone could investigate this?

mp4dumps below

what it should look like aka valid initialization
           [encv] size=8+316
              data_reference_index = 1
              width = 3840
              height = 2160
              compressor = HEVC Coding
              [hvcC] size=8+114
                Configuration Version = 1
                Profile Space = 0
                Profile = Main
                Tier = 0
                Profile Compatibility = 60000000
                Constraint = 900000000000
                Level = 150
                Min Spatial Segmentation = 0
                Parallelism Type = 0
                Chroma Format = 1
                Chroma Depth = 8
                Luma Depth = 8
                Average Frame Rate = 0
                Constant Frame Rate = 0
                Number Of Temporal Layers = 1
                Temporal Id Nested = 1
                NALU Length Size = 4

what the one built with bento4 looks like aka invalid initialization:
            [encv] size=8+279
              data_reference_index = 1
              width = 3840
              height = 2160
              compressor =
              [hvcC] size=8+91
                Configuration Version = 1
                Profile Space = 0
                Profile = Main
                Tier = 0
                Profile Compatibility = c01ffe1
                Constraint = 1840010c01
                Level = 255
                Min Spatial Segmentation = 3841
                Parallelism Type = 0
                Chroma Format = 0
                Chroma Depth = 11
                Luma Depth = 8
                Average Frame Rate = 144
                Constant Frame Rate = 0
                Number Of Temporal Layers = 0
                Temporal Id Nested = 0
                NALU Length Size = 1

mp4info dumps:

valid:
  Sample Description 0
    [ENCRYPTED]
      Coding:         encv
      Scheme Type:    piff
      Scheme Version: 65537
      Scheme URI:
    Coding:      hev1 (H.265)
    Width:       3840
    Height:      2160
    Depth:       24
    HEVC Profile Space:       0
    HEVC Profile:             1 (Main)
    HEVC Profile Compat:      60000000
    HEVC Level:               5.0
    HEVC Tier:                0
    HEVC Chroma Format:       1 (4:2:0)
    HEVC Chroma Bit Depth:    8
    HEVC Luma Bit Depth:      8
    HEVC Average Frame Rate:  0
    HEVC Constant Frame Rate: 0
    HEVC NALU Length Size:    4
    HEVC Sequences:
      {
        Array Completeness=1
        Type=32 (VPS_NUT - Video parameter set)
        40010c01ffff016000000300900000030000030096959409
      }
      {
        Array Completeness=1
        Type=33 (SPS_NUT - Sequence parameter set)
        420101016000000300900000030000030096a001e020021c596565924c2f01520202020800001f480002ee0040
      }
      {
        Array Completeness=1
        Type=34 (PPS_NUT - Picture parameter set)
        4401c172b66240
      }
    Codecs String: hev1.1.6.L150.90

built with bento4 / invalid:

Sample Description 0
    [ENCRYPTED]
      Coding:         encv
      Scheme Type:    piff
      Scheme Version: 65537
      Scheme URI:    
    Coding:      hvc1 (H.265)
    Width:       3840
    Height:      2160
    Depth:       0
    HEVC Profile Space:       0
    HEVC Profile:             1 (Main)
    HEVC Profile Compat:      c01ffe1
    HEVC Level:               8.5
    HEVC Tier:                0
    HEVC Chroma Format:       0 (Monochrome)
    HEVC Chroma Bit Depth:    11
    HEVC Luma Bit Depth:      8
    HEVC Average Frame Rate:  144
    HEVC Constant Frame Rate: 0
    HEVC NALU Length Size:    1
    HEVC Sequences:
    Codecs String: hvc1.1.87FF8030.L255.1840010c01
Thanks

**Comment by barbibulle** [comment]
@symydckhd  I'm curious: did you close this because you no longer have this problem, or some other reason?
