### ISSUE TITLE
[Question] A query on mp4encrypt: Support for SAMPLE-AES

### ISSUE THREAD

**Issue by Brainiarc7** [axiomatic-systems/Bento4#489]
Hello there,

Does the tool `mp4encrypt` support SAMPLE-AES, like its' counterpart `mp42hls`?
I came across [this](https://github.com/axiomatic-systems/Bento4/issues/63) issue where [passing custom fields to mp4encrypt](https://github.com/axiomatic-systems/Bento4/issues/63#issuecomment-257175758) allows for clear lead to be enabled in encrypted mp4s, and I ask if a similar option exists to toggle on SAMPLE-AES via such an option?

Thanks,

Brainiarc7.

**Comment by barbibulle** [comment]
Yes, you can do that with `mp4encrypt`. Use the `--method MPEG-CBCS` option when encrypting. This is also what you get when you use the `--encryption-cenc-scheme=cbcs` option with `mp4dash` when the `--hls` option is also used.

**Comment by Brainiarc7** [comment]
Brilliant, thank you so much!

I'll keep testing and report back on any findings.

**Comment by Brainiarc7** [comment]
On the same note: Can all tracks be explicitly encrypted without having to pass repetitive options such as `--key 1` `--key 2` , etc for each track? 

I tried using the -global-option key:$key:$iv and got the warnings:

```sh
WARNING: track ID 1 will not be encrypted
WARNING: track ID 2 will not be encrypted
```

As the file I'm encrypting has two tracks, 1 and 2 (video and audio respectively).

Can all tracks in a file be encrypted without having to pass their IDs explicitly?
