### ISSUE TITLE
HOWTO: MOV with "cmov" (compressed mov header) ?

### ISSUE THREAD

**Issue by alexbuisson** [axiomatic-systems/Bento4#50]
Hi, I'm looking for a way to explore and extract atom from a MOV/Quicktime file. 
For now the only thing I was able to do with Bento4, was to explore the 1st level (see below). But is there a way to uncompress and parse the "cmov" atom ?

[ftyp] size=8+24
  major_brand = qt
  minor_version = 20050300
  compatible_brand = qt
  compatible_brand =
  compatible_brand =
  compatible_brand =
[moov] size=8+1447
  [cmov] size=8+1439
[free] size=8+182
[wide] size=8+0
[mdat] size=8+990317

**Comment by barbibulle** [comment]
The runtime doesn't currently support cmov atoms. Those are quite quicktime-specific, so they're not used in "normal" MP4 files. It wouldn't be a big deal to support them, but doing so would introduce a dependency on a decompression library (zlib or equivalent), which would hurt portability. You can always do this externally from the library, by just getting the payload of the 'cmov' atom and decompressing it yourself.
