### ISSUE TITLE
Version 606 fails to execute due to missing BIN folder in UTILS

### ISSUE THREAD

**Issue by richardbushell** [axiomatic-systems/Bento4#51]
Hi Gilles
Just downloaded v606 to try from the Bento4 website, but mp4-dash.py execution fails (Windows).
I presume the BIN directory should be in the UTILS folder as in previous builds I have seen, but for some reason this is missing.
Can we just copy these missing exes from the other BIN folder in the root, or are these different in any way?
Maybe need to check the build process to see if something has changed as to why these are missing.
Please advise.

**Comment by richardbushell** [comment]
I have tried copying the binaries into utils/bin/win32 folder, and it's still not finding the exes.
I don't program in Python, but have you changed anything in the mp4-dash.py file that may be causing it to not find the binaries?

**Comment by richardbushell** [comment]
I note that Line 888 of mp4-dash.py states:
if not path.exists(options.exec_dir):
        PrintErrorAndExit('Executable directory does not exist ('+Options.exec_dir+'), use --exec-dir')
BUT should this be:
if not path.exists(Options.exec_dir):
this seems to have changed from a previous version we have archived.
Is this the cause?

**Comment by barbibulle** [comment]
Sorry for that. This latest release broke the executable search support on the Windows platform. This will be fixed and updated later today or tomorrow.
