### ISSUE TITLE
Big files results in OOM

### ISSUE THREAD

**Issue by willkk** [axiomatic-systems/Bento4#513]
I have doubt in bento4's memory recycling.
See the graph of machine:
![image](https://user-images.githubusercontent.com/17777977/82627363-d8e31700-9c1c-11ea-9098-6cc84581ec54.png)
The machine's memory became full since 14:30, and it lasted a few hours. 
As I know, several tasks with big source files were executed.

And I check the code here, it seems the tasks are processed in sequence. 
https://github.com/axiomatic-systems/Bento4/blob/86f86fb268a4fb9a46d1970931586ef92785e180/Source/Python/utils/mp4-hls.py#L259

Relative code:
```python
    for media_source in mp4_sources:
        ...
        # process the source
        out_dir = path.join(options.output_dir, media_info['dir'])
        MakeNewDir(out_dir)
        ProcessSource(options, media_info, out_dir)
        ...

        main_media.append(media_info)
```
So , when is the memory recycled?(Not quite familiar with python)

**Comment by barbibulle** [comment]
The `mp4-hls.py` python script will process just one set of inputs at a time (where a set is one or more audio/video files that belong to the same stream, so just one for single-bitrate, maybe a handful for multi-bitrate). Once the output has been created, the process exits and the memory can be reclaimed. That shouldn't take long, and it is mostly disk-bound. Maybe a few seconds to a few minutes depending on whether you encrypt or not. Definitely not something that will last a few hours like on that graph. Did you encounter a case where `mp4-hls.py` was running for a long time?

**Comment by willkk** [comment]
Ok. I will test this.
