### ISSUE TITLE
Bento4 mp4dash  to encrypt Dolby Vision MP4 video with Playready does not play

### ISSUE THREAD

**Issue by btran256** [axiomatic-systems/Bento4#517]
I use mp4dash to encrypt my MP4 Dolby Vision video with Playready. The video cannot play because the payload data at the "mdat" box is bad. The first 4 bytes of the payload data is supposed to be the size of the payload. Currently the size number is too big so the data got rejected.
When I use mp4dash with MP4 video without Dolby Vision and encrypt with Playready, video can play fine. The data at the box "mdat" is good, the first 4 bytes of the data has the correct size.

So I have to conclude that may be mp4dash does not work correctly with Dolby Vision + Playready.

**Comment by barbibulle** [comment]
Is your video larger than 4GB? In that case, the `mdat` box should use the 'long' form, which the tools should do automatically for you. Can you share the output of `mp4dump` for the file that doesn't play?

**Comment by btran256** [comment]
Hi Gilles,

Thanks for your reply.
I have attached the mp4dump output.
My MP4 video file is 427984124 bytes  which is less than 4GB.
My code tries to read and send  the data at “mdat” but it does not think data is correct. May be the data at “mdat” got encrypted by mistake?

Best regards

**Comment by barbibulle** [comment]
The `mdat` atoms here look fine. If `mp4dump` was able to show you all the fragments (each fragment has its own `mdat`), it means the `mdat` atom sizes are correct. If they were not, `mp4dump` wouldn't be able to continue to the next fragment.

**Comment by btran256** [comment]
Hi Gilles

Thanks for looking at my problem.

I have attached a hexdump of the MP4 file and some explanation, you will see what my problem is.


Thanks


________________________________

**Comment by barbibulle** [comment]
The size of an atom appear before the atom type. Here, the size of `mdat` in the Dolby Vision example is `00  03 9e 3b` (237115 bytes) and `01 06 91 e2` (17207778 bytes) without Dolby Vision.

**Comment by btran256** [comment]
Hi Gilles,

I think the size I have problem with is the size of the frame to be sent.

The size you refer to is the size of the mdat box. The mdat box  has many frames inside, each frame has different size.

If you look at the hex dump, for the  Non-DolbyVision Playready file:

01 06 91 e2    (size of mdat)
6d 64 61 74     ("mdat")
00 00 00 06      (size of frame to be sent)
4e 01 81 01 0f 80  (bytes to be sent, number of bytes is equal to size above)
00 00  00 10      (size of frame to be sent)
4e 01 00 06 80 0a  fc 78 00 06 01 03 04 00  07 80  (bytes to be sent)
............ (more frames)

Now look at DolbyVision+Playready hex dump:

00  03 9e 3b  (size of mdat)
6d 64 61 74    ("mdat")
69 de 77 02    (size of frame to be sent,  number is too big, my code will reject this frame)





________________________________

**Comment by btran256** [comment]
HI Gilles,

I have attached another document showing the hexdump content of the same Dolby Vision file which is not encrypted. If you compare with  the same Dolby Vision file +PLayready , you will see  that the unencrypted file has good data in the box "mdat".


You can find MP4 video with Dolby Vision at this link:

https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/


If you can use "mp4dash" to encrypt the Dolby Vision video, it will help.

If you can play the file with your player then it means that I did something wrong.

If you cannot play the file then we are seeing the same problem.


I am using  Bento 4 version Bento4-SDK-1-6-0-634.x86_64


Thanks


________________________________

**Comment by barbibulle** [comment]
I now understand what you mean. What you're referring to here are the NAL units that are part of the video data. NAL units have a `size` prefix followed by some type information and a payload. The `size` may be encoded with 1, 2 or 4 bytes. In your case here, a 4-byte NAL unit size encoding is used.
The problem you're seeing is that `mp4encrypt`, unfortunately, doesn't detect Dolby Vision as being NAL-unit based, so it is encrypting the entire data payload, not as a sequence of NAL units (in which case the NAL unit headers would be left in the clear).
I have fixed that now, so that Dolby Vision is properly detected when encrypting, and thus will be encrypted like other NAL-unit based formats.
I'll push a new pre-compiled build soon. In the meantime, you can try it by building from source

**Comment by barbibulle** [comment]
The updated code is already on the master branch on GitHub. For the pre-compiled binaries, they'll be at the usual location: https://www.bento4.com/downloads/  soon (it will be Version 1.6.0-636 or later)

**Comment by btran256** [comment]
HI Gilles,

I tried the new Bento4 version 636 that you just changed.

It looks like command "mp4dash" is working differently now.

"mp4dash" used to split the MP4 video  into audio file and video file. Now I only see video file, there is no audio file.

Please check


Thanks


________________________________

**Comment by barbibulle** [comment]
`mp4dash` should work exactly the same as before. Can you run `mp4dash` with the `-d` and  `-v` options and share the output?

**Comment by btran256** [comment]
Hi Gilles,

Below is output of "mp4dash" for Bento4 version 636.

As you can see, only "video" sub-directory is generated in the "output" directory, there is no "audio" sub-directory.

I used Bento4_SDK-1-6-0-634 before, it gave me both audio and video directory.


Thanks


==============================


 ./bin/mp4dash --use-segment-list --use-segment-timeline  --encryption-key=09e367028f33436ca5dd60ffe6671e70:#XVBovsmzhP9gRIZxWfFta3VVRPzVEWmJsazEJ46I --playready --playready-header=LA_URL:http://test.playready.microsoft.com/service/rightsmanager.asmx -d -v  Dolby-OnOff-DolbyVision@24fps-fragmented.mp4


Profiles: urn:mpeg:dash:profile:isoff-live:2011
COMMAND:  /home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/utils/../bin/mp4info --format json --fast Dolby-OnOff-DolbyVision@24fps-fragmented.mp4 ['/home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/utils/../bin/mp4info', '--format', 'json', '--fast', 'Dolby-OnOff-DolbyVision@24fps-fragmented.mp4']
PlayReady Derived Key = b42ca3172ee4e69bf51848a59db9cd13
Encrypting track IDs [1] in Dolby-OnOff-DolbyVision@24fps-fragmented.mp4
COMMAND:  /home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/utils/../bin/mp4encrypt Dolby-OnOff-DolbyVision@24fps-fragmented.mp4 /home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/output/tmpijez0x96 --method MPEG-CENC --global-option mpeg-cenc.piff-compatible:true --key 1:b42ca3172ee4e69bf51848a59db9cd13:random --property 1:KID:09e367028f33436ca5dd60ffe6671e70 --pssh 9a04f07998404286ab92e65be0885f95:/home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/output/tmpzwmkdpvu ['/home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/utils/../bin/mp4encrypt', 'Dolby-OnOff-DolbyVision@24fps-fragmented.mp4', '/home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/output/tmpijez0x96', '--method', 'MPEG-CENC', '--global-option', 'mpeg-cenc.piff-compatible:true', '--key', '1:b42ca3172ee4e69bf51848a59db9cd13:random', '--property', '1:KID:09e367028f33436ca5dd60ffe6671e70', '--pssh', '9a04f07998404286ab92e65be0885f95:/home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/output/tmpzwmkdpvu']
Parsing media file 1: tmpijez0x96 = Encrypted[Dolby-OnOff-DolbyVision@24fps-fragmented.mp4]
Processing MP4 file /home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/output/tmpijez0x96
  found 63 segments
COMMAND:  /home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/utils/../bin/mp4dump --format json --verbosity 1 /home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/output/tmpijez0x96 ['/home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/utils/../bin/mp4dump', '--format', 'json', '--verbosity', '1', '/home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/output/tmpijez0x96']
Track ID                     = 1
    Segment Count            = 63
    Type                     = video
    Sample Count             = 2997
    Average segment bitrate  = 27396475
    Max segment bitrate      = 41396013
    Required bandwidth       = 28864634
    Average segment duration = 1.9896926229508183
Audio: {}
Video: {('video', 'dvhe'): [File 1#1]}
Subtitles: {}
Key info for File 1#1: [KID=09e367028f33436ca5dd60ffe6671e70, KEY=b42ca3172ee4e69bf51848a59db9cd13]
video track: File 1#1 - language=und, max bitrate=41396013, avg bitrate=27396475, req bandwidth=28864634, codec=dvhe.05.06
Splitting media file (video) tmpijez0x96 = Encrypted[Dolby-OnOff-DolbyVision@24fps-fragmented.mp4]
COMMAND:  /home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/utils/../bin/mp4split --track-id 1 --pattern-parameters N --start-number 1 --init-segment output/video/dvhe/init.mp4 --media-segment output/video/dvhe/seg-%llu.m4s /home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/output/tmpijez0x96 ['/home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/utils/../bin/mp4split', '--track-id', '1', '--pattern-parameters', 'N', '--start-number', '1', '--init-segment', 'output/video/dvhe/init.mp4', '--media-segment', 'output/video/dvhe/seg-%llu.m4s', '/home/brian/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux/output/tmpijez0x96']
brian@brian-Aspire-5552:~/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux$



brian@brian-Aspire-5552:~/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux$ ls
bin                                           lib
docs                                          output
Dolby-OnOff-DolbyVision@24fps-fragmented.mp4  output_DolbyOnOff
Dolby-OnOff-DolbyVision@24fps.mp4             utils
include
brian@brian-Aspire-5552:~/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux$ ls output
stream.mpd  video
brian@brian-Aspire-5552:~/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux$ ls output/video
dvhe
brian@brian-Aspire-5552:~/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux$ ls output/video/dvhe
init.mp4    seg-1.m4s   seg-2.m4s   seg-3.m4s   seg-4.m4s   seg-5.m4s
seg-10.m4s  seg-20.m4s  seg-30.m4s  seg-40.m4s  seg-50.m4s  seg-60.m4s
seg-11.m4s  seg-21.m4s  seg-31.m4s  seg-41.m4s  seg-51.m4s  seg-61.m4s
seg-12.m4s  seg-22.m4s  seg-32.m4s  seg-42.m4s  seg-52.m4s  seg-62.m4s
seg-13.m4s  seg-23.m4s  seg-33.m4s  seg-43.m4s  seg-53.m4s  seg-63.m4s
seg-14.m4s  seg-24.m4s  seg-34.m4s  seg-44.m4s  seg-54.m4s  seg-6.m4s
seg-15.m4s  seg-25.m4s  seg-35.m4s  seg-45.m4s  seg-55.m4s  seg-7.m4s
seg-16.m4s  seg-26.m4s  seg-36.m4s  seg-46.m4s  seg-56.m4s  seg-8.m4s
seg-17.m4s  seg-27.m4s  seg-37.m4s  seg-47.m4s  seg-57.m4s  seg-9.m4s
seg-18.m4s  seg-28.m4s  seg-38.m4s  seg-48.m4s  seg-58.m4s
seg-19.m4s  seg-29.m4s  seg-39.m4s  seg-49.m4s  seg-59.m4s
brian@brian-Aspire-5552:~/test_Bento4_SDK-1-6-0-636/Bento4-SDK-1-6-0-636.x86_64-unknown-linux$



________________________________

**Comment by barbibulle** [comment]
From the output here it looks like there's no audio track in your input file. Can you share the output of `mp4info` and `mp4dump` with the same file?

**Comment by btran256** [comment]
Hi Gilles,

I have attached the mp4info and mp4dump of the original DolbyVision file (not encrypted) and the Dolby Vision fragmented file (generated by "mp4fragment" from original unencrypted file).


I can see the problem:  the original file shows 2 tracks (video and audio) but the fragmented file shows only 1 video track. It looks like this is a bug with "mp4fragment".


Thanks


________________________________

**Comment by barbibulle** [comment]
While fixing a potential overflow issue found by a fuzzer (issue #511 ) , I introduced a bug where files with constant-size audio samples were not handled correctly anymore.

**Comment by btran256** [comment]
Hi Gilles,


I still have problems playing the Dolby Vision Playready video.

My code still has problem parsing the Dolby Vision Playready file generated by mp4dash.

It looks like the number of subsamples is 2  which is giving me problem, video cannot play.


On a non-DolbyVision file, the mp4dash command with Playready gives me a file with number of subsamples=1, the video plays fine.

I do not understand this "subsample" well. Do you have any documents on this?


Thanks


________________________________
