### ISSUE TITLE
mp4 decrypt error

### ISSUE THREAD

**Issue by forty875** [axiomatic-systems/Bento4#522]
I am trying to decrypt an mp4 file. When using mp4decrypt i get pixel/frame errors but it seems mp4box decrypts the file correctly.
**xml for decrypting with mp4box:**
```
<?xml version="1.0" encoding="UTF-8" ?>
<GPACDRM type="cbcs">
<CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x0eae03b3c9c43e0f29c81da04d619e85" saiSavedBox="senc">
<key KID="0x00000000000000000000000000000000" value="0x4541b680b07db1fd3f8256a141aa100b"/>
</CrypTrack>
</GPACDRM>
```
**Here is the test file:** https://www.file-upload.net/download-14136548/encrypted.mp4.html

**Comment by barbibulle** [comment]
Would it be possible to post a link to the original (prior to encryption) file, so that I can compare the decrypted result and the expected data?

**Comment by forty875** [comment]
@barbibulle
Sry i only have the encrypted mp4 segments...

**Comment by barbibulle** [comment]
What about the decrypted output from mp4box?

**Comment by forty875** [comment]
@barbibulle 
Decrypt yourself with mp4box decrypt key is inside the xml file

**Comment by barbibulle** [comment]
Ok. Do you know which tool was used to encrypt the file?

**Comment by barbibulle** [comment]
Issue found: one of the sample sizes was not computed correctly (the encrypted file has an unusual way of using the default sample size feature of the format).
The issue is fixed in master, and I will push a new set of precompiled binaries shortly.
