### ISSUE TITLE
Tag r637

### ISSUE THREAD

**Issue by jimmymic** [axiomatic-systems/Bento4#528]
Hi Giles,

Missing a tag for r637 on the source which has quite an important fix for the sample count not being calculated correctly.

We had mistakenly been using r636 as the latest available tag but were striking the sample count issue - interestingly not for encrypted files. 

Issue was fixed in r637

Thanks,

James

**Comment by barbibulle** [comment]
Sorry about that. I have now pushed the tag.

**Comment by jimmymic** [comment]
Thanks
