### ISSUE TITLE
mp4decrypt decrypts audio on windows but not on linux

### ISSUE THREAD

**Issue by abellybeer** [axiomatic-systems/Bento4#538]
Hi, I am having similar issue like this post here 
https://github.com/axiomatic-systems/Bento4/issues/450

I can decrypt video with key in format 1:key and kid:key and audio only decrypts with kid:key(windows).

When I try replicate the same on ubuntu 18 the audio doesn’t decrypt.

I already tried downloading latest code from this repo and building it but it just doesn’t work.

I followed these steps
git clone 
mkdir cmakebuild
cd cmakebuild
cmake -DCMAKE_BUILD_TYPE=Release ..
make

Then tried decrypting using the binary I just compiled. Maybe I am using the wrong binary or doing something wrong?

I am suprised it works on windows and not on ubuntu 18.04.

Any guesses?

**Comment by barbibulle** [comment]
Would it be possible to share the exact command line you're using, and possible a sample encrypted file, so that I can try to replicate this (I'm not able to replicate this problem when I encrypt/decrypt files)

**Comment by abellybeer** [comment]
I redownload the binaries from bento4.com and now its working.

Thank you for your answer @barbibulle
