### ISSUE TITLE
Track bypass from input file to output file 

### ISSUE THREAD

**Issue by alexbuisson** [axiomatic-systems/Bento4#55]
Hi, I would implement a complete pass through of a Track from 1 input file to a file I create. It could be an audio track or a time code track, in fact I don't know if it really matter, but for now every try I made with the Bento4 API failed ?
Is it possible ? 
if 'yes', I could share my current implementation, but it can be summarize by the following step:

1) Open the input file (using `input` bitstream) and locate a specific track atom
````
AP4_TrakAtom* newTrakAtom = AP4_DYNAMIC_CAST(AP4_TrakAtom, track_atom);
````
2) Add a track to an AP4_Movie instance using the AP4_Track copy constructor in which we pass the track atom and the `input` bitstream.
```
result = movie->AddTrack(new AP4_Track(*newTrakAtom, *input, movie->GetTimeScale()));
````
3) Write a MP4 output file

**Comment by barbibulle** [comment]
You can do what you need, but there are a few cases to consider, because they will differ in how the output is created. For example, creating fragmented and non-fragmented MP4 files is different.
The Bento4 runtime includes a convenience class to do this type of input->output processing, in a way that preserves as much of the original structure as possible (i.e if your input is fragmented, the output will be as well, etc.). That class is the AP4_Processor class. For example, the mp4encrypt application uses that class, implementing a custom sub-class of AP4_Processor that will encrypt the samples from input to output. In your case, you can simply create your own AP4_Processor subclass that will just be responsible for removing the tracks you don't want in the output. The rest will be copied as-is.

**Comment by alexbuisson** [comment]
Thank you for your answer, 
I followed your advice and I was able to write a kind of "track" remover based on the MP4Edit sample. But after how can I add the new track ?

```
// find the position of the atom in the parent
        AP4_AtomParent* parent = atom->GetParent();
        int position = 0;
        AP4_List<AP4_Atom>::Item* list_item = parent->GetChildren().FirstItem();
        while (list_item) {
            if (list_item->GetData() == atom) break;
            position++;
            list_item = list_item->GetNext();
        }

        // remove the atom from the parent
        atom->Detach();
        delete atom;
```
I suppose that calling `result = parent->AddChild(new_track->GetTrakAtom(), position);` is not enough :)
In fact it leads to a crash in `AP4_StssAtom::IsSampleSync`

Have you another good idea ?

**Comment by alexbuisson** [comment]
Hi,
Finally I found an approach working fine ... I added below a pseudo-code

```
boost::shared_ptr<AP4_ByteStream> input(AP4_FileByteStream_Create (fileNameIn.c_str(), AP4_FileByteStream::STREAM_MODE_READ, logger), AP4_InstanceReleaser<AP4_ByteStream>());
AP4_File input_file (*input, AP4_DefaultAtomFactory::Instance, true);
///////////////////////////////////////////////////////////
// by-pass some original video track atom (edts/elst, tref)
AP4_Track* VideoTrack = input_file.GetMovie()->GetTrack(VideoTrackIds[0].first);
AP4_Atom* edtsAtom=FindAtom(VideoTrack->GetTrakAtom(), AP4_ATOM_TYPE('e','d','t','s'), logger);
if(edtsAtom)
{
  edtsAtom = edtsAtom->Clone();
  result = AP4_DYNAMIC_CAST(AP4_AtomParent, track->GetTrakAtom())->AddChild(edtsAtom);
}
AP4_Atom* trefAtom=FindAtom(VideoTrack->GetTrakAtom(), AP4_ATOM_TYPE('t','r','e','f'), logger);
if(trefAtom)
{
  trefAtom = trefAtom->Clone();
  result = AP4_DYNAMIC_CAST(AP4_AtomParent, track->GetTrakAtom())->AddChild(trefAtom);
}
///////////////////////////////////////////////////////////
result = RemoveTrack(input_file.GetMovie(), VideoTrackIds[0].first, logger);

track->SetId(VideoTrackIds[0].first);
result = input_file.GetMovie()->AddTrack(track, VideoTrackIds[0].second);

// Create output bytestream
boost::shared_ptr<AP4_ByteStream> output(AP4_FileByteStream_Create (mp4File.c_str(), AP4_FileByteStream::STREAM_MODE_WRITE, logger), AP4_InstanceReleaser<AP4_ByteStream>());
result = AP4_FileWriter::Write(input_file, *output);
```
