### ISSUE TITLE
Audio decryption problem

### ISSUE THREAD

**Issue by bkod7** [axiomatic-systems/Bento4#569]
I'm trying to decrypt audio and it's not working. Video worked smoothly but the audio isn't somehow.

Used the video key + the KID key. Any idea?

**Comment by lfaureyt** [comment]
Could you post the URLs to your audio init and segment data ?

**Comment by bkod7** [comment]
Its from Amazon, video encrypted well, but the audio is silent(if not its still decrypted) 

Used this command for audio: mp4decrypt --key kid:key raw.m4a audio.m4a

**Comment by barbibulle** [comment]
It is possible that the audio and video tracks are encrypted with different keys. Do they have the same KIDs?
You can also try `mp4decrypt` with `--key <track-id>:<key>` instead of `--key <kid>:<key>` just to be sure.
