### ISSUE TITLE
some h264 to mp4 bad video

### ISSUE THREAD

**Issue by supperlitt** [axiomatic-systems/Bento4#57]
I use ffmpeg args to h264 to mp4 not bad,but use bento4 has it.
the extend h264file.
http://pan.baidu.com/s/1nuxQhaL

**Comment by barbibulle** [comment]
I don't quite understand the issue you are describing. Can you provide a more detailed description of the problem?

**Comment by supperlitt** [comment]
yeah,the question is I have a h264 file in up underline,I used bento4 mp4mux to change it to mp4, the result file have bad screen,but i used ffmpeg to change it ,the result mp4 is not bad.

**Comment by supperlitt** [comment]
I got it.i take the file but is a ps file.so can't make to mp4.sorry.

**Comment by supperlitt** [comment]
I thank error.
