### ISSUE TITLE
mp4decrypt wont decrypt this video

### ISSUE THREAD

**Issue by realn3rd** [axiomatic-systems/Bento4#570]
I am trying to download and decode this video. I have the right key for this.

https://vodnowusoawsdash.secure.footprint.net/proxy11012/manifest/tvnow/3901103-2/0.ism/.mpd
Key: 875f6cb415d8b567131d78c3faa99273 (KID=25a7a66dbccf5e6418e1d26aaa29c6bc)

Unfortunately, I have not had any success with it so far.

I have taken these steps, but the end result is an unplayable video file.

Step 1: Download

ffmpeg -i https://vodnowusoawsdash.secure.footprint.net/proxy11012/manifest/tvnow/3901103-2/0.ism/.mpd -acodec copy -vcodec copy video_encrypted.mp4

Step 2: Decrypt

mp4decrypt --key 25a7a66dbccf5e6418e1d26aaa29c6bc:875f6cb415d8b567131d78c3faa99273 video_encrypted.mp4 video_decrypted.mp4

What am I doing wrong?

Or do I have to decode the segments individually and only then can I assemble them into a video with FFmpeg?

**Comment by PlaceboPRS** [comment]
I think you have the key wrong, have you written the Keyid and key? You only need two write it like "1:key" I believe, so for your example:

mp4decrypt --key 1:875f6cb415d8b567131d78c3faa99273 video_encrypted.mp4 video_decrypted.mp4

If 875f6cb415d8b567131d78c3faa99273  is the key

Your post with the correct commands/formatting helped me figure it out myself as I'd only stumbled on the whole "process" yesterday, so thanks for that! :)

**Comment by realn3rd** [comment]
mp4decrypt --key 1:875f6cb415d8b567131d78c3faa99273 video_encrypted.mp4 video_decrypted.mp4

The command works for me.

The trick is to merge the segments with cat and then decrypt the video and audio separately, then merge everything with FFmpeg.
