### ISSUE TITLE
cannot decrypt ismv file

### ISSUE THREAD

**Issue by m0ck69** [axiomatic-systems/Bento4#585]
Hi.
I cannot decrypt ismv file.
I have no problems with mp4, ts etc.
Are ismv files any different from others?

Example:
[video.zip](https://github.com/axiomatic-systems/Bento4/files/6074766/video.zip)

```
key:c739f6a4fea79481ea20144756be335c
KID=5196291eebc145c5ac79f458502b2932
```

**Comment by p2mgrup** [comment]
how do you decrypt ts file?

**Comment by barbibulle** [comment]
ismv files use the MP4 format, so they work exactly the same.
But the video.ismv file you're pointing to here is either not encrypted, or is encrypted but without proper signaling. An encrypted ismv/mp4 file has its sample description 'wrapped' in an `encv` box (child of the `stsd` box), which isn't the case for your file. You can check with `mp4dump` or `mp4info` (when a file is encrypted and signaled properly, `mp4info` will show that it is encrypted).
