### ISSUE TITLE
🚨 Potential NULL Pointer Dereference

### ISSUE THREAD

**Issue by huntr-helper** [axiomatic-systems/Bento4#605]
👋 Hello, @barbibulle, @dimitry-ishenko, @haridarshan - a potential medium severity NULL Pointer Dereference vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/2-other-axiomatic-systems/Bento4** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by huntr-helper** [comment]
📦 A patch has been submitted for this report. 🔗 Check the patch (https://github.com/axiomatic-systems/Bento4/compare/HEAD...dimitry-ishenko:issue-605) or visit the advisory page (https://huntr.dev/bounties/2-other-axiomatic-systems/Bento4) for more information.

**Comment by huntr-helper** [comment]
📦 A patch has been submitted for this report. 🔗 Check the patch (https://github.com/axiomatic-systems/Bento4/compare/HEAD...dimitry-ishenko:issue-605) or visit the advisory page (https://huntr.dev/bounties/2-other-axiomatic-systems/Bento4) for more information.

**Comment by dimitry-ishenko** [comment]
@barbibulle I've already submitted PR #607 to fix this.

**Comment by barbibulle** [comment]
Thanks Dimitry. I've merged #607 now.
