### ISSUE TITLE
troubleshooting cbcs mp4 audio

### ISSUE THREAD

**Issue by cstranex** [axiomatic-systems/Bento4#613]
I am generating audio-only fmp4 files for playback on the web with DRM and hoping to support both Widevine and FairPlay however I am having trouble getting cbcs encryption scheme to work:

I prepare the mp4 file as follows:
```
ffmpeg -y -i SOURCE -map 0:a:0 -ac 2 -c:a aac -b:a 128k -movflags default_base_moof+empty_moov+faststart -map_metadata -1 -frag_duration 2000000 -f mp4 TRANSCODED.mp4
```

And then feed it into mp4dash:
```
mp4dash --no-split --force --hls --hls-master-playlist-name=gYFzjPBgaRg_master.m3u8 --hls-media-playlist-name=gYFzjPBgaRg.m3u8 --encryption-cenc-scheme=cbcs --encryption-key=KID:KEY:IV --eme-signaling=pssh-v1 --widevine --widevine-header="provider:intertrust#content_id:2a" ./TRANSCODED.mp4 --output-dir output
```

Using the cenc protection scheme works perfectly on Chrome, however changing to cbcs results in a decode error. Interestingly Chrome reports this in the debug logs:
```
Selected FFmpegAudioDecoder for audio decoding, config: codec: aac, profile: unknown, bytes_per_channel: 4, channel_layout: STEREO, channels: 2, samples_per_second: 44100, sample_format: Float 32-bit planar, bytes_per_frame: 8, seek_preroll: 0us, codec_delay: 0, has extra data: true, encryption scheme: Unencrypted, discard decoder delay: true
FFmpegDemuxer: av_read_frame(): Invalid data found when processing input
```

There doesn't seem to be any clear lead in the resulting file, at least if I try play it with ffplay directly it complains about `Incorrect number of samples in encryption info`.

Running `mp4info` I can see that it does describe the encryption correctly:
```
File:
  major brand:      iso5
  minor version:    200
  compatible brand: iso5
  compatible brand: iso6
  compatible brand: mp41
  fast start:       yes

Movie:
  duration:   0 (media timescale units)
  duration:   0 (ms)
  time scale: 1000
  fragments:  yes

Found 1 Tracks
Track 1:
  flags:        3 ENABLED IN-MOVIE
  id:           1
  type:         Audio
  duration: 0 ms
  language: und
  media:
    sample count: 0
    timescale:    44100
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 128.827 Kbps
    sample count with fragments: 8053
    duration with fragments:     8245888
    duration with fragments:     186982 (ms)
  Sample Description 0
    [ENCRYPTED]
      Coding:         enca
      Scheme Type:    cbcs
      Scheme Version: 65536
      Scheme URI:     
    Coding:       mp4a (MPEG-4 Audio)
    Codec String: mp4a.40.2
    Stream Type: Audio
    Object Type: MPEG-4 Audio
    Max Bitrate: 128000
    Avg Bitrate: 0
    Buffer Size: 0
    MPEG-4 Audio Object Type: 2 (AAC Low Complexity)
    MPEG-4 Audio Decoder Config:
      Sampling Frequency: 44100
      Channels: 2
      Extension:
        Object Type: Spectral Band Replication
        SBR Present: no
        PS Present:  no
        Sampling Frequency: 0
    Sample Rate: 44100
    Sample Size: 16
    Channels:    2
```

**Comment by barbibulle** [comment]
I can try to reproduce this to see what may be going on. What player are you using in Chrome to test? (something like the Shaka Player lib, dash.js, something else?)

**Comment by cstranex** [comment]
Hi @barbibulle 

I realised I didn't clarify in the issue above, I am trying to play the resulting mp4 directly instead of using a manifest since ultimately these particular files would be stored locally rather than streamed.

I have tried directly with EME and also using Shaka. If I swap to using the dash manifest Shaka does play it

**Comment by barbibulle** [comment]
Playing an encrypted file directly, without the assistance of an EME-based library, isn't going to work, because the browser has no way to get the decryption key by itself. The browser's media engine can see that the media is encrypted, but doesn't have the information (and typically even the logic) to contact the DRM server, via a DRM client library, to obtain the decryption key(s).

**Comment by cstranex** [comment]
Yes, I don't expect the browser to work without EME :)
The simplified process:
```
const node = new Audio();
const keySystem = await navigator.requestMediaKeySystemAccess('com.widevine.alpha', [{
    {
      initDataTypes: ['cenc'],
      videoCapabilities: [],
      audioCapabilities: [{contentType: 'audio/mp4; codecs="mp4a.40.2"'}],
   }
}]);
node.setMediaKeys(keySystem);
node.addEventListener('encrypted', (e) => { /* ... handle creating media key sessions, and performing license requests, etc. */  });
playFile('https://....../asset.mp4'); // Creates a media source and feeds the contents of the file to the audio element via a source buffer
```

The above does work fine if I create the mp4 using the cenc encryption scheme but as soon as I change to cbcs it fails.

Using shaka player I can play the cbcs file using the manifest created by mp4dash but the goal is to avoid the manifest if possible. Since I am able to do the playback with the cenc file I am guessing it is either a limitation of the browser or a signalling issue in the mp4

**Comment by cstranex** [comment]
It turns out it was a browser issue (specifically on older versions of Chrome when using cbcs of which some of our test devices are running). The shaka player working with the manifest was a red herring since I was testing that locally with the most recent version of Chrome.
