### ISSUE TITLE
Building/Deploying on macOS

### ISSUE THREAD

**Issue by dg1sek** [axiomatic-systems/Bento4#620]
I want to use mp4-dash tool on macos. 
I manage to build bento4 on Xcode without any issue (thank you for the great work!)
Question, is there an easy way after build to deploy into /Applications or another directory or do I have to manually move all Python scripts and binaries into my own directory hierarchies?
Thanks again for the great work!

**Comment by barbibulle** [comment]
One option is to use the pre-compiled distribution (http://www.bento4.com/downloads/), which has all the executables and scripts that can be run as-is in place. A second easy option, if you want to build from source yourself, is to build the Release config, and then run the SDK packager python script (Scripts/SdkPackager.py), which will create an packaged SDK equivalent to the precompiled distribution.

**Comment by dg1sek** [comment]
Thanks !
