### ISSUE TITLE
mp4dash `--hls-media-playlist-name` and similar params not respected

### ISSUE THREAD

**Issue by jgcaruso** [axiomatic-systems/Bento4#624]
The `--hls-media-playlist-name` and `--hls-iframes-playlist-name` params don't appear to be used to name the playlist files when executing `mp4dash --hls`. From looking through the code it seems like they are only used conditionally (and the condition is when they aren't set or if `options.on_demand` is true - https://github.com/axiomatic-systems/Bento4/blob/4f813a9b791e312761b762fcab4b09e921bee584/Source/Python/utils/mp4-dash.py#L939).

The `--hls-master-playlist-name` is working as expected.

Is there a reason these can't be used all of the time? Also, is it possible to have a param for the audio playlist as well?

It would be nice to be able to generate predictable playlist names when running bento4 in an automated environment.

Incase I'm misinterpreting what those params are supposed to be doing, what I'm asking for is a way to name the `.m3u8` playlists that are generated in the output directory, currently what I'm seeing for `hevc` content is the following:

`video-hvc1.m3u8` (assuming this is the media playlist)
`video-hvc1_iframes.m3u8` (assuming this is the iframes playlist)
`master.m3u8` (master playlist)
`audio-en-mp4a.40.2.m3u8` (would like to also be able to rename the audio playlist)

**Comment by barbibulle** [comment]
The reason `--hls-media-playlist-name` is ignored when using the `on-demand` or `no-split` modes is that in those modes, the media files are all in a single directory, so the tool need to control the names of the playlist files in order to compute unique names for those files (there's one per media stream, they can't all have the same name)

**Comment by jgcaruso** [comment]
Thanks, just wanted to make sure if it was intentional or not before I started working with it.
