### ISSUE TITLE
i have a question the Mp42Ts result .ts file con't play in ios system..

### ISSUE THREAD

**Issue by supperlitt** [axiomatic-systems/Bento4#65]
I need help.

**Comment by barbibulle** [comment]
For HLS, please use mp42hls tool for single files, or the higher level HLS packager mp4hls for multiple bitrates.

**Comment by supperlitt** [comment]
vs2012 not contains ,mp42hls,but vs 2010 have it.

**Comment by supperlitt** [comment]
friends, in fact i want to, use mp4 to ts create the match ios use,ts file...
but i don't know where to start...to use.

**Comment by barbibulle** [comment]
You should be able to convert the vs2010 mp42hls project file into your vs2012 solution (it will automatically be converted). But even simpler, you can download the precompiled version of the tools at http://www.bento4.com

**Comment by supperlitt** [comment]
thanks for your help.
