### ISSUE TITLE
Subtitles with mp4-dash

### ISSUE THREAD

**Issue by Zonimi** [axiomatic-systems/Bento4#667]
Hello, I'm trying to add subtitles in the conversion to fmp4 as follows;

`mp4-dash.py --hls MP4/video.mp4 [+format=webvtt,+language=por]MP4/por.vtt [+format=webvtt,+language=forced]MP4/forced.vtt
`

But I'm getting this error message and no subtitles are added, any solution?

```
Parsing media file 1: MP4/video.mp4
Splitting media file (audio) MP4/video.mp4
Splitting media file (audio) MP4/video.mp4
Splitting media file (video) MP4/video.mp4
Processing and Copying subtitles file MP4/por.vtt
Processing and Copying subtitles file MP4/forced.vtt
ERROR: local variable 'language_name' referenced before assignment
```

**Comment by barbibulle** [comment]
I'm able to reproduce the issue. We'll fix this ASAP.

**Comment by nilmic** [comment]
Probably same as https://github.com/axiomatic-systems/Bento4/issues/659

**Comment by clia6547** [comment]
I'm running version 1.6.0-639 on M2 chip and got the same issue
