### ISSUE TITLE
AC4 audio not supported in mp4hls

### ISSUE THREAD

**Issue by ashiskumarsahu** [axiomatic-systems/Bento4#680]
I am trying to pack a 4K mp4 file with mp4hls tool. Its returning below error 

ERROR: audio codec not supported
ERROR: binary tool failed with error 1

I have used ac4 audio format. Could you please check and share why this is not happening? I used mp4mux to mux ac4 audio which is well supported. For dash generation using mp4dash its working fine as well. But in case of mp4hls its failing.

Appreciate your quick response on this.

Thank You

**Comment by barbibulle** [comment]
There are two "flavors" of HLS: legacy HLS with MPEG2-TS or "packed audio" segments, and interoperable HLS, with fMP4 segments. For the second flavor, you should use the `mp4dash` tool, with the `--hls` option. AC4 with legacy MPEG2-TS/packed audio segments isn't supported at this time. Do you actually need AC4 with legacy MPEG2-TS/packed audio, or would you be able to use the fMP4 format?

**Comment by ashiskumarsahu** [comment]
Hi,
Thanks for reply.
Yes I am able to use fmp4 format.
Thanks for the valuable input. It would be great if mp4hls will support ac4 and upcoming future formats as well.
