### ISSUE TITLE
Bento4#unable to see IV (Initilization Vector value) in manifest

### ISSUE THREAD

**Issue by dhaval02** [axiomatic-systems/Bento4#683]
Please help me with below issue:
Unable to see IV value in manifest file,
Please help me with modifications in below command in bento4 (mp4hls packaging)

/root/bento4/Bento4-SDK-1-6-0-637.x86_64-unknown-linux/bin/mp4hls --hls-version=5 --master-playlist-name=index.m3u8 --encryption-mode=SAMPLE-AES --encryption-iv-mode=fps --encryption-key=248bd83f78dcf7dd4e7b2fa7e9ed32d0773aa50de5174249acf4264e96f78b76 --encryption-key-format=com.apple.streamingkeydelivery --encryption-key-uri=skd://773aa50de5174249acf4264e96f78b76 96p_mp4.mp4 144p_mp4.mp4 240p_mp4.mp4 360p_mp4.mp4 480p_mp4.mp4 576p_mp4.mp4 720lowp_mp4.mp4 720highp_mp4.mp4 1080lowp_mp4.mp4 1080highp_mp4.mp4 -o KundaliBhagya_5/ -f

**Comment by barbibulle** [comment]
That's normal. When you create an HLS output for FairPlay the IV is part of the delivered key material (delivered by the FairPlay server), not included in the playlist.

**Comment by samcurran22** [comment]
Is there any tool available to know VMAF score of Live 24x7 HEVC Stream (HLS and DASH) ?
Please let me know
