### ISSUE TITLE
Support for muxing HEVC files 

### ISSUE THREAD

**Issue by ATrattnig** [axiomatic-systems/Bento4#69]
Is there anything planned to support the muxing of hevc files to mp4 anytime soon? I see there was some work done regarding parsing hevc NALUs. But the tool mp4mux can only handle avc right now.

**Comment by barbibulle** [comment]
Full support for muxing HEVC is scheduled for about 2 weeks from now.

**Comment by ATrattnig** [comment]
I wanted to ask if there are any updates regarding the status of this issue. It would be a great feature to have.

**Comment by barbibulle** [comment]
A first version of this feature has been implemented. A new release will be pushed to the servers later this week.
