### ISSUE TITLE
Duration of muxed mp4 video is too long

### ISSUE THREAD

**Issue by BinaryJava** [axiomatic-systems/Bento4#690]
I have demuxed a 56 second dvhe.05.09 mp4 file into h265 and ec3 files. When I mux them together, I end up with a 56 min 12 s video file which has 56 seconds of audio. This is the command I am using: `./mp4mux --track out_1.h265#frame_rate=60,format=dvh1,dv_profile=5 --track out_2.ec3 output.mp4`

**Comment by barbibulle** [comment]
Hi. Would it be possible to post examples files so that we can reproduce this issue?

**Comment by BinaryJava** [comment]
https://drive.google.com/file/d/1-Z6xOAJPgcGzIk9MqdzIy6nuaFQLfn7y/view?usp=sharing

**Comment by BinaryJava** [comment]
Was anyone able to replicate on their end? All I want to do is change the codec id to dvh1, so not sure if that affects timings.
