### ISSUE TITLE
Option to include '#EXT-X-ALLOW-CACHE:YES' in HLS SubtitlesPlaylist

### ISSUE THREAD

**Issue by flipmcf** [axiomatic-systems/Bento4#693]
I just need this option in my segment playlist header.  This is all.

```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1

```

**Comment by flipmcf** [comment]
Note that I only enhanced the non-iframe section.   If the iframe code is triggered the new cache option is ignored.

This also only applies to mp42hls  This doesn't touch mp4hls or the python implementation.   I only needed the segment playlists altered.

I wanted to touch as little code as possible to suit only my very specific issue. 
I don't want to introduce any new bugs or complications.

**Comment by barbibulle** [comment]
Thanks for the PR. I ended up pushing a commit with a slightly more generic version of the same option. Please note that the `EXT-X-ALLOW-CACHE` tag was removed in protocol version 7.
