### ISSUE TITLE
Insert 360 video metadata

### ISSUE THREAD

**Issue by aleksey2403** [axiomatic-systems/Bento4#71]
Hello,

I am trying add 360 video metadata to the .mp4 video file using this library. The goal is to make the video recognized by Youtube and Facebook as a 360 video. I was following the specs of 360 video metadata format given here:
https://github.com/google/spatial-media

Basically, I need to insert an xml file to the following box: 
moov.trak.uuid
where uuid is ffcc8263-f855-4a93-8814-587a02521fdd.

Is it possible to do with this library? I was trying to use mp4info on a valid 360 video file, but I cannot even see the required xml metadata in the console logs.

Thanks for any help!

Alex

**Comment by rodolforubens** [comment]
Hi @barbibulle , any news on this?

**Comment by barbibulle** [comment]
The latest version of the mp4edit tool will allow you to insert UUID boxes, so you should be able to use that to insert the necessary XML file.
For example, `mp4edit --insert moov/trak[1]:ffcc8263f8554a938814587a02521fdd#metadata.xml video.mp4 video360.mp4`  to insert the metadata in the second track.
