### ISSUE TITLE
Playreaedy encryption

### ISSUE THREAD

**Issue by gweberk** [axiomatic-systems/Bento4#74]
Hey! I'm trying to encrypt a content using playready. I use a fragmented file generated by mp4fragment, and use the same example of Bento4's page.

`/usr/local/bin/mp4-dash.py -f -d --exec-dir=/usr/local/bin/bento4 --encryption-key=09e367028f33436ca5dd60ffe6671e70:b42ca3172ee4e69bf51848a59db9cd13 --playready-header=LA_URL:http://playready.directtaps.net/pr/svc/rightsmanager.asmx filefragmented.mp4`

I also tried using the microsoft test server's keyseed

`--encryption-key=09e367028f33436ca5dd60ffe6671e70:#XVBovsmzhP9gRIZxWfFta3VVRPzVEWmJsazEJ46I`

Also using the `--encryption-args="--global-option mpeg-cenc.piff-compatible:true"` option.

I always have the same error (IE 11):
 In shaka player I got error code 3016, MEDIA.VIDEO_ERROR and 3014: MEDIA_SOURCE_OPERATION_FAILED
In dash.js I got MEDIA_ERR_SRC_NOT_SUPPORTED 

If I set a clear lead I got the same errors (Never plays anything)

I read about a similar issue, there is any solution about this? Am I doing something wrong?

**Comment by barbibulle** [comment]
Are you attempting playback on a "real" PC, or in a virtual machine? If you're running Windows in a VM, you will definitely see this type of error when playing content with PlayReady protection.
If you're on a "real" PC, both Shaka and dash.js should work. I can provide a URL to some test content if that's helpful.

**Comment by gweberk** [comment]
I'm testing on a real PC. If you have an URL to some content generated with MP4-DASH It would be helpful.

**Comment by barbibulle** [comment]
Which version of Bento4 are you using? One of the features introduced in the release prior to the last one, which included an 'EME' header in the DASH MPD file, was found to cause problems with some PlayReady clients in browsers. The latest release now makes this EME header optional and off by default. So that may be what's causing the problem for you. Can you check?

**Comment by gweberk** [comment]
I was using "Bento4-SDK-1-4-3-608.x86_64-unknown-linux.zip". It works when I update to "Bento4-SDK-1-5-0-610.x86_64-unknown-linux". Thank you very much! 

Now plays in IE11 but I can't find any request to the key server on the network tab in the developer tools. I change la_url when encrypting, and in the player config to a random data and the video is still playing. The key is stored somewhere in the metadata?

**Comment by barbibulle** [comment]
The reason you're not seeing any request to the key server is that the license you acquired is a persistent license. Once acquired the first time, it gets stored locally, so subsequent playbacks will obtain the key from the local copy of the license. There is a way to remove the file in which the licenses are stored (I forgot exactly where that file is, but you should be able to google it), or you can configure your license server to issue non-persistent licenses, in which case a license will be acquired from the server for every playback session,

**Comment by gweberk** [comment]
It's working thank you!

There's a Microsoft utility to remove stored licenses. Changing KID also solved this problem.

**Comment by barbibulle** [comment]
Good to know. Can you point me to this Microsoft utility? That can be very useful when testing.

**Comment by gweberk** [comment]
Sorry, but that utility It's part of Playready server SDK and I'm not able to share it. The documentation says:

> The MSPRClean.exe utility is used to erase all licenses, certificates, and associated data, and completely reset the digital rights management state that PlayReady PC runtime stores on a computer. This utility also removes individualization, effectively allowing PlayReady to start over as if it were installed for the first time.> 

I think it's included in the tools of the client SDKs and the porting Kit, if you have one of them.

**Comment by barbibulle** [comment]
Thanks. I have access to a PlayReady server SDK as well as a client SDK, so I’ll go look there.

-- Gilles


On May 27, 2016 at 9:01:55 AM, gweberk (notifications@github.com) wrote:

Sorry, but that utility It's part of Playready server SDK and I'm not able to share it. The documentation says:

The MSPRClean.exe utility is used to erase all licenses, certificates, and associated data, and completely reset the digital rights management state that PlayReady PC runtime stores on a computer. This utility also removes individualization, effectively allowing PlayReady to start over as if it were installed for the first time.>

I think it's included in the tools of the client SDKs and the porting Kit, if you have one of them.
