### ISSUE TITLE
Not handling (seemingly) incorrect DefaultSampleInfoSize

### ISSUE THREAD

**Issue by glennguy** [axiomatic-systems/Bento4#742]
Hi there,

I've been trying to fix an issue when playing certain streams in Kodi with inputstream.adaptive and I'm starting to get a bit stuck. (related issue - https://github.com/xbmc/inputstream.adaptive/issues/1007)

In the attached sample files when trying to create a `CencSampleInfoTable` it runs into an issue that eventually leads to a crash.
The `saiz` box holds a default sample info size of 30 which seems to be at odds with the actual content of the `senc` box:

![image](https://user-images.githubusercontent.com/11909320/185789461-9bc46b6b-5570-4b67-9da3-f8a7df195367.png)

![image](https://user-images.githubusercontent.com/11909320/185789448-fe44995d-9e5d-4a28-be22-b55b5a7b64d2.png)

So yes it appears the source video is 'wrong', however other players seem to handle it fine.

One though I had was to do a more step-by-step reading of the aux info data instead of trusting the default length here: https://github.com/axiomatic-systems/Bento4/blob/df9ba99a3d7f37547ab610c84166239fde012cdf/Source/C%2B%2B/Core/Ap4CommonEncryption.cpp#L2915-L2938

Something like (psuedo code):
* if per sample IV, read IV
* read subsample count
* for each subsample read clear bytes, encrypted bytes

If however I'm wrong by any measure please advise, I know a little about this library but not much.

Grateful for your help on this

Thanks

Glenn

[cbcs.zip](https://github.com/axiomatic-systems/Bento4/files/9388988/cbcs.zip)

**Comment by glennguy** [comment]
Small update:

Even if I patch in to change `info_size` from 30 to 28 in the block quoted above there are still issues with this file (picture is not decoded correctly plus crashes)
After creating the sample table the members look like this:
![image](https://user-images.githubusercontent.com/11909320/185791581-d570ea51-7515-49f3-9af1-f418e0cb7d38.png)
`SubSampleMapStarts` and `SubSampleMapLengths` only receive one item when doing a `AddSubSampleData` with subsample count of 2.
However this causes problems here: https://github.com/axiomatic-systems/Bento4/blob/df9ba99a3d7f37547ab610c84166239fde012cdf/Source/C%2B%2B/Core/Ap4CommonEncryption.cpp#L3158-L3186

Once this is called with an index greater than the amount of items in the map starts/lengths then (at least in debug) we're reading uninitialized memory and eventually attempt to access outside the array.

Hoping this helps

**Comment by barbibulle** [comment]
There are two issues to address here: 
1/ Clearly, the file is wrong. But that's not an excuse for the code to crash. The code should gracefully handle all sorts of input, right or wrong. This is something I'll fix right away.
2/ Is there a way to somehow be resilient to the error in the input in a way that a) allows a correct result, and b) doesn't risk introducing a behavior that could break valid, compliant, input files that may use the specification in unusual yet valid ways. I will look into this closely to see if I can come up with something that'd work for this type of wrong input.

**Comment by barbibulle** [comment]
Also, about the correct value that should have been used in this specific file for the default sample info size is 14 (not 30, nor 28 as you tried in your experiment). That’s 2 entries for each sample, where each entry is 6 bytes, and each list of entry (per sample) is preceded with a 2-byte entry count: 2+2*6 = 14. There are 192 samples, so a total table size of 2688 bytes.
Out of curiosity, do you know which software was used to create this file? It would be nice to reach out to the author and let them know about the issue with the output of their software.

**Comment by glennguy** [comment]
Thanks heaps for looking into and the quick response!

The content provider has their content hosted on axprod.net which is Axinom. According to https://github.com/Axinom/drm-quick-start they have their own packager called 'Makemedia' which does the encoding/encrypting. The provider is 'Optus Sport', and this behavior is seen in their live channels.

Thanks also for the correction in 28 vs 14, I'll try later to see if this produces a good result.

**Comment by glennguy** [comment]
Confirming that as you suggested setting this value to 14 works well - everything seems to parse correctly. I have to figure out now how to get the CDM to handle subsamples == 2/CBCS but that is an inputstream.adaptive problem.

**Comment by glennguy** [comment]
Also please see attached an example from the same service where there are varying subsample counts, sample sizes are listed as 30 and 24 instead of 14 and 8. 

https://user-images.githubusercontent.com/11909320/187906177-afa3b291-1544-4133-b210-84fd0f8594ce.mp4

**Comment by barbibulle** [comment]
I've pushed an update to the main branch that should be more resilient to invalid saio/saiz tables (if the parsing of those tables fails, but there's a valid `senc` table, it will automatically be used instead).
Could give it a try and let me know if it works for you?

**Comment by glennguy** [comment]
@barbibulle Yes this seems to work well, thank you for your help!
