### ISSUE TITLE
How to encrypt HLS fragments with the key and get Flowplayer to play it with the key encryption.

### ISSUE THREAD

**Issue by powersg2** [axiomatic-systems/Bento4#75]
I have tried to use MP4H2LS to generate fragment TS and encrypt it with the Key. While try to play it with flowplayer to decrypt with the key specified in the file-

Below is the comand I used:
C:\mp42hls\bin\mp42hls --verbose --segment-duration 10 --encryption-key d7bdf7e841400c5138dc2000074d7c1420c507503bd00dbd --encryption-mode AES-128  c:\mp42hls\rmn_ast_001.mp4

Then I added "d7bdf7e841400c5138dc2000074d7c1420c507503bd00dbd" into the file "key.bin". FlowPlayer not able to play it with the message "Video not properly encoded".

I am not sure where I am wrong - Can you help me to provide example the of the command line and what is the right format key to put into URI or File.txt.

**Comment by barbibulle** [comment]
There are two issues here I believe:
1/ the key that you are supplying isn't 128-bit long, it is too long. 128-bits is 16 bytes, which is 32 hex characters. Your key here is 24 bytes long.

2/ if you create a file for the key, the key must be in binary, not hex, so make sure that this is what you are writing in your key file (it should be 16 bytes long)

**Comment by powersg2** [comment]
1/ Is there any tools out there that can generate 32 hex characters?
2/ the file for the key - do I need to convert it from hex to the binary?

Can you give me some example - I am really stuck for weeks. Not much reference from my google. Really appreciate your help.

**Comment by barbibulle** [comment]
the key is just a random number, so any good random number generator can produce 16 bytes of data. You can write a simple tool to generate the key for you and save it to a file, as well as printing it in hex. Any language like python, java, C can do this in a few lines of code.
If you're on a unix-like platform (Linux, Mac OSX), you can also use command line tools to do this. For example, this will generate a 16-byte file named key.bin with 16 random bytes:
dd if=/dev/urandom of=key.bin bs=16 count=1
and this will give you a hex representation of those 16 bytes:
xxd -ps key.bin

**Comment by powersg2** [comment]
Dear Barbibulle,
Awesome!! It is working perfectly now. Thousands Thanks, you are really good.

**Comment by aromes** [comment]
Hello,
Thank you Barbibulle for your explanations.
I'm on Windows and I would like to do the same thing. Using OpenSSL, I can generate a random hex key like
`rand -hex 16 > NomFichier.txt`
Or generate the binary key like this:
`rand 16 > key.bin`
But I can't find out how to generate one key with two output or convert the hex one to a binary one.
Would you have some advice please?

**Comment by barbibulle** [comment]
An easy solution here is to generate your key file in binary (`rand 16 > key.bin`), then use a tool to look at a hex dump of the 16 bytes in the file. 
If you don't have such a command-line tool in your Windows system, you can do that with one line of python:
python -c "print open('key.bin', 'rb').read().encode('hex')"

**Comment by openaspace** [comment]
the best is to generate a different key for each chunk of http hls.
