### ISSUE TITLE
mp4fragment incorrect timescale in sidx box

### ISSUE THREAD

**Issue by michelnok** [axiomatic-systems/Bento4#76]
When mp4fragment timescale option is used (for example, --timescale 10000000), it computes segment durations according to requested timescale, but then writes sidx.timescale given from original track info.

**Comment by barbibulle** [comment]
Thanks for reporting that. We'll fix this ASAP.

**Comment by michelnok** [comment]
As I see, it was fixed in commit c29960fb757b0ae784d8c83214e3cb5af16517ad. Thank you!
