### ISSUE TITLE
AP4_FileWriter::Write performance

### ISSUE THREAD

**Issue by Grinchman** [axiomatic-systems/Bento4#8]
As you remember, I've implemented function that merge several mp4 files to one for Android application. In general it works fine. But now I'm doing measuring of that operation's performance and compare it with the same operation but written in Java using google's interface.

So, my expectations was that C++ library will be much faster than Java implementation . But result dissapointed me, performance almost unchanged (I use Nexus 5 device for measuring): two FullHD files with duration of 60 sec. each was merged in 23 sec., the same 4 files was merged in 48 sec.

Logs shown me that the most slow function is AP4_FileWriter::Write(AP4_File& file, AP4_ByteStream& stream, Interleaving interleaving = INTERLEAVING_SEQUENTIAL)

Maybe you have any suggestions how to improve performance of writing file operation? Maybe may I change something localy in my version of Bento4 library to achieve that? 

Thanks in advance for you time and great feedback in previous issue )

**Comment by barbibulle** [comment]
A C++ implementation isn't likely to be any faster than a Java implementation for this, as this process is mostly I/O bound, so the limiting factor is how fast you can read/write to/from storage, not how fast you can process the data.

**Comment by Grinchman** [comment]
You are right! I've made more carefully testing and found that I bumped into the limit of flash storage write speed. Sorry for false 'indict' )
