### ISSUE TITLE
Is it actually possible to write your own DRM backend service?

### ISSUE THREAD

**Issue by venomone** [axiomatic-systems/Bento4#805]
Hey folks,

I'm very interested in DRM technology as I'm building on a VOD platform. Basically the packaging process is fully done but currently without DRM. As I'm not interested in paying for a DRM provider, I would like to know if it is potentially possible to write your own Key exchange service for that? Or do I really need to pay a license fee here?

Thanks in advance and sorry if this might be the wrong place to ask this qustion.

**Comment by YannickFuereder** [comment]
You could just use clearkey encryption

When using clearkey the user can access the decryption keys and decrypt the video!

If you dont want that to happen the best solution would be Widevine as it has support for almost all devices
Tradeoff here is the price

Widevine can only hide the decryption keys from the user because every modern browser has a built in Widevine module that grabs the decryption keys without exposing them to the client

When coding your own key exchange service you would have to create a module like this and get Firefox etc to implement it into their browser


If you have more questions feel free to ask 😀

**Comment by venomone** [comment]
@YannickFuereder Hello, thanks for your reply. My biggest problem currently is that I don't want to have a contract with any DRM provider, and I'm really asking myself how can I do this? Currently, I secure my videos by using a JWT that has to be attached to every segment request of a video stream, but this is far away from a real protection, even widevine is if you look at tools like Anystream which very successfully has unlocked any DRM of any bigger VOD provider even for 4K HDR content at widevine L1 ...
So the protection of content is as always not really possible ... Why should I pay for a solution that just makes it harder to grab stuff, but not impossible?
With this in mind, I really don't see any need to apply for a contract with any DRM provider, as in the end this is wasted money. Google does by far not update Widevine often enough in order to get a tool like Anystream loose ...

So the question is, are there any "free" solutions except of clearkey?

Thanks :)

**Comment by YannickFuereder** [comment]
Nope
all the other drm solutions like Playready or Fairplay only work on specific devices

Here is a list of all supported devices with each drm solution
[https://castlabs.com/resources/drm-comparison/](https://castlabs.com/resources/drm-comparison/)

If you only want to target apple devices you could use Fairplay
I think there is a free self hosted solution available

**Comment by uwuforever** [comment]
I assume you're just trying to set up your own license server. So... yes, it's possible, and for the most part, all of the information you need can be found on Google or Github if you're willing to spend the time.

**BUT** you'll need to apply for and be approved for a digital certificate from each DRM vendor.

The Fairplay certificate requires you to sign up for an Apple Developer account which is $108/year, but once you get the certificate, it never expires, even if you cancel the developer account.

Widevine and PlayReady certificates are supposedly free from the vendors... however, it seems to only be available for active businesses. PlayReady requires you to verify your business by purchasing an EV code signing certificate, which can be a few hundred dollars.

**Comment by venomone** [comment]
Thanks for all your hello guys. I ended with blank AES-128 encryption.
