### ISSUE TITLE
Question: Does the order of the output of mp4dump reflect the order of the atoms in the file?

### ISSUE THREAD

**Issue by contentfree** [axiomatic-systems/Bento4#822]
I'm trying to use mp4dump to determine if the MOOV atom is at the front of the file or at the end. In the output of my file, the MOOV atom is printed before the MDAT atom (and in fact it is the second atom printed behind `ftyp`). 

Is that the order in the actual file?

**Comment by barbibulle** [comment]
Yes, `mp4dump` prints the boxes in the order they appear in the file.

**Comment by contentfree** [comment]
Thanks for the clarification!
