### ISSUE TITLE
Dedicated directory in case Single resolution Dash Packaging

### ISSUE THREAD

**Issue by tanmayapatramuvi** [axiomatic-systems/Bento4#827]
Hello Bento4 Support,

When I package a single resolution video it stores the output inside "output/video/avc1/<here>". But when I package a video with multiple resolution, it stroes the output inside "output/video/avc1/1/<here>; output/video/avc1/2/<here>; so on ..".

Q. If I want to store Single resolution Packaging inside "**output/video/avc1/1**/<here>", then what to do ??

Please suggest.

Thanks
Tanmaya Patra

**Comment by barbibulle** [comment]
The packager currently always tries to keep the direction depth to a minimum. There's no option to force it to create the extra sub-directories used to separate multiple bitrates (or audio languages, or bitrates) when needed.

**Comment by tanmayapatramuvi** [comment]
> The packager currently always tries to keep the direction depth to a minimum. There's no option to force it to create the extra sub-directories used to separate multiple bitrates (or audio languages, or bitrates) when needed.

Okay. Actually we needed this feature for one of our feature. Anyways we will manage it with our script.

Thanks.
