### ISSUE TITLE
mp4dash not working with encrypted input and --clearkey

### ISSUE THREAD

**Issue by mahmoudkhudairi11** [axiomatic-systems/Bento4#856]
I have pre encrypted video (using mp4encrypt)
then I pass it to mp4dash but the MPD does not include any KID when I use --clearkey, however when I set --widevine the KID appeared

**Comment by barbibulle** [comment]
Thanks for reporting this. You're right, if you have a pre-encrypted input and are not using any of the DRMs, the tool currently fails to add the content protection section. A fix will be pushed shortly for this.
