### ISSUE TITLE
HLS AUDIO AAC 7.1 CHANNELS 7 mistake

### ISSUE THREAD

**Issue by legosoff** [axiomatic-systems/Bento4#859]
<HTML><HEAD></HEAD>
<BODY>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY><TR>
<TD width=150>
<H2>Audio</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>1</TD></TR>
<TR>
<TD><I>Format :</I></TD>
<TD colSpan=3>AAC LC</TD></TR>
<TR>
<TD><I>Format/Info :</I></TD>
<TD colSpan=3>Advanced Audio Codec Low Complexity</TD></TR>
<TR>
<TD><I>Codec ID :</I></TD>
<TD colSpan=3>mp4a-40-2</TD></TR>
<TR>
<TD><I>Duration :</I></TD>
<TD colSpan=3>1 h 52 min</TD></TR>
<TR>
<TD><I>Bit rate mode :</I></TD>
<TD colSpan=3>Constant</TD></TR>
<TR>
<TD><I>Nominal bit rate :</I></TD>
<TD colSpan=3>128 kb/s</TD></TR>
<TR>
<TD><I>Channel(s) :</I></TD>
<TD colSpan=3>8 channels</TD></TR>
<TR>
<TD><I>Channel layout :</I></TD>
<TD colSpan=3>C L R Ls Rs Lw Rw LFE</TD></TR>
<TR>
<TD><I>Sampling rate :</I></TD>
<TD colSpan=3>48.0 kHz</TD></TR>
<TR>
<TD><I>Frame rate :</I></TD>
<TD colSpan=3>46.875 FPS (1024 SPF)</TD></TR>
<TR>
<TD><I>Compression mode :</I></TD>
<TD colSpan=3>Lossy</TD></TR>
<TR>
<TD><I>Language :</I></TD>
<TD colSpan=3>English</TD></TR></TBODY></TABLE></BODY></HTML>

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio/mp4a.40.2",LANGUAGE="en",NAME="English 7.1 | Original",AUTOSELECT=YES,DEFAULT=NO,CHANNELS="7",URI="audio/en/mp4a.40.2/media.m3u8"
СHANNELS="7"  wrong, should be on 8.

**Comment by barbibulle** [comment]
Hi. Thanks for reporting this issue. Would it be possible to share a link to a file encoded with AAC 7.1 using the same parameters as what you've been using, so that we can verify a fix on our side?

**Comment by legosoff** [comment]
https://drive.google.com/file/d/1uG6NVl_iHPeeY61ZK1PU_BfyYlb_STWb/view?usp=share_link

**Comment by legosoff** [comment]
I have windows 10, version 1.6.0.640  mp4dash.bat --hls
