### ISSUE TITLE
SUBTITLES problem

### ISSUE THREAD

**Issue by legosoff** [axiomatic-systems/Bento4#861]
Good afternoon! Subtitles are one en_full.vtt after creation, media.m3u8 is fine, and when 2 or 3 en_full.vtt, en_sdh.vtt and en_comment.vtt after creation, one is obtained in the media.m3u8 file - there is en_full.vtt, and there are still 2 en_sdh.vtt and en_comment.vtt yes files, media.m3u8 no file. Windows 10, Version 1.6.0-640.

[+format=webvtt,+language=en,+language_name=en]"C:\temp\JACK_THE_GIANT_SLAYER_2013_BD.en_Full.vtt"  media.m3u8 yes
[+format=webvtt,+language=en,+language_name=en]"C:\temp\JACK_THE_GIANT_SLAYER_2013_BD.en_SDH.vtt" media.m3u8 no
[+format=webvtt,+language=en,+language_name=en]"C:\temp\JACK_THE_GIANT_SLAYER_2013_BD.en_Comment.vtt" media.m3u8 no

**Comment by legosoff** [comment]
> Good afternoon! Subtitles are one en_full.vtt after creation, media.m3u8 is fine, and when 2 or 3 en_full.vtt, en_sdh.vtt and en_comment.vtt after creation, one is obtained in the media.m3u8 file - there is en_full.vtt, and there are still 2 en_sdh.vtt and en_comment.there is yes vtt in the media.m3u8 no file. Windows 10, Version 1.6.0-640.
> 
> [+format=webvtt,+language=en,+language_name=en]C:\temp\JACK_THE_GIANT_SLAYER_2013_BD.en_Full.vtt media.m3u8 yes [+format=webvtt,+language=en,+language_name=en]"C:\temp\JACK_THE_GIANT_SLAYER_2013_BD.en_SDH.vtt" media.m3u8 no [+format=webvtt,+language=en,+language_name=en]"C:\temp\JACK_THE_GIANT_SLAYER_2013_BD.en_Comment.vtt" media.m3u8 no

**Comment by legosoff** [comment]
Does it seem right to me? 

[+format=webvtt,+language=en,+language_name=en]
[+format=webvtt,+language=en1,+language_name=en1]
[+format=webvtt,+language=en2,+language_name=en2]

Is that right?

**Comment by barbibulle** [comment]
Hi. I'm not sure I fully understand the problem you're having. Are you trying to create an output stream with 3 subtitle tracks?
Can you share the command line you used, that may help get a better sense of what you're trying to do.

**Comment by legosoff** [comment]
I've already figured it out.
**language=en
language=en2
language=en3**
Now with running 3 tracks created a folder of three en, en2 and en3.

I've already figured it out.
**language=en
language=en
language=en**
Now the folder is one en here, there are no en2 and en3.

**Comment by barbibulle** [comment]
That's right. In the current model, you can only have one entry per language.
