### ISSUE TITLE
How to add HLS Characteristics attributes?

### ISSUE THREAD

**Issue by xavierlaffargue** [axiomatic-systems/Bento4#883]
Hi

I’ve 2 audio tracks, I would like to provide a video descriptive service, how can I add a characteristics attributes on the second one with this value public.accessibility.describes-video ?

Thank you for your help

**Comment by xavierlaffargue** [comment]
I don't have find an option so I created a pull request to add this feature : https://github.com/axiomatic-systems/Bento4/pull/885

**Comment by barbibulle** [comment]
Thanks for the PR :-)
