### ISSUE TITLE
mp4-dash - The Initialization range gets too small while creating On-Demand DASH representations

### ISSUE THREAD

**Issue by molvis** [axiomatic-systems/Bento4#89]
It would seem the Initialization range described in the mpd becomes one byte too small (say 0-1500 while it actually is 0-1501) in generated DASH OnDemand representations.

**Comment by barbibulle** [comment]
The @indexRange parameter follows the byte-range-spec syntax from RFC 2616, which means that the two range values are inclusive. Thus a range like 0-1500 means from byte 0 to 1500 inclusive, so it is 1501 bytes in total.

**Comment by molvis** [comment]
Thanks 
You are right, it the problem sat in the player application I used.
