### ISSUE TITLE
android build failed with NDK v12 on mac

### ISSUE THREAD

**Issue by lioliy** [axiomatic-systems/Bento4#92]
I type `scons -u build_config=Release target=arm-android-linux`

It cant find stdio.h by default
`Source/C++/Apps/Aac2Mp4/Aac2Mp4.cpp:32:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^`

so I download gcc-arm-none-eabi and change to this CCFLAGS = ['-I'+'/Users/lioliy/mv/11/20150925/arm-none-eabi/include','-I'+'/Users/lioliy/mv/11/20150925/arm-none-eabi/include/c++/4.9.3','-I'+'/Users/lioliy/mv/11/20150925/arm-none-eabi/include/c++/4.9.3/arm-none-eabi' 

But a minute later still build failed

`arm-linux-androideabi-g++ -o Build/Targets/arm-android-linux/Release/C++/Crypto/Ap4StreamCipher.o -c -fno-exceptions -fno-rtti -Wall -D_REENTRANT -O3 -I/Users/lioliy/mv/11/20150925/arm-none-eabi/include -I/Users/lioliy/mv/11/20150925/arm-none-eabi/include/c++/4.9.3 -I/Users/lioliy/mv/11/20150925/arm-none-eabi/include/c++/4.9.3/arm-none-eabi --sysroot /Users/lioliy/Library/Android/sdk/ndk-bundle/platforms/android-3/arch-arm -msoft-float -fpic -mthumb-interwork -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -D_REENTRANT -DANDROID -DNPT_CONFIG_HAVE_SYSTEM_LOG_CONFIG -ISource/C++/Core -ISource/C++/Crypto -ISource/C++/MetaData -ISource/C++/Codecs -ISource/Config Source/C++/Crypto/Ap4StreamCipher.cpp
arm-linux-androideabi-g++ -o Build/Targets/arm-android-linux/Release/C++/MetaData/Ap4MetaData.o -c -fno-exceptions -fno-rtti -Wall -D_REENTRANT -O3 -I/Users/lioliy/mv/11/20150925/arm-none-eabi/include -I/Users/lioliy/mv/11/20150925/arm-none-eabi/include/c++/4.9.3 -I/Users/lioliy/mv/11/20150925/arm-none-eabi/include/c++/4.9.3/arm-none-eabi --sysroot /Users/lioliy/Library/Android/sdk/ndk-bundle/platforms/android-3/arch-arm -msoft-float -fpic -mthumb-interwork -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -D_REENTRANT -DANDROID -DNPT_CONFIG_HAVE_SYSTEM_LOG_CONFIG -ISource/C++/Core -ISource/C++/Crypto -ISource/C++/MetaData -ISource/C++/Codecs -ISource/Config Source/C++/MetaData/Ap4MetaData.cpp
arm-linux-androideabi-g++ -o Build/Targets/arm-android-linux/Release/C++/System/Android/Ap4AndroidFileByteStream.o -c -fno-exceptions -fno-rtti -Wall -D_REENTRANT -O3 -I/Users/lioliy/mv/11/20150925/arm-none-eabi/include -I/Users/lioliy/mv/11/20150925/arm-none-eabi/include/c++/4.9.3 -I/Users/lioliy/mv/11/20150925/arm-none-eabi/include/c++/4.9.3/arm-none-eabi --sysroot /Users/lioliy/Library/Android/sdk/ndk-bundle/platforms/android-3/arch-arm -msoft-float -fpic -mthumb-interwork -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -D_REENTRANT -DANDROID -DNPT_CONFIG_HAVE_SYSTEM_LOG_CONFIG -ISource/C++/Core -ISource/C++/Crypto -ISource/C++/MetaData -ISource/C++/Codecs -ISource/Config Source/C++/System/Android/Ap4AndroidFileByteStream.cpp
Source/C++/System/Android/Ap4AndroidFileByteStream.cpp: In member function 'virtual AP4_Result AP4_AndroidFileByteStream::Seek(AP4_Position)':
Source/C++/System/Android/Ap4AndroidFileByteStream.cpp:255:5: error: 'off64_t' was not declared in this scope
     off64_t result = lseek64(m_FD, position, SEEK_SET);
     ^
Source/C++/System/Android/Ap4AndroidFileByteStream.cpp:256:9: error: 'result' was not declared in this scope
     if (result >= 0) {
         ^
Source/C++/System/Android/Ap4AndroidFileByteStream.cpp:262:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
scons: *** [Build/Targets/arm-android-linux/Release/C++/System/Android/Ap4AndroidFileByteStream.o] Error 1
scons: building terminated because of errors.`

I tried to build debug version `scons -u  target=arm-android-linux` but still this problem

How to fix this.Help me please.

**Comment by barbibulle** [comment]
Looks like something broke with NDK 12 (works with NDK 11). I'll investigate and fix the issue.

**Comment by barbibulle** [comment]
Here's what's going on: the default build setting is configured for the android-3 platform, which is no longer supported in NDK 12. We'll change the default.
Until then, you can manually choose the android platform you want to target, by setting the android_platform variable on the command line when building.
Example:
scons -u target=arm-android-linux android_platform=android-9
