### ISSUE TITLE
mp4encrypt with pssh

### ISSUE THREAD

**Issue by hassanzreik** [axiomatic-systems/Bento4#924]
trying to run below command 
getting `ERROR: invalid argument syntax for --pssh` 
```
mp4encrypt \
--show-progress \
--method MPEG-CENC \
--key 1:ad4abff38eXXXXXXdb1dc4:35582dcfaca35XXXXXXfc876de \
--property 1:KID:2380edc042XXXXX3 \
--pssh-v1 edef8ba9-79d6-4ace-a3c8-27dcd51d21ed:./ttt.bin \
PRW-YYY-frag.mp4 PRW-YYY-cenc.mp4
```

please advice, also if you can give example how to pass base64 pssh for widevine and playready and how to use mp4encrypt for fairplay

**Comment by elzalem** [comment]
You need to remove the `-` from the system id. It should be 32 characters long.
