### ISSUE TITLE
How to read frame by frame pixel data of mp4 file?

### ISSUE THREAD

**Issue by kunaldawn** [axiomatic-systems/Bento4#93]
I want to get frame by frame pixel data so that i can use in OpenGL texture (playing mp4 in opengl kinda stuff), is it possible with this library. Any small example will be awesome cool.

**Comment by kunaldawn** [comment]
Any updates on this?? Is H.264 decoded data can be retrieved from MP4 container?

**Comment by araipiyo** [comment]
You can use ffmpeg for obtaining pixel data. This software is to handle MP4 container, but not a H264 decoder.

**Comment by kunaldawn** [comment]
Thanks.
