### ISSUE TITLE
[REGRESSION] master branch have broken DolbyDigital streams

### ISSUE THREAD

**Issue by CastagnaIT** [axiomatic-systems/Bento4#975]
On Kodi media center software we builtin bento4 library to parse data packages
we have recently sync our project to bento4 master branch (at today commit 874c264a9d80dcddba0622b489eff25e223609f8)
and a lot of users reported broken DolbyDigital+ and atmos streams
ref. issues https://github.com/xbmc/inputstream.adaptive/issues/1617 https://github.com/matthuisman/slyguy.addons/issues/827
that i can also test/confirm by myself

initially i tried to revert only https://github.com/axiomatic-systems/Bento4/commit/66e29226d27784e39cddc7ff61240087f3618e88 but still broken

then i have reverted to [v1.6.0-641](https://github.com/axiomatic-systems/Bento4/releases/tag/v1.6.0-641) (last working release)
and added on top commits:
b92b7c3042a0f02d233dd5c9b3be2db804670b18
84b95d424c27d1dd7ec503377cab392a9434e8fb
147f15aac87e7cc16a686f1a7f8b10a8549d7508
because i need the c++20 compatibility, and its ok works
then the 3 commits above are not the cause of broken DD

I would not know what other data to provide to investigate the problem
but anyway on the debug there is no bento errors printed nor error raised, silently fails

kodi audio stream parser seem that is not able to detect eac3 anymore such as the data are corrupted

**Comment by barbibulle** [comment]
I have pushed an update which should fix the issue. Could you give it a try and let me know if it works for you?

**Comment by CastagnaIT** [comment]
seem to works correctly thanks
